import http from 'node:http';
import { readFileSync, existsSync } from 'node:fs';
import { extname, join, normalize } from 'node:path';
import { fileURLToPath } from 'node:url';
import { db, ensureStoreDay, todayISO, uid, audit } from './db.mjs';
import { canAccessStore, canManageQuality, canManageStore } from './services/permissions.mjs';
import { getProductByEan, getDynamicsHealth, postReceiptToDynamics } from './services/dynamics.mjs';
import { processProgress, takeOwnership, completeTask, validateProcess } from './services/workflow.mjs';

const PORT=Number(process.env.PORT||8787);
const FRONTEND=fileURLToPath(new URL('../frontend',import.meta.url));

function json(res,status,data){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(data));}
function body(req){return new Promise((resolve,reject)=>{let d='';req.on('data',c=>{d+=c;if(d.length>1e6)reject(new Error('Payload too large'))});req.on('end',()=>{try{resolve(d?JSON.parse(d):{})}catch(e){reject(e)}});req.on('error',reject)})}
function userFrom(req){const id=req.headers['x-demo-user']||'u-vf';return db.prepare(`SELECT * FROM users WHERE id=?`).get(String(id));}
function requireStore(user,storeId){if(!canAccessStore(user,storeId)){const e=new Error('Accès interdit à ce magasin.');e.status=403;throw e}}
function route(path,pattern){const a=path.split('/').filter(Boolean),b=pattern.split('/').filter(Boolean);if(a.length!==b.length)return null;const p={};for(let i=0;i<a.length;i++){if(b[i].startsWith(':'))p[b[i].slice(1)]=decodeURIComponent(a[i]);else if(a[i]!==b[i])return null}return p}
function dlcStage(expiry){const d=Math.ceil((new Date(expiry+'T23:59:59')-new Date())/86400000);if(d<0)return {stage:'EXPIRED',label:'Expirée',severity:'CRITICAL'};if(d<=1)return {stage:'J1',label:`J-${Math.max(d,0)}`,severity:'CRITICAL'};if(d<=3)return {stage:'J3',label:`J-${d}`,severity:'HIGH'};if(d<=7)return {stage:'J7',label:`J-${d}`,severity:'MEDIUM'};return {stage:'OK',label:`J-${d}`,severity:'LOW'}}

async function api(req,res,url){
  const user=userFrom(req); if(!user)return json(res,401,{error:'Utilisateur inconnu'});
  const path=url.pathname;
  if(path==='/api/health') return json(res,200,{ok:true,service:'StoreOps API',version:'1.3'});
  if(path==='/api/session') return json(res,200,{user,availableDemoUsers:db.prepare(`SELECT id,name,role,store_id FROM users ORDER BY role,name`).all()});
  if(path==='/api/dynamics/health') return json(res,200,await getDynamicsHealth());
  if(path==='/api/stores'){
    const rows=user.role==='ops_director'?db.prepare(`SELECT * FROM stores WHERE active=1 ORDER BY name`).all():db.prepare(`SELECT * FROM stores WHERE id=?`).all(user.store_id);
    return json(res,200,rows);
  }
  let p=route(path,'/api/products/:ean'); if(p){const product=await getProductByEan(p.ean);return product?json(res,200,product):json(res,404,{error:'Article introuvable'})}
  p=route(path,'/api/stores/:storeId/dashboard'); if(p){requireStore(user,p.storeId);const day=ensureStoreDay(p.storeId,url.searchParams.get('date')||todayISO());const opening=processProgress(day.id,'opening'),closing=processProgress(day.id,'closing');const dlcs=db.prepare(`SELECT * FROM dlc_records WHERE store_id=? AND status='ACTIVE' ORDER BY expiry_date`).all(p.storeId).map(x=>({...x,risk:dlcStage(x.expiry_date)}));const incidents=db.prepare(`SELECT * FROM incidents WHERE store_id=? AND status='OPEN' ORDER BY created_at DESC`).all(p.storeId);return json(res,200,{day,opening,closing,dlcAtRisk:dlcs.filter(x=>x.risk.stage!=='OK').length,incidents:incidents.length,criticalIncidents:incidents.filter(x=>x.criticality==='CRITICAL').length,health:Math.max(0,100-incidents.length*6-opening.blockers*4),lastActions:db.prepare(`SELECT a.*,u.name actor FROM audit_log a LEFT JOIN users u ON u.id=a.user_id WHERE a.store_id=? ORDER BY a.id DESC LIMIT 8`).all(p.storeId)})}
  p=route(path,'/api/stores/:storeId/tasks'); if(p){requireStore(user,p.storeId);const day=ensureStoreDay(p.storeId,url.searchParams.get('date')||todayISO());const group=url.searchParams.get('group');const rows=group?db.prepare(`SELECT * FROM tasks WHERE store_day_id=? AND group_name=? ORDER BY created_at`).all(day.id,group):db.prepare(`SELECT * FROM tasks WHERE store_day_id=? ORDER BY group_name,created_at`).all(day.id);return json(res,200,{day,tasks:rows,opening:processProgress(day.id,'opening'),closing:processProgress(day.id,'closing')})}
  p=route(path,'/api/stores/:storeId/process/:group/take'); if(p && req.method==='POST'){requireStore(user,p.storeId);if(!canManageStore(user,p.storeId))return json(res,403,{error:'Réservé au Responsable magasin ou Directeur d’exploitation'});const day=ensureStoreDay(p.storeId);takeOwnership({storeDay:day,user,group:p.group});return json(res,200,{ok:true})}
  p=route(path,'/api/tasks/:taskId/complete'); if(p && req.method==='POST'){const task=db.prepare(`SELECT t.*,sd.store_id FROM tasks t JOIN store_days sd ON sd.id=t.store_day_id WHERE t.id=?`).get(p.taskId);if(!task)return json(res,404,{error:'Tâche introuvable'});requireStore(user,task.store_id);const b=await body(req);completeTask({task,user,value:b.value});return json(res,200,{ok:true})}
  p=route(path,'/api/stores/:storeId/process/:group/validate'); if(p && req.method==='POST'){requireStore(user,p.storeId);if(!canManageStore(user,p.storeId))return json(res,403,{error:'Réservé au Responsable magasin ou Directeur d’exploitation'});const day=ensureStoreDay(p.storeId);const progress=validateProcess({storeDay:day,user,group:p.group});return json(res,200,{ok:true,progress})}
  p=route(path,'/api/stores/:storeId/dlc'); if(p){requireStore(user,p.storeId);if(req.method==='GET'){const rows=db.prepare(`SELECT d.*,u.name created_by_name FROM dlc_records d JOIN users u ON u.id=d.created_by WHERE d.store_id=? ORDER BY d.expiry_date`).all(p.storeId).map(x=>({...x,risk:dlcStage(x.expiry_date)}));return json(res,200,rows)}if(req.method==='POST'){if(!canManageStore(user,p.storeId))return json(res,403,{error:'Réservé au Responsable magasin ou Directeur d’exploitation'});const b=await body(req);const product=await getProductByEan(b.ean);if(!product)return json(res,400,{error:'EAN inconnu Dynamics'});if(!b.expiryDate||!(Number(b.quantity)>0))return json(res,400,{error:'DLC et quantité obligatoires'});const id=uid('dlc');db.prepare(`INSERT INTO dlc_records(id,store_id,ean,product_name,expiry_date,quantity,zone,lot_ref,comment,created_by) VALUES(?,?,?,?,?,?,?,?,?,?)`).run(id,p.storeId,b.ean,product.name,b.expiryDate,Number(b.quantity),b.zone||'Rayon',b.lotRef||null,b.comment||null,user.id);audit({storeId:p.storeId,userId:user.id,action:'DLC_CREATED',entityType:'DLC',entityId:id,details:{ean:b.ean,expiryDate:b.expiryDate,quantity:b.quantity}});return json(res,201,{id})}}
  p=route(path,'/api/stores/:storeId/quality'); if(p){requireStore(user,p.storeId);if(req.method==='GET'){const rows=db.prepare(`SELECT q.*,u.name controlled_by_name FROM quality_controls q JOIN users u ON u.id=q.controlled_by WHERE q.store_id=? ORDER BY q.created_at DESC`).all(p.storeId);return json(res,200,rows)}if(req.method==='POST'){if(!canManageQuality(user,p.storeId))return json(res,403,{error:'Qualité réservée au Responsable magasin ou Directeur d’exploitation'});const b=await body(req);const delivered=Number(b.deliveredQty),accepted=Number(b.acceptedQty),rejected=Number(b.rejectedQty);if(Math.abs(accepted+rejected-delivered)>0.0001)return json(res,400,{error:'Accepté + refusé doit être égal au livré'});const product=await getProductByEan(b.ean);if(!product)return json(res,400,{error:'EAN inconnu Dynamics'});const decision=rejected===0?'ACCEPT':accepted===0?'REJECT':'PARTIAL';const id=uid('qc');db.prepare(`INSERT INTO quality_controls(id,store_id,context,po_number,ean,product_name,ordered_qty,delivered_qty,accepted_qty,rejected_qty,temperature,packaging_status,appearance_status,expiry_date,lot_ref,decision,comment,controlled_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,p.storeId,b.context||'Contrôle ponctuel',b.poNumber||null,b.ean,product.name,b.orderedQty??null,delivered,accepted,rejected,b.temperature??null,b.packagingStatus||'NA',b.appearanceStatus||'NA',b.expiryDate||null,b.lotRef||null,decision,b.comment||null,user.id);if(b.expiryDate && accepted>0){const did=uid('dlc');db.prepare(`INSERT INTO dlc_records(id,store_id,ean,product_name,expiry_date,quantity,zone,lot_ref,comment,created_by) VALUES(?,?,?,?,?,?,?,?,?,?)`).run(did,p.storeId,b.ean,product.name,b.expiryDate,accepted,b.zone||'Réserve',b.lotRef||null,`Créée depuis contrôle qualité ${id}`,user.id)}if(decision!=='ACCEPT'){const inc=uid('inc');db.prepare(`INSERT INTO incidents(id,store_id,title,category,criticality,blocking_level,source_type,source_id,created_by) VALUES(?,?,?,?,?,?,?,?,?)`).run(inc,p.storeId,`Non-conformité réception · ${product.name}`,'QUALITY',b.temperature!=null&&Number(b.temperature)>6?'CRITICAL':'HIGH','NONE','QUALITY_CONTROL',id,user.id)}audit({storeId:p.storeId,userId:user.id,action:'QUALITY_CONTROL_CREATED',entityType:'QUALITY_CONTROL',entityId:id,details:{ean:b.ean,decision,delivered,accepted,rejected}});return json(res,201,{id,decision})}}
  p=route(path,'/api/stores/:storeId/receipts'); if(p){requireStore(user,p.storeId);const rows=db.prepare(`SELECT * FROM receipts WHERE store_id=? ORDER BY eta`).all(p.storeId).map(r=>({...r,lines:db.prepare(`SELECT * FROM receipt_lines WHERE receipt_id=?`).all(r.id)}));return json(res,200,rows)}
  p=route(path,'/api/receipts/:po/post'); if(p && req.method==='POST'){const r=db.prepare(`SELECT * FROM receipts WHERE po_number=?`).get(p.po);if(!r)return json(res,404,{error:'PO introuvable'});requireStore(user,r.store_id);if(!canManageQuality(user,r.store_id))return json(res,403,{error:'Réservé au Responsable magasin ou Directeur d’exploitation'});const lines=db.prepare(`SELECT * FROM receipt_lines WHERE receipt_id=?`).all(r.id);if(lines.some(l=>!l.quality_control_id))return json(res,409,{error:'Toutes les lignes doivent avoir un contrôle qualité avant réception système'});const dyn=await postReceiptToDynamics(r.po_number);db.prepare(`UPDATE receipts SET status='POSTED',posted_at=CURRENT_TIMESTAMP WHERE id=?`).run(r.id);audit({storeId:r.store_id,userId:user.id,action:'RECEIPT_POSTED',entityType:'RECEIPT',entityId:r.id,details:dyn});return json(res,200,dyn)}
  p=route(path,'/api/receipts/:po/lines/:lineId/quality'); if(p && req.method==='POST'){const r=db.prepare(`SELECT * FROM receipts WHERE po_number=?`).get(p.po);if(!r)return json(res,404,{error:'PO introuvable'});requireStore(user,r.store_id);if(!canManageQuality(user,r.store_id))return json(res,403,{error:'Réservé au Responsable magasin ou Directeur d’exploitation'});const line=db.prepare(`SELECT * FROM receipt_lines WHERE id=? AND receipt_id=?`).get(p.lineId,r.id);if(!line)return json(res,404,{error:'Ligne introuvable'});const b=await body(req);const delivered=Number(b.deliveredQty),accepted=Number(b.acceptedQty),rejected=Number(b.rejectedQty);if(Math.abs(accepted+rejected-delivered)>0.0001)return json(res,400,{error:'Accepté + refusé doit être égal au livré'});const decision=rejected===0?'ACCEPT':accepted===0?'REJECT':'PARTIAL';const id=uid('qc');db.prepare(`INSERT INTO quality_controls(id,store_id,context,po_number,ean,product_name,ordered_qty,delivered_qty,accepted_qty,rejected_qty,temperature,packaging_status,appearance_status,expiry_date,lot_ref,decision,comment,controlled_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,r.store_id,'Réception',r.po_number,line.ean,line.product_name,line.ordered_qty,delivered,accepted,rejected,b.temperature??null,b.packagingStatus||'NA',b.appearanceStatus||'NA',b.expiryDate||null,b.lotRef||null,decision,b.comment||null,user.id);db.prepare(`UPDATE receipt_lines SET delivered_qty=?,accepted_qty=?,rejected_qty=?,quality_control_id=? WHERE id=?`).run(delivered,accepted,rejected,id,line.id);if(b.expiryDate && accepted>0){const did=uid('dlc');db.prepare(`INSERT INTO dlc_records(id,store_id,ean,product_name,expiry_date,quantity,zone,lot_ref,comment,created_by) VALUES(?,?,?,?,?,?,?,?,?,?)`).run(did,r.store_id,line.ean,line.product_name,b.expiryDate,accepted,'Réserve',b.lotRef||null,`Réception ${r.po_number}`,user.id)}audit({storeId:r.store_id,userId:user.id,action:'RECEIPT_LINE_CONTROLLED',entityType:'RECEIPT_LINE',entityId:line.id,details:{decision,delivered,accepted,rejected}});return json(res,201,{id,decision})}
  if(path==='/api/network'){if(user.role!=='ops_director')return json(res,403,{error:'Réservé au Directeur d’exploitation'});const stores=db.prepare(`SELECT * FROM stores WHERE active=1 ORDER BY name`).all();const rows=stores.map(s=>{const day=ensureStoreDay(s.id);const opening=processProgress(day.id,'opening'),closing=processProgress(day.id,'closing');const incidents=db.prepare(`SELECT COUNT(*) n,SUM(CASE WHEN criticality='CRITICAL' THEN 1 ELSE 0 END) crit FROM incidents WHERE store_id=? AND status='OPEN'`).get(s.id);const last=db.prepare(`SELECT a.action,a.created_at,u.name actor FROM audit_log a LEFT JOIN users u ON u.id=a.user_id WHERE a.store_id=? ORDER BY a.id DESC LIMIT 1`).get(s.id);return {...s,day,opening,closing,openIncidents:incidents.n||0,criticalIncidents:incidents.crit||0,lastAction:last||null}});return json(res,200,rows)}
  return json(res,404,{error:'Route API inconnue'});
}

function staticFile(req,res,url){let path=url.pathname==='/'?'/index.html':url.pathname;path=normalize(path).replace(/^\.\.(\/|\\|$)/,'');const file=join(FRONTEND,path);if(!file.startsWith(FRONTEND)||!existsSync(file)){res.writeHead(404);return res.end('Not found')}const type={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png'}[extname(file)]||'application/octet-stream';res.writeHead(200,{'content-type':type});res.end(readFileSync(file));}

const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,`http://${req.headers.host}`);if(url.pathname.startsWith('/api/'))return await api(req,res,url);return staticFile(req,res,url)}catch(e){console.error(e);return json(res,e.status||500,{error:e.message||'Erreur serveur',details:e.details||undefined})}});
server.listen(PORT,()=>console.log(`StoreOps V1.3 running on http://localhost:${PORT}`));
