import {api} from '../api.js';
import {app,isDirector} from '../state.js';
import {$,esc,status,toast} from '../ui.js';

let templates=[],assignments=[],processDataLoaded=false,processLoadPromise=null;
let view='home',wizardStep=1,editingTemplateId=null,editingAssignmentId=null;
let draft=blankDraft();

function blankDraft(){return{name:'',code:null,version:'1',moment:'OPENING',scope:'SOME',storeId:app.storeId||app.stores?.[0]?.id||'val-fleuri',frequency:'DAILY',steps:[{title:'',required:true,evidenceRequired:false}],blockingLevel:'STORE_OPENING',mandatory:true}}
function sampleData(){return{templates:[{id:'demo-open',active:true,code:'OPENING_PREMIUM',name:'Ouverture premium',version:'1',template:{code:'OPENING_PREMIUM',name:'Ouverture premium',version:'1',trigger:'DAILY',scope:'STORE',steps:[{code:'facade',title:'Façade & entrée impeccables',required:true,evidenceRequired:true,blockingLevel:'PROCESS'},{code:'fresh',title:'Contrôle Frais & Fruits/Légumes',required:true,evidenceRequired:false,blockingLevel:'PROCESS'},{code:'promo',title:'Têtes de gondole & promotions',required:true,evidenceRequired:false,blockingLevel:'PROCESS'}],gates:[]}}],assignments:[{id:'demo-a',template_id:'demo-open',template_name:'Ouverture premium',store_id:'val-fleuri',mandatory:true,blocking_level:'STORE_OPENING',active:true,effective_from:null,effective_to:null}]}}
async function ensureProcessData({force=false}={}){
 if(processDataLoaded&&!force)return;
 if(processLoadPromise&&!force)return processLoadPromise;
 processLoadPromise=(async()=>{if(app.showcase){const s=sampleData();templates=s.templates;assignments=s.assignments}else{const [t,a]=await Promise.all([api('/api/admin/process-templates?all=1'),api('/api/admin/process-assignments?all=1')]);templates=t.items||[];assignments=a.items||[]}processDataLoaded=true})();
 try{await processLoadPromise}finally{processLoadPromise=null}
}
const scopeLabel=id=>id?(app.stores.find(s=>s.id===id)?.name||id):'Tous les magasins';
const blockLabel=x=>x==='STORE_OPENING'?'Bloque l’ouverture':x==='STORE_CLOSING'?'Bloque la fermeture':x==='NONE'?'Rappel seulement':'Obligatoire à terminer';
function slug(v){return String(v||'PROCESS').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]+/g,'_').replace(/^_+|_+$/g,'').slice(0,34)||'PROCESS'}
function newCode(name){return `CUSTOM_${slug(name)}_${Date.now().toString(36).slice(-4).toUpperCase()}`}
function stepCode(title,i){const s=slug(title).toLowerCase().slice(0,28);return s||`step_${i+1}`}

function renderHome(){
 $('#adminStudioContent').innerHTML=`<div class="studio-hero"><div><div class="label">STOREOPS ADMIN STUDIO</div><h2>Qu’est-ce que vous voulez mettre en place ?</h2><p>Choisissez une intention. StoreOps cache la complexité technique et ne charge que ce dont vous avez besoin.</p></div><div class="studio-hero-badge"><strong>${processDataLoaded?templates.filter(x=>x.active).length:'—'}</strong><span>process actifs</span></div></div>
 <div class="studio-intent-grid">
  <button class="studio-intent-card primary" data-studio-action="new-process"><span class="studio-intent-icon">✓</span><strong>Créer un process magasin</strong><small>Ouverture, fermeture, qualité, réception, sécurité, inventaire…</small><em>Créer →</em></button>
  <button class="studio-intent-card" data-studio-action="existing"><span class="studio-intent-icon">☷</span><strong>Mes process</strong><small>Voir, modifier, activer ou désactiver les parcours publiés.</small><em>Gérer →</em></button>
  <button class="studio-intent-card" data-studio-target="replenishmentRulesSection"><span class="studio-intent-icon">↗</span><strong>Règles de réappro</strong><small>Couverture, délai, sécurité, colisage et règles par périmètre.</small><em>Configurer →</em></button>
  <button class="studio-intent-card" data-studio-target="storeSettingsSection"><span class="studio-intent-icon">🏬</span><strong>Magasins & entrepôts</strong><small>Warehouse magasin, source réseau, assortiment et identité D365.</small><em>Configurer →</em></button>
  <button class="studio-intent-card" data-studio-action="users"><span class="studio-intent-icon">👥</span><strong>Équipe & accès</strong><small>Créer les utilisateurs, rôles et périmètres sans passer par le code.</small><em>Configurer →</em></button>
  <button class="studio-intent-card" data-studio-action="integrations"><span class="studio-intent-icon">⇄</span><strong>Intégrations</strong><small>ERP, POS, WMS, PIM, RH et APIs par capacité.</small><em>Configurer →</em></button>
  <button class="studio-intent-card" data-studio-action="tenant"><span class="studio-intent-icon">✦</span><strong>Marque & vocabulaire</strong><small>Nom enseigne, couleurs, mots métier et modules activés.</small><em>Configurer →</em></button>
 </div><div id="studioExtensions"></div>`;
 bindHome()
}
function bindHome(){
 document.querySelector('[data-studio-action="new-process"]')?.addEventListener('click',()=>startWizard());
 document.querySelector('[data-studio-action="existing"]')?.addEventListener('click',async()=>{view='loading';render();try{await ensureProcessData();view='library';render()}catch(e){view='home';render();toast(e.message)}})
}

function startWizard(template=null){
 editingTemplateId=template?.id||null;editingAssignmentId=null;wizardStep=1;
 if(template){const a=assignments.find(x=>x.template_id===template.id&&x.active)||assignments.find(x=>x.template_id===template.id)||null;editingAssignmentId=a?.id||null;const level=a?.blocking_level||'PROCESS',moment=level==='STORE_OPENING'?'OPENING':level==='STORE_CLOSING'?'CLOSING':template.template?.trigger==='EVENT'?'EVENT':'DAY';draft={name:template.name,code:template.code,version:template.version||'1',moment,scope:a?.store_id?'SOME':'ALL',storeId:a?.store_id||app.storeId||app.stores[0]?.id||null,frequency:template.template?.trigger||'DAILY',steps:(template.template?.steps||[]).map(s=>({title:s.title,required:s.required!==false,evidenceRequired:!!s.evidenceRequired})),blockingLevel:level,mandatory:a?a.mandatory!==false:true};if(!draft.steps.length)draft.steps=[{title:'',required:true,evidenceRequired:false}]}
 else draft=blankDraft();view='wizard';render()
}
function captureWizard(){
 if(wizardStep===1)draft.name=$('#wizardName')?.value?.trim()||draft.name;
 if(wizardStep===2){draft.storeId=$('#wizardStore')?.value||draft.storeId;draft.frequency=$('#wizardFrequency')?.value||draft.frequency}
 if(wizardStep===3)document.querySelectorAll('[data-wizard-step]').forEach(row=>{const i=Number(row.dataset.wizardStep);if(!draft.steps[i])return;draft.steps[i].title=row.querySelector('[data-step-title]')?.value?.trim()||'';draft.steps[i].required=!!row.querySelector('[data-step-required]')?.checked;draft.steps[i].evidenceRequired=!!row.querySelector('[data-step-evidence]')?.checked})
}
function validateStep(n){if(n===1&&!draft.name.trim())return'Indique le nom du process.';if(n===2&&draft.scope==='SOME'&&!draft.storeId)return'Choisis le magasin concerné.';if(n===3&&(draft.steps.length<1||draft.steps.some(s=>!s.title.trim())))return'Donne un titre clair à chaque étape.';return null}
function goWizard(n){captureWizard();const err=n>wizardStep?validateStep(wizardStep):null;if(err)return toast(err);wizardStep=Math.max(1,Math.min(5,n));render()}
function momentLabel(){return({OPENING:'Avant l’ouverture',DAY:'Pendant la journée',CLOSING:'À la fermeture',EVENT:'Lors d’un événement'})[draft.moment]||draft.moment}
function ruleDescription(){return({NONE:'StoreOps rappelle l’action mais ne bloque pas le magasin.',PROCESS:'Le process doit être terminé et reste visible comme obligation.',STORE_OPENING:'Le magasin ne peut pas être déclaré ouvert tant que ce process n’est pas terminé.',STORE_CLOSING:'Le magasin ne peut pas clôturer la journée tant que ce process n’est pas terminé.'})[draft.blockingLevel]}
function wizardRail(){return `<aside class="studio-wizard-rail">${[['L’objectif','Que faut-il faire ?'],['Où & quand','Périmètre'],['Les étapes','Parcours RM'],['La règle','Si ce n’est pas fait'],['Aperçu','Voir comme le RM']].map((x,i)=>`<div class="studio-wizard-rail-step ${i+1===wizardStep?'active':''} ${i+1<wizardStep?'done':''}"><b>${i+1}. ${x[0]}</b><span>${x[1]}</span></div>`).join('')}</aside>`}
function navButtons({back=false,publish=false}={}){return `<div class="studio-wizard-actions"><button class="btn ghost" data-wizard-back>${back?'Retour':'Annuler'}</button>${publish?'<button class="btn brand" data-wizard-publish>Publier le process</button>':'<button class="btn brand" data-wizard-next>Continuer</button>'}</div>`}
function renderWizard(){
 let body='';
 if(wizardStep===1)body=`<div class="label">ÉTAPE 1 SUR 5</div><h2>Qu’est-ce que le magasin doit faire ?</h2><p class="muted">Décrivez le besoin comme vous le diriez au Responsable magasin.</p><label class="studio-guided-field"><span>Nom du process</span><input id="wizardName" value="${esc(draft.name)}" placeholder="Ex. Contrôle ouverture premium"></label><div class="studio-guided-label">À quel moment ?</div><div class="studio-choice-grid">${[['OPENING','Avant l’ouverture','Le magasin doit être prêt avant l’accueil client.'],['DAY','Pendant la journée','Contrôle ou action opérationnelle.'],['CLOSING','À la fermeture','Obligation avant clôture magasin.'],['EVENT','Lors d’un événement','Réception, incident, changement promo…']].map(([k,t,d])=>`<button class="studio-choice ${draft.moment===k?'selected':''}" data-moment="${k}"><strong>${t}</strong><small>${d}</small></button>`).join('')}</div>${navButtons()}`;
 if(wizardStep===2)body=`<div class="label">ÉTAPE 2 SUR 5</div><h2>Où et quand ?</h2><p class="muted">Choisissez simplement le périmètre.</p><div class="studio-choice-grid"><button class="studio-choice ${draft.scope==='ALL'?'selected':''}" data-scope="ALL"><strong>Tous les magasins</strong><small>Règle réseau.</small></button><button class="studio-choice ${draft.scope==='SOME'?'selected':''}" data-scope="SOME"><strong>Un magasin</strong><small>Commencer sur un périmètre précis.</small></button></div>${draft.scope==='SOME'?`<label class="studio-guided-field"><span>Magasin concerné</span><select id="wizardStore">${app.stores.map(s=>`<option value="${esc(s.id)}" ${draft.storeId===s.id?'selected':''}>${esc(s.name)}</option>`).join('')}</select></label>`:''}<label class="studio-guided-field"><span>Fréquence</span><select id="wizardFrequency"><option value="DAILY" ${draft.frequency==='DAILY'?'selected':''}>Tous les jours d’ouverture</option><option value="EVENT" ${draft.frequency==='EVENT'?'selected':''}>Quand l’événement est déclenché</option><option value="MANUAL" ${draft.frequency==='MANUAL'?'selected':''}>À la demande</option></select></label>${navButtons({back:true})}`;
 if(wizardStep===3)body=`<div class="label">ÉTAPE 3 SUR 5</div><h2>Que doit faire le magasin ?</h2><p class="muted">Chaque étape doit être comprise sans formation.</p><div class="studio-guided-steps">${draft.steps.map((s,i)=>`<div class="studio-guided-step" data-wizard-step="${i}"><div class="studio-step-number">${i+1}</div><div><input data-step-title value="${esc(s.title)}" placeholder="Ex. Vérifier la façade et l’entrée"><div class="studio-inline-options"><label><input type="checkbox" data-step-required ${s.required!==false?'checked':''}> Obligatoire</label><label><input type="checkbox" data-step-evidence ${s.evidenceRequired?'checked':''}> Demander une preuve</label>${draft.steps.length>1?`<button class="btn ghost" data-remove-wizard-step="${i}">Supprimer</button>`:''}</div></div></div>`).join('')}</div><button class="btn soft" id="wizardAddStep">+ Ajouter une étape</button>${navButtons({back:true})}`;
 if(wizardStep===4)body=`<div class="label">ÉTAPE 4 SUR 5</div><h2>Que se passe-t-il si ce n’est pas fait ?</h2><p class="muted">StoreOps appliquera réellement cette règle dans le parcours magasin.</p><div class="studio-choice-grid">${[['NONE','Rappeler seulement','Action visible en retard, sans blocage.'],['PROCESS','Obligatoire à terminer','Le process reste une obligation opérationnelle.'],['STORE_OPENING','Le magasin ne peut pas ouvrir','La validation d’ouverture reste bloquée.'],['STORE_CLOSING','Le magasin ne peut pas fermer','La clôture reste bloquée.']].map(([k,t,d])=>`<button class="studio-choice ${draft.blockingLevel===k?'selected':''}" data-blocking="${k}"><strong>${t}</strong><small>${d}</small></button>`).join('')}</div><div class="studio-rule-summary"><strong>${esc(blockLabel(draft.blockingLevel))}</strong><span>${esc(ruleDescription())}</span></div>${navButtons({back:true})}`;
 if(wizardStep===5){const first=draft.steps[0]||{title:'Étape'};body=`<div class="label">ÉTAPE 5 SUR 5</div><h2>Aperçu exact côté Responsable magasin</h2><p class="muted">On publie seulement après avoir vérifié l’expérience terrain.</p><div class="studio-preview-phone"><div class="studio-preview-meta">${esc(draft.scope==='ALL'?'Tous magasins':scopeLabel(draft.storeId))} · ${esc(momentLabel())}</div><div class="studio-preview-card"><div class="label">${esc(momentLabel().toUpperCase())} · 1 SUR ${draft.steps.length}</div><div class="studio-preview-progress"><span style="width:${Math.max(8,100/draft.steps.length)}%"></span></div><h3>${esc(first.title||'Première étape')}</h3><p>${first.evidenceRequired?'Une preuve sera demandée avant de pouvoir continuer.':'Validez cette étape puis passez à la suivante.'}</p>${first.evidenceRequired?'<div class="studio-preview-proof">📷 Ajouter la preuve obligatoire</div>':''}<button class="btn brand">Valider et continuer</button></div></div><div class="studio-publish-summary"><div><span>Périmètre</span><strong>${esc(draft.scope==='ALL'?'Tous les magasins':scopeLabel(draft.storeId))}</strong></div><div><span>Moment</span><strong>${esc(momentLabel())}</strong></div><div><span>Règle</span><strong>${esc(blockLabel(draft.blockingLevel))}</strong></div><div><span>Étapes</span><strong>${draft.steps.length}</strong></div></div>${navButtons({back:true,publish:true})}`}
 $('#adminStudioContent').innerHTML=`<div class="studio-guided-shell"><div class="studio-guided-top"><button class="btn ghost" id="wizardExit">← Admin Studio</button><span class="pill">${editingTemplateId?'Modifier':'Nouveau process'}</span></div><div class="studio-wizard-layout">${wizardRail()}<section class="studio-wizard-card">${body}</section></div></div>`;bindWizard()
}
function bindWizard(){
 $('#wizardExit')?.addEventListener('click',()=>{captureWizard();view='home';render()});
 document.querySelector('[data-wizard-back]')?.addEventListener('click',()=>wizardStep===1?(view='home',render()):goWizard(wizardStep-1));
 document.querySelector('[data-wizard-next]')?.addEventListener('click',()=>goWizard(wizardStep+1));
 document.querySelectorAll('[data-moment]').forEach(b=>b.onclick=()=>{captureWizard();draft.moment=b.dataset.moment;if(draft.moment==='OPENING')draft.blockingLevel='STORE_OPENING';else if(draft.moment==='CLOSING')draft.blockingLevel='STORE_CLOSING';else if(['STORE_OPENING','STORE_CLOSING'].includes(draft.blockingLevel))draft.blockingLevel='PROCESS';render()});
 document.querySelectorAll('[data-scope]').forEach(b=>b.onclick=()=>{captureWizard();draft.scope=b.dataset.scope;render()});
 document.querySelectorAll('[data-blocking]').forEach(b=>b.onclick=()=>{draft.blockingLevel=b.dataset.blocking;draft.mandatory=draft.blockingLevel!=='NONE';render()});
 $('#wizardAddStep')?.addEventListener('click',()=>{captureWizard();draft.steps.push({title:'',required:true,evidenceRequired:false});render()});
 document.querySelectorAll('[data-remove-wizard-step]').forEach(b=>b.onclick=()=>{captureWizard();draft.steps.splice(Number(b.dataset.removeWizardStep),1);render()});
 $('[data-wizard-publish]')?.addEventListener('click',()=>publishWizard().catch(e=>toast(e.message)))
}
async function publishWizard(){
 captureWizard();for(const n of [1,2,3]){const e=validateStep(n);if(e)return toast(e)}
 if(app.showcase)return toast('Aperçu Showcase : publication désactivée.');
 const code=draft.code||newCode(draft.name),steps=draft.steps.map((s,i)=>({code:stepCode(s.title,i),title:s.title.trim(),order:i+1,required:s.required!==false,evidenceRequired:!!s.evidenceRequired,blockingLevel:'PROCESS'})),payload={code,name:draft.name.trim(),version:draft.version||'1',trigger:draft.frequency,scope:'STORE',steps,gates:[]};
 const saved=await api(editingTemplateId?`/api/admin/process-templates/${encodeURIComponent(editingTemplateId)}`:'/api/admin/process-templates',{method:editingTemplateId?'PUT':'POST',body:payload});
 const assignmentBody={templateId:saved.id,storeId:draft.scope==='ALL'?null:draft.storeId,blockingLevel:draft.blockingLevel,mandatory:draft.blockingLevel==='NONE'?false:draft.mandatory,effectiveFrom:null,effectiveTo:null,active:true};
 await api(editingAssignmentId?`/api/admin/process-assignments/${encodeURIComponent(editingAssignmentId)}`:'/api/admin/process-assignments',{method:editingAssignmentId?'PUT':'POST',body:assignmentBody});
 toast(editingTemplateId?'Process mis à jour et republié.':'Process publié.');processDataLoaded=false;await ensureProcessData({force:true});editingTemplateId=null;editingAssignmentId=null;view='library';render()
}

function renderLibrary(){
 $('#adminStudioContent').innerHTML=`<div class="studio-guided-top"><button class="btn ghost" id="libraryBack">← Admin Studio</button><button class="btn brand" id="libraryNew">+ Nouveau process</button></div><div class="card studio-process-library"><div class="label">PROCESS PUBLIÉS</div><h2>Mes process magasin</h2><p class="muted">Modifiez le parcours, le périmètre ou la règle sans exposer les paramètres techniques.</p><div class="studio-process-cards">${templates.length?templates.map(t=>{const a=assignments.find(x=>x.template_id===t.id&&x.active)||assignments.find(x=>x.template_id===t.id),count=t.template?.steps?.length||0;return `<div class="studio-process-card"><div><div class="row"><strong>${esc(t.name)}</strong>${status(t.active?'Actif':'Inactif',t.active?'ok':'neutral')}</div><p>${esc(a?scopeLabel(a.store_id):'Non affecté')} · ${esc(a?blockLabel(a.blocking_level):'Aucune règle')} · ${count} étape(s)</p></div><div class="studio-process-card-actions"><button class="btn soft" data-edit-process="${esc(t.id)}">Modifier</button><button class="btn ghost" data-toggle-process="${esc(t.id)}">${t.active?'Désactiver':'Réactiver'}</button></div></div>`}).join(''):'<div class="empty">Aucun process publié.</div>'}</div></div>`;
 $('#libraryBack')?.addEventListener('click',()=>{view='home';render()});$('#libraryNew')?.addEventListener('click',()=>startWizard());document.querySelectorAll('[data-edit-process]').forEach(b=>b.onclick=()=>startWizard(templates.find(x=>x.id===b.dataset.editProcess)));document.querySelectorAll('[data-toggle-process]').forEach(b=>b.onclick=async()=>{const t=templates.find(x=>x.id===b.dataset.toggleProcess);if(app.showcase)return toast('Aperçu Showcase : écriture désactivée.');try{await api(`/api/admin/process-templates/${encodeURIComponent(t.id)}/active`,{method:'POST',body:{active:!t.active}});processDataLoaded=false;await ensureProcessData({force:true});toast(t.active?'Process désactivé.':'Process réactivé.');render()}catch(e){toast(e.message)}})
}
function renderLoading(){$('#adminStudioContent').innerHTML='<div class="studio-hero"><div><div class="label">ADMIN STUDIO</div><h2>Chargement de vos process…</h2><p>Le reste de l’Admin Studio reste disponible sans chargement supplémentaire.</p></div></div>'}
function render(){if(view==='wizard')return renderWizard();if(view==='library')return renderLibrary();if(view==='loading')return renderLoading();renderHome()}
export async function renderAdminStudio(){if(!isDirector())return;view='home';render()}
