import {api} from '../api.js';
import {app,isDirector} from '../state.js';
import {$,esc,status,toast} from '../ui.js';

let templates=[],assignments=[],editingId=null,draftSteps=[];
const blankStep=i=>({code:`step_${i+1}`,title:'',required:true,evidenceRequired:false,blockingLevel:'PROCESS'});
const blockingLabel=x=>x==='STORE_OPENING'?'Bloque ouverture':x==='STORE_CLOSING'?'Bloque fermeture':x==='NONE'?'Informatif':'Obligatoire process';
const scopeLabel=id=>id?(app.stores.find(s=>s.id===id)?.name||id):'Tous les magasins';

function sampleData(){return{
 templates:[{id:'demo-open',active:true,code:'OPENING_PREMIUM',name:'Ouverture premium',version:'1',template:{code:'OPENING_PREMIUM',name:'Ouverture premium',version:'1',trigger:'DAILY',scope:'STORE',steps:[{code:'facade',title:'Façade & entrée impeccables',required:true,evidenceRequired:true,blockingLevel:'STORE_OPENING'},{code:'fresh',title:'Contrôle Frais & Fruits/Légumes',required:true,evidenceRequired:false,blockingLevel:'STORE_OPENING'},{code:'promo',title:'Têtes de gondole & promotions',required:true,evidenceRequired:false,blockingLevel:'STORE_OPENING'}],gates:[]}}],
 assignments:[{id:'demo-a',template_id:'demo-open',template_name:'Ouverture premium',store_id:'val-fleuri',mandatory:true,blocking_level:'STORE_OPENING',active:true,effective_from:null,effective_to:null}]
}}

async function load(){if(app.showcase){const s=sampleData();templates=s.templates;assignments=s.assignments;return}const [t,a]=await Promise.all([api('/api/admin/process-templates?all=1'),api('/api/admin/process-assignments?all=1')]);templates=t.items||[];assignments=a.items||[]}
function currentTemplate(){return templates.find(x=>x.id===editingId)||null}
function resetDraft(){editingId=null;draftSteps=[blankStep(0)]}
function setEdit(t){editingId=t.id;draftSteps=(t.template?.steps||[]).map(x=>({...x}));if(!draftSteps.length)draftSteps=[blankStep(0)]}

function templateCard(t){const assigned=assignments.filter(a=>a.template_id===t.id&&a.active).length;return `<button class="studio-template-card ${editingId===t.id?'selected':''}" data-edit-template="${esc(t.id)}"><div class="row"><strong>${esc(t.name)}</strong>${status(t.active?'Actif':'Inactif',t.active?'ok':'neutral')}</div><div class="small muted">${esc(t.code)} · v${esc(t.version||'1')} · ${t.template?.steps?.length||0} étape(s)</div><div class="studio-card-foot"><span>${assigned} affectation(s)</span><span>Modifier →</span></div></button>`}
function stepEditor(s,i){return `<div class="studio-step-editor" data-step-index="${i}"><div class="studio-step-number">${i+1}</div><div class="studio-step-fields"><div class="grid g2"><label><span>Nom de l’étape</span><input data-step-field="title" value="${esc(s.title||'')}" placeholder="Ex. Contrôle façade"></label><label><span>Code</span><input data-step-field="code" value="${esc(s.code||`step_${i+1}`)}"></label></div><div class="studio-inline-options"><label><input type="checkbox" data-step-field="required" ${s.required!==false?'checked':''}> Obligatoire</label><label><input type="checkbox" data-step-field="evidenceRequired" ${s.evidenceRequired?'checked':''}> Preuve obligatoire</label><button class="btn ghost" data-remove-step="${i}" ${draftSteps.length===1?'disabled':''}>Supprimer</button></div></div></div>`}
function assignmentRow(a){return `<tr><td><strong>${esc(a.template_name)}</strong></td><td>${esc(scopeLabel(a.store_id))}</td><td>${status(blockingLabel(a.blocking_level),a.blocking_level==='NONE'?'neutral':a.blocking_level==='PROCESS'?'info':'danger')}</td><td>${a.mandatory?'Oui':'Non'}</td><td>${a.effective_from?esc(a.effective_from):'—'} → ${a.effective_to?esc(a.effective_to):'∞'}</td><td>${status(a.active?'Actif':'Inactif',a.active?'ok':'neutral')}</td><td><button class="btn soft" data-toggle-assignment="${esc(a.id)}">${a.active?'Désactiver':'Activer'}</button></td></tr>`}

function renderShell(){
 const t=currentTemplate(),activeTemplates=templates.filter(x=>x.active).length,activeAssignments=assignments.filter(x=>x.active).length,opening=assignments.filter(x=>x.active&&x.blocking_level==='STORE_OPENING').length,closing=assignments.filter(x=>x.active&&x.blocking_level==='STORE_CLOSING').length;
 $('#adminStudioContent').innerHTML=`
 <div class="studio-hero"><div><div class="label">STOREOPS ADMIN STUDIO</div><h2>Construire les règles opérationnelles sans redévelopper l’application.</h2><p>Crée les process, définis les preuves obligatoires, choisis le périmètre et décide si une étape bloque réellement l’ouverture ou la fermeture.</p></div><div class="studio-hero-badge"><strong>${activeTemplates}</strong><span>process actifs</span></div></div>
 ${app.showcase?'<div class="banner ban-info"><strong>Aperçu Showcase</strong><span>Cette vue illustre l’Admin Studio. Les boutons d’écriture seront actifs sur le backend V1.80 réel.</span></div>':''}
 <div class="studio-kpis"><div class="card"><span>Templates actifs</span><strong>${activeTemplates}</strong></div><div class="card"><span>Affectations actives</span><strong>${activeAssignments}</strong></div><div class="card"><span>Gates ouverture</span><strong>${opening}</strong></div><div class="card"><span>Gates fermeture</span><strong>${closing}</strong></div></div>
 <div class="studio-layout">
  <aside class="card studio-library"><div class="row"><div><strong>Bibliothèque de process</strong><div class="small muted">Réseau & magasins</div></div><button class="btn brand" id="studioNewTemplate">+ Nouveau</button></div><div class="studio-template-list">${templates.length?templates.map(templateCard).join(''):'<div class="empty">Aucun process personnalisé.</div>'}</div></aside>
  <section class="card studio-builder"><div class="row"><div><div class="label">PROCESS BUILDER</div><h3>${t?'Modifier le process':'Nouveau process'}</h3></div>${t?`<button class="btn ghost" id="studioToggleTemplate">${t.active?'Désactiver':'Réactiver'}</button>`:''}</div>
   <div class="grid g2 studio-form-grid"><label><span>Nom</span><input id="studioName" value="${esc(t?.template?.name||'')}" placeholder="Ex. Ouverture premium"></label><label><span>Code unique</span><input id="studioCode" value="${esc(t?.template?.code||'')}" placeholder="OPENING_PREMIUM"></label><label><span>Version</span><input id="studioVersion" value="${esc(t?.template?.version||'1')}"></label><label><span>Déclenchement</span><select id="studioTrigger"><option value="MANUAL">Manuel</option><option value="DAILY" ${(t?.template?.trigger||'')==='DAILY'?'selected':''}>Quotidien</option><option value="EVENT" ${(t?.template?.trigger||'')==='EVENT'?'selected':''}>Événement</option></select></label></div>
   <div class="studio-builder-head"><div><strong>Étapes</strong><div class="small muted">Ordre d’exécution, obligation et preuve.</div></div><button class="btn soft" id="studioAddStep">+ Ajouter une étape</button></div><div id="studioSteps">${draftSteps.map(stepEditor).join('')}</div>
   <div class="studio-savebar"><span class="small muted">Une modification ne change jamais un process déjà démarré : chaque journée conserve son snapshot.</span><button class="btn brand" id="studioSaveTemplate">${t?'Enregistrer les modifications':'Créer le process'}</button></div>
  </section>
 </div>
 <section class="card studio-assignments"><div class="row"><div><div class="label">AFFECTATIONS</div><h3>Où et quand ce process s’applique</h3></div></div>
  <div class="studio-assignment-form"><select id="assignTemplate"><option value="">Choisir un process…</option>${templates.filter(x=>x.active).map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('')}</select><select id="assignStore"><option value="">Tous les magasins</option>${app.stores.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('')}</select><select id="assignBlocking"><option value="PROCESS">Obligatoire dans le process</option><option value="STORE_OPENING">Bloque l’ouverture</option><option value="STORE_CLOSING">Bloque la fermeture</option><option value="NONE">Informatif</option></select><label class="studio-check"><input type="checkbox" id="assignMandatory" checked> Obligatoire</label><input id="assignFrom" type="date" title="Début"><input id="assignTo" type="date" title="Fin"><button class="btn brand" id="studioAssign">Affecter</button></div>
  <div class="table-wrap"><table class="table"><thead><tr><th>Process</th><th>Périmètre</th><th>Règle</th><th>Oblig.</th><th>Période</th><th>État</th><th></th></tr></thead><tbody>${assignments.length?assignments.map(assignmentRow).join(''):'<tr><td colspan="7"><div class="empty">Aucune affectation.</div></td></tr>'}</tbody></table></div>
 </section>
 <div class="grid g2 studio-next"><div class="card"><div class="label">PROCHAIN BLOC V1.80</div><strong>Règles de réappro</strong><p class="small muted">Lead time, stock sécurité, colisage et facteurs promo par réseau, magasin, catégorie ou article.</p></div><div class="card"><div class="label">PROCHAIN BLOC V1.80</div><strong>Utilisateurs & accès</strong><p class="small muted">Séparer clairement collaborateurs, comptes StoreOps, rôles, périmètres et droits d’administration.</p></div></div>`
}

function syncDraftFromDom(){document.querySelectorAll('[data-step-index]').forEach(row=>{const i=Number(row.dataset.stepIndex),s=draftSteps[i];row.querySelectorAll('[data-step-field]').forEach(el=>{const k=el.dataset.stepField;s[k]=el.type==='checkbox'?el.checked:el.value})})}
async function refresh(){await load();if(editingId&&!templates.some(x=>x.id===editingId))resetDraft();renderShell();bind()}
async function saveTemplate(){syncDraftFromDom();const name=$('#studioName').value.trim(),code=$('#studioCode').value.trim().toUpperCase().replace(/[^A-Z0-9_]+/g,'_'),version=$('#studioVersion').value.trim()||'1';const steps=draftSteps.map((s,i)=>({...s,code:(s.code||`step_${i+1}`).trim(),title:(s.title||'').trim(),order:i+1,blockingLevel:'PROCESS'}));if(!name||!code||steps.some(s=>!s.title))return toast('Nom, code et titre de chaque étape sont obligatoires.');const payload={code,name,version,trigger:$('#studioTrigger').value,scope:'STORE',steps,gates:[]};if(app.showcase)return toast('Aperçu seulement dans le Showcase.');const path=editingId?`/api/admin/process-templates/${encodeURIComponent(editingId)}`:'/api/admin/process-templates';await api(path,{method:editingId?'PUT':'POST',body:payload});toast(editingId?'Process mis à jour.':'Process créé.');editingId=null;draftSteps=[blankStep(0)];await refresh()}
function bind(){
 $('#studioNewTemplate').onclick=()=>{resetDraft();renderShell();bind()};
 document.querySelectorAll('[data-edit-template]').forEach(b=>b.onclick=()=>{setEdit(templates.find(x=>x.id===b.dataset.editTemplate));renderShell();bind()});
 $('#studioAddStep').onclick=()=>{syncDraftFromDom();draftSteps.push(blankStep(draftSteps.length));renderShell();bind()};
 document.querySelectorAll('[data-remove-step]').forEach(b=>b.onclick=()=>{syncDraftFromDom();draftSteps.splice(Number(b.dataset.removeStep),1);draftSteps.forEach((s,i)=>{if(/^step_\d+$/.test(s.code||''))s.code=`step_${i+1}`});renderShell();bind()});
 $('#studioSaveTemplate').onclick=()=>saveTemplate().catch(e=>toast(e.message));
 if($('#studioToggleTemplate'))$('#studioToggleTemplate').onclick=async()=>{if(app.showcase)return toast('Aperçu seulement dans le Showcase.');const t=currentTemplate();await api(`/api/admin/process-templates/${encodeURIComponent(t.id)}/active`,{method:'POST',body:{active:!t.active}});toast(t.active?'Process désactivé.':'Process réactivé.');await refresh()};
 $('#studioAssign').onclick=async()=>{const templateId=$('#assignTemplate').value;if(!templateId)return toast('Choisis un process.');if(app.showcase)return toast('Aperçu seulement dans le Showcase.');await api('/api/admin/process-assignments',{method:'POST',body:{templateId,storeId:$('#assignStore').value||null,blockingLevel:$('#assignBlocking').value,mandatory:$('#assignMandatory').checked,effectiveFrom:$('#assignFrom').value||null,effectiveTo:$('#assignTo').value||null,active:true}});toast('Process affecté.');await refresh()};
 document.querySelectorAll('[data-toggle-assignment]').forEach(b=>b.onclick=async()=>{const a=assignments.find(x=>x.id===b.dataset.toggleAssignment);if(app.showcase)return toast('Aperçu seulement dans le Showcase.');await api(`/api/admin/process-assignments/${encodeURIComponent(a.id)}`,{method:'PUT',body:{templateId:a.template_id,storeId:a.store_id||null,blockingLevel:a.blocking_level,mandatory:!!a.mandatory,effectiveFrom:a.effective_from||null,effectiveTo:a.effective_to||null,active:!a.active}});toast(a.active?'Affectation désactivée.':'Affectation activée.');await refresh()})
}

export async function renderAdminStudio(){if(!isDirector())return;try{if(!draftSteps.length)resetDraft();await refresh()}catch(e){$('#adminStudioContent').innerHTML=`<div class="banner ban-danger"><strong>Admin Studio indisponible</strong><span>${esc(e.message)}</span></div>`}}
