import {api} from '../api.js';
import {app,isDirector} from '../state.js';
import {$,esc,status,toast} from '../ui.js';

let templates=[],assignments=[],view='home',wizardStep=1,editingTemplateId=null,editingAssignmentId=null,moduleNonce=0;
let draft=blankDraft();

function blankDraft(){return{name:'',code:null,version:'1',moment:'OPENING',scope:'SOME',storeId:app.storeId||app.stores?.[0]?.id||'val-fleuri',frequency:'DAILY',steps:[{title:'',required:true,evidenceRequired:false}],blockingLevel:'STORE_OPENING',mandatory:true}}
function sampleData(){return{templates:[{id:'demo-open',active:true,code:'OPENING_PREMIUM',name:'Ouverture premium',version:'1',template:{code:'OPENING_PREMIUM',name:'Ouverture premium',version:'1',trigger:'DAILY',scope:'STORE',steps:[{code:'facade',title:'Façade & entrée impeccables',required:true,evidenceRequired:true,blockingLevel:'PROCESS'},{code:'fresh',title:'Contrôle Frais & Fruits/Légumes',required:true,evidenceRequired:false,blockingLevel:'PROCESS'}],gates:[]}}],assignments:[{id:'demo-a',template_id:'demo-open',template_name:'Ouverture premium',store_id:'val-fleuri',mandatory:true,blocking_level:'STORE_OPENING',active:true}]}}
async function load(){if(app.showcase){const s=sampleData();templates=s.templates;assignments=s.assignments;return}const [t,a]=await Promise.all([api('/api/admin/process-templates?all=1'),api('/api/admin/process-assignments?all=1')]);templates=t.items||[];assignments=a.items||[]}
function freshRoot(){const old=document.getElementById('adminStudioContent');if(!old)return null;const next=document.createElement('div');next.id='adminStudioContent';old.replaceWith(next);return next}
const root=()=>document.getElementById('adminStudioContent');
const scopeLabel=id=>id?(app.stores.find(s=>s.id===id)?.name||id):'Tous les magasins';
const blockLabel=x=>x==='STORE_OPENING'?'Bloque l’ouverture':x==='STORE_CLOSING'?'Bloque la fermeture':x==='NONE'?'Rappel seulement':'Obligatoire à terminer';
function slug(v){return String(v||'PROCESS').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]+/g,'_').replace(/^_+|_+$/g,'').slice(0,34)||'PROCESS'}
function newCode(name){return `CUSTOM_${slug(name)}_${Date.now().toString(36).slice(-4).toUpperCase()}`}
function stepCode(title,i){const s=slug(title).toLowerCase().slice(0,28);return s||`step_${i+1}`}

function homeCard(code,icon,title,detail,primary=false){return `<button class="ux-choice ${primary?'primary':''}" data-admin-area="${code}"><span class="ux-icon">${icon}</span><strong>${esc(title)}</strong><small>${esc(detail)}</small><em>Ouvrir →</em></button>`}
function renderHome(){
 const r=freshRoot();if(!r)return;const activeTemplates=templates.filter(x=>x.active).length;
 r.innerHTML=`<div class="ux-hero"><div><div class="ux-eyebrow">ADMIN</div><h2>Qu’est-ce que vous voulez changer ?</h2><p>StoreOps garde les paramètres techniques derrière. Choisissez le sujet, faites le changement, puis revenez ici.</p></div><button class="btn brand" id="adminQuickProcess">+ Nouveau process</button></div><div class="ux-mini-grid"><div class="ux-kpi"><span>Process actifs</span><strong>${activeTemplates}</strong></div><div class="ux-kpi"><span>Magasins</span><strong>${app.stores.length}</strong></div><div class="ux-kpi"><span>Accès</span><strong>Gérer</strong></div><div class="ux-kpi"><span>Connecteurs</span><strong>Voir</strong></div></div><div class="ux-grid">${homeCard('operations','✓','Opérations magasin','Process, règles de réappro et automatisations terrain',true)}${homeCard('network','⌂','Réseau & magasins','Magasins, entrepôts, D365 et assortiments')}${homeCard('people','◎','Utilisateurs & accès','Qui peut se connecter, rôles et périmètres')}${homeCard('system','⇄','Système & marque','Intégrations, santé des connecteurs et identité de marque')}</div>`;
 document.getElementById('adminQuickProcess').onclick=()=>startWizard();r.querySelectorAll('[data-admin-area]').forEach(b=>b.onclick=()=>renderArea(b.dataset.adminArea))
}
function renderArea(area){
 const r=freshRoot();if(!r)return;
 const defs={operations:{title:'Opérations magasin',detail:'Créez les règles sans exposer la mécanique technique.'},system:{title:'Système & marque',detail:'Connecteurs, identité et diagnostics dans un seul endroit.'}};
 if(area==='network')return loadAdminModule('../admin-studio-stores.js','Réseau & magasins','Entrepôt source, mapping D365 et assortiment magasin.');
 if(area==='people')return loadAdminModule('../admin-studio-access.js','Utilisateurs & accès','Un compte Microsoft, un rôle clair, un périmètre clair.');
 const d=defs[area]||defs.operations;
 r.innerHTML=`<button class="ux-back" data-admin-home>← Admin</button><div class="ux-hero"><div><div class="ux-eyebrow">ADMIN</div><h2>${esc(d.title)}</h2><p>${esc(d.detail)}</p></div></div><div class="ux-grid">${area==='operations'?`${homeCard('processes','✓','Process magasin','Créer, publier et modifier les parcours terrain',true)}${homeCard('replenishment','↗','Règles de réappro','Couverture, sécurité, lead time et colisage')}`:`${homeCard('integrations','⇄','Intégrations','ERP, POS, WMS, PIM, RH et disponibilité des capacités',true)}${homeCard('tenant','✦','Marque & vocabulaire','Nom, couleurs, mots métier et modules du tenant')}${homeCard('diagnostics','◉','Diagnostics','Santé technique et mapping Dynamics')}`}</div>`;
 r.querySelector('[data-admin-home]').onclick=()=>{view='home';renderHome()};r.querySelectorAll('[data-admin-area]').forEach(b=>b.onclick=()=>{const code=b.dataset.adminArea;if(code==='processes'){view='library';renderLibrary()}else if(code==='replenishment')loadAdminModule('../admin-studio-replenishment.js','Règles de réappro','La règle la plus précise gagne, les paramètres avancés restent à la demande.');else if(code==='integrations')loadAdminModule('../admin-studio-integrations.js','Intégrations','Voir seulement ce qui est connecté, dégradé ou à mapper.');else if(code==='tenant')loadAdminModule('../admin-studio-tenant.js','Marque & vocabulaire','Personnaliser StoreOps sans fork du produit.');else if(code==='diagnostics')document.querySelector('[data-page="system"]')?.click()})
}
async function loadAdminModule(path,title,detail){
 const r=freshRoot();if(!r)return;r.innerHTML=`<button class="ux-back" data-admin-home>← Admin</button><div class="studio-hero"><div><div class="ux-eyebrow">ADMIN</div><h2>${esc(title)}</h2><p>${esc(detail)}</p></div></div><div class="ux-loading" id="adminLazyLoading">Chargement…</div>`;r.querySelector('[data-admin-home]').onclick=()=>{view='home';renderHome()};
 try{await import(`${path}?v=1850-${++moduleNonce}`);document.getElementById('adminLazyLoading')?.remove()}catch(e){document.getElementById('adminLazyLoading').innerHTML=`<strong>Impossible de charger ce réglage.</strong><div class="small muted">${esc(e.message)}</div>`}
}

function startWizard(template=null){editingTemplateId=template?.id||null;editingAssignmentId=null;wizardStep=1;if(template){const a=assignments.find(x=>x.template_id===template.id&&x.active)||assignments.find(x=>x.template_id===template.id)||null;editingAssignmentId=a?.id||null;const level=a?.blocking_level||'PROCESS',moment=level==='STORE_OPENING'?'OPENING':level==='STORE_CLOSING'?'CLOSING':template.template?.trigger==='EVENT'?'EVENT':'DAY';draft={name:template.name,code:template.code,version:template.version||'1',moment,scope:a?.store_id?'SOME':'ALL',storeId:a?.store_id||app.storeId||app.stores[0]?.id||null,frequency:template.template?.trigger||'DAILY',steps:(template.template?.steps||[]).map(s=>({title:s.title,required:s.required!==false,evidenceRequired:!!s.evidenceRequired})),blockingLevel:level,mandatory:a?a.mandatory!==false:true};if(!draft.steps.length)draft.steps=[{title:'',required:true,evidenceRequired:false}]}else draft=blankDraft();view='wizard';renderWizard()}
function captureWizard(){if(wizardStep===1)draft.name=$('#wizardName')?.value?.trim()||draft.name;if(wizardStep===2){draft.storeId=$('#wizardStore')?.value||draft.storeId;draft.frequency=$('#wizardFrequency')?.value||draft.frequency}if(wizardStep===3)document.querySelectorAll('[data-wizard-step]').forEach(row=>{const i=Number(row.dataset.wizardStep);if(!draft.steps[i])return;draft.steps[i].title=row.querySelector('[data-step-title]')?.value?.trim()||'';draft.steps[i].required=!!row.querySelector('[data-step-required]')?.checked;draft.steps[i].evidenceRequired=!!row.querySelector('[data-step-evidence]')?.checked})}
function validateStep(n){if(n===1&&!draft.name.trim())return'Indique le nom du process.';if(n===2&&draft.scope==='SOME'&&!draft.storeId)return'Choisis le magasin concerné.';if(n===3&&(draft.steps.length<1||draft.steps.some(s=>!s.title.trim())))return'Donne un titre clair à chaque étape.';return null}
function goWizard(n){captureWizard();const err=n>wizardStep?validateStep(wizardStep):null;if(err)return toast(err);wizardStep=Math.max(1,Math.min(5,n));renderWizard()}
function momentLabel(){return({OPENING:'Avant l’ouverture',DAY:'Pendant la journée',CLOSING:'À la fermeture',EVENT:'Lors d’un événement'})[draft.moment]||draft.moment}
function ruleDescription(){return({NONE:'StoreOps rappelle l’action mais ne bloque pas le magasin.',PROCESS:'Le process doit être terminé et reste visible comme obligation.',STORE_OPENING:'Le magasin ne peut pas être déclaré ouvert tant que ce process n’est pas terminé.',STORE_CLOSING:'Le magasin ne peut pas être déclaré fermé tant que ce process n’est pas terminé.'})[draft.blockingLevel]}
function wizardRail(){return `<aside class="studio-wizard-rail">${[['Objectif','Besoin'],['Périmètre','Où & quand'],['Étapes','Terrain'],['Règle','Blocage'],['Aperçu','RM']].map((x,i)=>`<div class="studio-wizard-rail-step ${i+1===wizardStep?'active':''} ${i+1<wizardStep?'done':''}"><b>${i+1}. ${x[0]}</b><span>${x[1]}</span></div>`).join('')}</aside>`}
function navButtons({publish=false}={}){return `<div class="studio-wizard-actions"><button class="btn ghost" data-wizard-back>${wizardStep===1?'Annuler':'Retour'}</button>${publish?'<button class="btn brand" data-wizard-publish>Publier</button>':'<button class="btn brand" data-wizard-next>Continuer</button>'}</div>`}
function renderWizard(){
 const r=freshRoot();if(!r)return;let body='';
 if(wizardStep===1)body=`<div class="label">1 SUR 5</div><h2>Qu’est-ce que le magasin doit faire ?</h2><p class="muted">Une phrase simple, compréhensible sans formation.</p><label class="studio-guided-field"><span>Nom</span><input id="wizardName" value="${esc(draft.name)}" placeholder="Ex. Contrôle ouverture premium"></label><div class="studio-guided-label">À quel moment ?</div><div class="studio-choice-grid">${[['OPENING','Avant l’ouverture'],['DAY','Pendant la journée'],['CLOSING','À la fermeture'],['EVENT','Lors d’un événement']].map(([k,t])=>`<button class="studio-choice ${draft.moment===k?'selected':''}" data-moment="${k}"><strong>${t}</strong></button>`).join('')}</div>${navButtons()}`;
 if(wizardStep===2)body=`<div class="label">2 SUR 5</div><h2>Où et quand ?</h2><div class="studio-choice-grid"><button class="studio-choice ${draft.scope==='ALL'?'selected':''}" data-scope="ALL"><strong>Tous les magasins</strong></button><button class="studio-choice ${draft.scope==='SOME'?'selected':''}" data-scope="SOME"><strong>Un magasin</strong></button></div>${draft.scope==='SOME'?`<label class="studio-guided-field"><span>Magasin</span><select id="wizardStore">${app.stores.map(s=>`<option value="${esc(s.id)}" ${draft.storeId===s.id?'selected':''}>${esc(s.name)}</option>`).join('')}</select></label>`:''}<label class="studio-guided-field"><span>Fréquence</span><select id="wizardFrequency"><option value="DAILY" ${draft.frequency==='DAILY'?'selected':''}>Tous les jours</option><option value="EVENT" ${draft.frequency==='EVENT'?'selected':''}>À l’événement</option><option value="MANUAL" ${draft.frequency==='MANUAL'?'selected':''}>À la demande</option></select></label>${navButtons()}`;
 if(wizardStep===3)body=`<div class="label">3 SUR 5</div><h2>Que fait le magasin ?</h2><div class="studio-guided-steps">${draft.steps.map((s,i)=>`<div class="studio-guided-step" data-wizard-step="${i}"><div class="studio-step-number">${i+1}</div><div><input data-step-title value="${esc(s.title)}" placeholder="Ex. Vérifier la façade"><div class="studio-inline-options"><label><input type="checkbox" data-step-required ${s.required!==false?'checked':''}> Obligatoire</label><label><input type="checkbox" data-step-evidence ${s.evidenceRequired?'checked':''}> Preuve</label>${draft.steps.length>1?`<button class="btn ghost" data-remove-wizard-step="${i}">Supprimer</button>`:''}</div></div></div>`).join('')}</div><button class="btn soft" id="wizardAddStep">+ Ajouter une étape</button>${navButtons()}`;
 if(wizardStep===4)body=`<div class="label">4 SUR 5</div><h2>Si ce n’est pas fait ?</h2><div class="studio-choice-grid">${[['NONE','Rappeler seulement'],['PROCESS','Obligatoire'],['STORE_OPENING','Bloquer l’ouverture'],['STORE_CLOSING','Bloquer la fermeture']].map(([k,t])=>`<button class="studio-choice ${draft.blockingLevel===k?'selected':''}" data-blocking="${k}"><strong>${t}</strong></button>`).join('')}</div><div class="studio-rule-summary"><strong>${esc(blockLabel(draft.blockingLevel))}</strong><span>${esc(ruleDescription())}</span></div>${navButtons()}`;
 if(wizardStep===5){const first=draft.steps[0]||{title:'Étape'};body=`<div class="label">5 SUR 5</div><h2>Aperçu Responsable magasin</h2><div class="studio-preview-phone"><div class="studio-preview-meta">${esc(draft.scope==='ALL'?'Tous magasins':scopeLabel(draft.storeId))} · ${esc(momentLabel())}</div><div class="studio-preview-card"><div class="label">${esc(momentLabel().toUpperCase())} · 1 SUR ${draft.steps.length}</div><div class="studio-preview-progress"><span style="width:${Math.max(8,100/draft.steps.length)}%"></span></div><h3>${esc(first.title||'Première étape')}</h3>${first.evidenceRequired?'<div class="studio-preview-proof">📷 Preuve obligatoire</div>':''}<button class="btn brand">Valider et continuer</button></div></div><div class="studio-publish-summary"><div><span>Périmètre</span><strong>${esc(draft.scope==='ALL'?'Tous les magasins':scopeLabel(draft.storeId))}</strong></div><div><span>Règle</span><strong>${esc(blockLabel(draft.blockingLevel))}</strong></div><div><span>Étapes</span><strong>${draft.steps.length}</strong></div></div>${navButtons({publish:true})}`}
 r.innerHTML=`<div class="studio-guided-shell"><div class="studio-guided-top"><button class="ux-back" id="wizardExit">← Admin</button><span class="pill">${editingTemplateId?'Modifier':'Nouveau process'}</span></div><div class="studio-wizard-layout">${wizardRail()}<section class="studio-wizard-card">${body}</section></div></div>`;bindWizard()
}
function bindWizard(){document.getElementById('wizardExit')?.addEventListener('click',()=>{view='home';renderHome()});document.querySelector('[data-wizard-back]')?.addEventListener('click',()=>wizardStep===1?(view='home',renderHome()):goWizard(wizardStep-1));document.querySelector('[data-wizard-next]')?.addEventListener('click',()=>goWizard(wizardStep+1));document.querySelectorAll('[data-moment]').forEach(b=>b.onclick=()=>{captureWizard();draft.moment=b.dataset.moment;if(draft.moment==='OPENING')draft.blockingLevel='STORE_OPENING';else if(draft.moment==='CLOSING')draft.blockingLevel='STORE_CLOSING';else if(['STORE_OPENING','STORE_CLOSING'].includes(draft.blockingLevel))draft.blockingLevel='PROCESS';renderWizard()});document.querySelectorAll('[data-scope]').forEach(b=>b.onclick=()=>{captureWizard();draft.scope=b.dataset.scope;renderWizard()});document.querySelectorAll('[data-blocking]').forEach(b=>b.onclick=()=>{draft.blockingLevel=b.dataset.blocking;draft.mandatory=draft.blockingLevel!=='NONE';renderWizard()});document.getElementById('wizardAddStep')?.addEventListener('click',()=>{captureWizard();draft.steps.push({title:'',required:true,evidenceRequired:false});renderWizard()});document.querySelectorAll('[data-remove-wizard-step]').forEach(b=>b.onclick=()=>{captureWizard();draft.steps.splice(Number(b.dataset.removeWizardStep),1);renderWizard()});document.querySelector('[data-wizard-publish]')?.addEventListener('click',()=>publishWizard().catch(e=>toast(e.message)))}
async function publishWizard(){captureWizard();for(const n of [1,2,3]){const e=validateStep(n);if(e)return toast(e)}if(app.showcase)return toast('Aperçu Showcase : publication désactivée.');const code=draft.code||newCode(draft.name),steps=draft.steps.map((s,i)=>({code:stepCode(s.title,i),title:s.title.trim(),order:i+1,required:s.required!==false,evidenceRequired:!!s.evidenceRequired,blockingLevel:'PROCESS'})),payload={code,name:draft.name.trim(),version:draft.version||'1',trigger:draft.frequency,scope:'STORE',steps,gates:[]};const saved=await api(editingTemplateId?`/api/admin/process-templates/${encodeURIComponent(editingTemplateId)}`:'/api/admin/process-templates',{method:editingTemplateId?'PUT':'POST',body:payload});const assignmentBody={templateId:saved.id,storeId:draft.scope==='ALL'?null:draft.storeId,blockingLevel:draft.blockingLevel,mandatory:draft.blockingLevel==='NONE'?false:draft.mandatory,effectiveFrom:null,effectiveTo:null,active:true};await api(editingAssignmentId?`/api/admin/process-assignments/${encodeURIComponent(editingAssignmentId)}`:'/api/admin/process-assignments',{method:editingAssignmentId?'PUT':'POST',body:assignmentBody});toast(editingTemplateId?'Process mis à jour.':'Process publié.');await load();editingTemplateId=null;editingAssignmentId=null;view='library';renderLibrary()}
function renderLibrary(){const r=freshRoot();if(!r)return;r.innerHTML=`<button class="ux-back" id="libraryBack">← Opérations magasin</button><div class="ux-hero"><div><div class="ux-eyebrow">PROCESS</div><h2>Process magasin</h2><p>${templates.length} process configuré(s). La technique reste cachée, le terrain ne voit que les étapes utiles.</p></div><button class="btn brand" id="libraryNew">+ Nouveau</button></div><div class="ux-command-list" style="margin-top:14px">${templates.length?templates.map(t=>{const a=assignments.find(x=>x.template_id===t.id&&x.active)||assignments.find(x=>x.template_id===t.id),count=t.template?.steps?.length||0;return `<div class="ux-command"><span><strong>${esc(t.name)}</strong><small>${esc(a?scopeLabel(a.store_id):'Non affecté')} · ${esc(a?blockLabel(a.blocking_level):'Aucune règle')} · ${count} étape(s)</small></span><div><button class="btn soft" data-edit-process="${esc(t.id)}">Modifier</button> ${status(t.active?'Actif':'Inactif',t.active?'ok':'neutral')}</div></div>`}).join(''):'<div class="ux-loading">Aucun process publié.</div>'}</div>`;document.getElementById('libraryBack').onclick=()=>renderArea('operations');document.getElementById('libraryNew').onclick=()=>startWizard();r.querySelectorAll('[data-edit-process]').forEach(b=>b.onclick=()=>startWizard(templates.find(x=>x.id===b.dataset.editProcess)))}
export async function renderAdminStudio(){if(!isDirector())return;try{await load();if(view==='wizard')renderWizard();else if(view==='library')renderLibrary();else renderHome()}catch(e){const r=freshRoot();if(r)r.innerHTML=`<div class="banner ban-danger"><strong>Admin Studio indisponible</strong><span>${esc(e.message)}</span></div>`}}
