import {api} from '../api.js';
import {esc,status,toast} from '../ui.js';

let config=null,projects=[],filter='ALL';
const stageLabel=code=>config?.stages?.find(x=>x.code===code)?.label||code;
const money=v=>v===null||v===undefined||v===''?'—':`${Number(v).toLocaleString('fr-FR',{maximumFractionDigits:0})} DH`;
const date=v=>v?new Date(`${String(v).slice(0,10)}T12:00:00`).toLocaleDateString('fr-FR'):'—';
const decisionLabel=v=>({PENDING:'À décider',GO:'GO',HOLD:'HOLD',NO_GO:'NO GO'})[v]||v||'À décider';
const priorityLabel=v=>({LOW:'Basse',NORMAL:'Normale',HIGH:'Haute',CRITICAL:'Critique'})[v]||v||'Normale';
const riskTone=p=>p?.risk?.severity==='danger'?'danger':p?.risk?.severity==='warn'?'warn':'ok';
const decisionTone=v=>v==='GO'?'ok':v==='NO_GO'?'danger':v==='HOLD'?'warn':'neutral';
const attention=p=>['BLOCKED','ACTION_LATE','OPENING_LATE','OPENING_SOON'].includes(p.risk?.code);
const root=()=>document.getElementById('developmentContent');

async function load(){const [c,p]=await Promise.all([api('/api/development/config'),api('/api/development/projects')]);config=c;projects=p.items||[]}
async function reloadProject(id){await load();return api(`/api/development/projects/${encodeURIComponent(id)}`)}
function filtered(){if(filter==='ALL')return projects;if(filter==='ATTENTION')return projects.filter(attention);return projects.filter(x=>x.stage===filter)}
function stageIndex(code){return Math.max(0,(config?.stages||[]).findIndex(x=>x.code===code))}
function nextStage(p){return (config?.stages||[])[stageIndex(p.stage)+1]||null}
function projectCard(p){return `<button class="ux191-project" data-dev-project="${esc(p.id)}"><div class="row" style="align-items:flex-start"><div><div class="label">${esc(stageLabel(p.stage).toUpperCase())}</div><h3>${esc(p.name)}</h3><p>${esc([p.city,p.zone||p.address].filter(Boolean).join(' · '))}</p></div><div style="display:grid;gap:6px;justify-items:end">${status(p.risk?.label||'Sous contrôle',riskTone(p))}${status(decisionLabel(p.decision),decisionTone(p.decision))}</div></div><div class="ux191-meta"><div><span>Ouverture cible</span><strong>${date(p.target_opening_date)}</strong></div><div><span>Responsable</span><strong>${esc(p.owner_name||'À affecter')}</strong></div><div><span>Prochaine action</span><strong>${esc(p.next_action||'À définir')}</strong></div><div><span>${p.stage==='WORKS'?'Travaux':'CAPEX'}</span><strong>${p.stage==='WORKS'?`${Number(p.works_progress||0)}%`:money(p.capex_budget)}</strong></div></div>${p.blocker?`<div class="ux191-risk"><strong>Blocage</strong><div class="small">${esc(p.blocker)}</div></div>`:''}<div class="ux191-progress"><i style="width:${Number(p.progress||0)}%"></i></div></button>`}
function renderBoard(){const r=root();if(!r)return;const active=projects.filter(x=>x.status==='ACTIVE'),soon=projects.filter(x=>x.daysToOpening!==null&&x.daysToOpening>=0&&x.daysToOpening<=90&&x.stage!=='OPEN'),rows=filtered();r.innerHTML=`<div class="ux191-shell"><div class="ux191-hero"><div><div class="ux191-eyebrow">DÉVELOPPEMENT RÉSEAU</div><h2>De l’opportunité au magasin ouvert.</h2><p>Sourcing, décision GO, contrat, CAPEX, travaux et pré-ouverture dans un seul parcours pilotable.</p></div><button class="btn brand" id="devNew">+ Nouveau projet</button></div><div class="ux191-kpis"><div class="ux191-kpi"><span>Projets actifs</span><strong>${active.length}</strong></div><div class="ux191-kpi"><span>En sourcing</span><strong>${active.filter(x=>x.stage==='SOURCING').length}</strong></div><div class="ux191-kpi"><span>En travaux</span><strong>${active.filter(x=>x.stage==='WORKS').length}</strong></div><div class="ux191-kpi"><span>À surveiller</span><strong>${projects.filter(attention).length}</strong></div><div class="ux191-kpi"><span>Ouverture ≤ 90 j</span><strong>${soon.length}</strong></div></div><div class="ux191-filters"><button class="ux191-chip ${filter==='ALL'?'active':''}" data-dev-filter="ALL">Tous</button><button class="ux191-chip ${filter==='ATTENTION'?'active':''}" data-dev-filter="ATTENTION">À surveiller</button>${(config?.stages||[]).map(s=>`<button class="ux191-chip ${filter===s.code?'active':''}" data-dev-filter="${esc(s.code)}">${esc(s.label)}</button>`).join('')}</div><div class="ux191-board">${rows.length?rows.map(projectCard).join(''):'<div class="ux191-empty">Aucun projet dans ce périmètre.</div>'}</div></div>`;document.getElementById('devNew')?.addEventListener('click',renderCreate);r.querySelectorAll('[data-dev-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.devFilter;renderBoard()});r.querySelectorAll('[data-dev-project]').forEach(b=>b.onclick=()=>openProject(b.dataset.devProject).catch(e=>toast(e.message)))}

function renderCreate(){const r=root();if(!r)return;r.innerHTML=`<div class="ux191-shell"><button class="ux191-back" id="devBack">← Développement</button><div class="ux191-hero"><div><div class="ux191-eyebrow">NOUVELLE OPPORTUNITÉ</div><h2>Qualifier un local.</h2><p>Commencez avec les informations utiles à la décision. Le dossier pourra être enrichi à chaque étape.</p></div></div><div class="ux191-card" style="margin-top:14px"><div class="grid g2"><label><span>Nom du projet *</span><input id="devName" placeholder="Ex. Franprix Racine"></label><label><span>Ville *</span><input id="devCity" value="Casablanca"></label><label><span>Quartier / zone</span><input id="devZone"></label><label><span>Adresse / local</span><input id="devAddress"></label><label><span>Surface m²</span><input id="devSurface" type="number" min="0"></label><label><span>Source du lead</span><input id="devLead" placeholder="Agent, propriétaire, prospection…"></label><label><span>Loyer mensuel</span><input id="devRent" type="number" min="0"></label><label><span>Budget CAPEX</span><input id="devCapex" type="number" min="0"></label><label><span>Date cible d’ouverture</span><input id="devTarget" type="date"></label><label><span>Responsable projet</span><select id="devOwner"><option value="">Non affecté</option>${(config?.users||[]).map(u=>`<option value="${esc(u.id)}">${esc(u.name)}</option>`).join('')}</select></label></div><label><span>Prochaine action</span><input id="devNextAction" placeholder="Ex. Programmer la visite technique"></label><div class="studio-savebar"><span class="small muted">Le projet démarre en Sourcing local avec décision À décider.</span><button class="btn brand" id="devCreate">Créer le projet</button></div></div></div>`;document.getElementById('devBack').onclick=renderBoard;document.getElementById('devCreate').onclick=async()=>{const body={name:document.getElementById('devName').value.trim(),city:document.getElementById('devCity').value.trim(),zone:document.getElementById('devZone').value.trim(),address:document.getElementById('devAddress').value.trim(),surfaceM2:document.getElementById('devSurface').value||null,sourceLead:document.getElementById('devLead').value.trim(),monthlyRent:document.getElementById('devRent').value||null,capexBudget:document.getElementById('devCapex').value||null,targetOpeningDate:document.getElementById('devTarget').value||null,ownerUserId:document.getElementById('devOwner').value||null,nextAction:document.getElementById('devNextAction').value.trim()};if(!body.name||!body.city)return toast('Nom du projet et ville obligatoires.');try{const created=await api('/api/development/projects',{method:'POST',body});await load();await openProject(created.id);toast('Projet développement créé.')}catch(e){toast(e.message)}}}

function stageRail(p){const current=stageIndex(p.stage);return `<div class="dev-stage-rail">${(config?.stages||[]).map((s,i)=>`<div class="dev-stage-node ${i<current?'done':i===current?'active':''}"><span>${i<current?'✓':i+1}</span><small>${esc(s.label)}</small></div>`).join('')}</div>`}
function decisionControls(p){return `<div class="dev-decision-row"><span>Décision projet</span><div>${['GO','HOLD','NO_GO'].map(v=>`<button class="btn ${p.decision===v?'brand':'soft'}" data-dev-decision="${v}">${v==='NO_GO'?'NO GO':v}</button>`).join('')}</div></div>`}
function milestoneRows(p){return (p.milestones||[]).map(m=>`<div class="ux191-mile ${m.status==='DONE'?'done':''}"><span><strong>${esc(m.label)}</strong><small>${esc(stageLabel(m.stage))}${m.due_date?` · cible ${date(m.due_date)}`:''}</small></span>${m.status==='DONE'?status('Fait','ok'):`<button class="btn soft" data-dev-milestone="${esc(m.code)}">Valider</button>`}</div>`).join('')}
function detailForm(p){return `<div class="grid g2"><label><span>Responsable</span><select id="devOwner"><option value="">Non affecté</option>${(config?.users||[]).map(u=>`<option value="${esc(u.id)}" ${p.owner_user_id===u.id?'selected':''}>${esc(u.name)}</option>`).join('')}</select></label><label><span>Priorité</span><select id="devPriority">${(config?.priorities||['LOW','NORMAL','HIGH','CRITICAL']).map(v=>`<option value="${v}" ${p.priority===v?'selected':''}>${priorityLabel(v)}</option>`).join('')}</select></label><label><span>Ouverture cible</span><input id="devTarget" type="date" value="${esc(p.target_opening_date||'')}"></label><label><span>Prochaine action</span><input id="devNextAction" value="${esc(p.next_action||'')}"></label><label><span>Échéance prochaine action</span><input id="devNextDue" type="date" value="${esc(p.next_action_due_date||'')}"></label><label><span>Blocage actif</span><input id="devBlocker" value="${esc(p.blocker||'')}" placeholder="Vide = aucun blocage"></label><label><span>Loyer mensuel</span><input id="devRent" type="number" min="0" value="${p.monthly_rent??''}"></label><label><span>CAPEX budget</span><input id="devCapexBudget" type="number" min="0" value="${p.capex_budget??''}"></label><label><span>CAPEX engagé</span><input id="devCapexCommitted" type="number" min="0" value="${p.capex_committed??''}"></label><label><span>CAPEX réel</span><input id="devCapexActual" type="number" min="0" value="${p.capex_actual??''}"></label><label><span>Score emplacement /100</span><input id="devSiteScore" type="number" min="0" max="100" value="${p.site_score??''}"></label><label><span>Score économique /100</span><input id="devEconomicScore" type="number" min="0" max="100" value="${p.economic_score??''}"></label><label><span>Avancement travaux %</span><input id="devWorksProgress" type="number" min="0" max="100" value="${Number(p.works_progress||0)}"></label></div><div class="studio-savebar"><span class="small muted">Ces informations alimentent automatiquement les alertes Développement.</span><button class="btn brand" id="devSave">Enregistrer le projet</button></div>`}
async function openProject(id){const r=root();if(!r)return;r.innerHTML='<div class="ux191-shell"><div class="ux191-empty">Chargement du projet…</div></div>';const p=await api(`/api/development/projects/${encodeURIComponent(id)}`);renderDetail(p)}
function renderDetail(p){const r=root();if(!r)return;const next=nextStage(p);r.innerHTML=`<div class="ux191-shell"><button class="ux191-back" id="devBack">← Développement</button><div class="ux191-hero"><div><div class="ux191-eyebrow">${esc(stageLabel(p.stage))}</div><h2>${esc(p.name)}</h2><p>${esc([p.city,p.zone||p.address].filter(Boolean).join(' · '))}</p><div style="display:flex;gap:7px;flex-wrap:wrap;margin-top:10px">${status(decisionLabel(p.decision),decisionTone(p.decision))}${status(p.risk?.label||'Sous contrôle',riskTone(p))}${status(`Priorité ${priorityLabel(p.priority)}`,p.priority==='CRITICAL'?'danger':p.priority==='HIGH'?'warn':'neutral')}</div></div>${next?`<button class="btn brand" id="devAdvance" ${p.stageReadiness?.ready===false?'disabled':''}>Passer à ${esc(next.label)} →</button>`:''}</div>${stageRail(p)}${next&&p.stageReadiness?.ready===false?`<div class="banner ban-warn" style="margin-top:12px"><strong>${Number(p.stageReadiness.count||0)} prérequis restent à terminer</strong><span>${(p.stageReadiness.incomplete||[]).slice(0,5).map(x=>esc(x.label)).join(' · ')}</span></div>`:''}${decisionControls(p)}<div class="ux191-detail"><div class="ux191-card"><h3>Jalons & gates</h3>${milestoneRows(p)}</div><div><div class="ux191-card"><h3>Business case & pilotage</h3><div class="ux191-facts"><div><span>Surface</span><strong>${p.surface_m2??'—'} m²</strong></div><div><span>Loyer</span><strong>${money(p.monthly_rent)}</strong></div><div><span>CAPEX budget</span><strong>${money(p.capex_budget)}</strong></div><div><span>CAPEX engagé</span><strong>${money(p.capex_committed)}</strong></div><div><span>CAPEX réel</span><strong>${money(p.capex_actual)}</strong></div><div><span>Travaux</span><strong>${Number(p.works_progress||0)}%</strong></div><div><span>Score emplacement</span><strong>${p.site_score??'—'}/100</strong></div><div><span>Score économique</span><strong>${p.economic_score??'—'}/100</strong></div></div></div><div class="ux191-card" style="margin-top:12px"><h3>Pilotage du projet</h3>${detailForm(p)}</div>${p.history?.length?`<details class="dev-history" style="margin-top:12px"><summary>Historique du projet</summary>${p.history.map(h=>`<div><strong>${esc(String(h.event_type||'').replaceAll('_',' '))}</strong><span>${esc(h.detail||'')} · ${esc(h.user_name||'Système')} · ${new Date(h.created_at).toLocaleString('fr-FR')}</span></div>`).join('')}</details>`:''}</div></div></div>`;bindDetail(p,next)}
function bindDetail(p,next){document.getElementById('devBack').onclick=async()=>{await load();renderBoard()};document.querySelectorAll('[data-dev-decision]').forEach(b=>b.onclick=async()=>{try{const updated=await api(`/api/development/projects/${encodeURIComponent(p.id)}`,{method:'PATCH',body:{decision:b.dataset.devDecision}});renderDetail(updated);toast(`Décision ${decisionLabel(updated.decision)} enregistrée.`)}catch(e){toast(e.message)}});document.querySelectorAll('[data-dev-milestone]').forEach(b=>b.onclick=async()=>{try{const updated=await api(`/api/development/projects/${encodeURIComponent(p.id)}/milestones/${encodeURIComponent(b.dataset.devMilestone)}`,{method:'POST',body:{status:'DONE'}});renderDetail(updated);toast('Jalon validé.')}catch(e){toast(e.message)}});document.getElementById('devAdvance')?.addEventListener('click',async()=>{if(!next)return;try{const updated=await api(`/api/development/projects/${encodeURIComponent(p.id)}/stage`,{method:'POST',body:{stage:next.code}});renderDetail(updated);toast(`Projet passé à ${next.label}.`)}catch(e){toast(e.message)}});document.getElementById('devSave')?.addEventListener('click',async()=>{const body={ownerUserId:document.getElementById('devOwner').value||null,priority:document.getElementById('devPriority').value,targetOpeningDate:document.getElementById('devTarget').value||null,nextAction:document.getElementById('devNextAction').value.trim(),nextActionDueDate:document.getElementById('devNextDue').value||null,blocker:document.getElementById('devBlocker').value.trim(),monthlyRent:document.getElementById('devRent').value||null,capexBudget:document.getElementById('devCapexBudget').value||null,capexCommitted:document.getElementById('devCapexCommitted').value||null,capexActual:document.getElementById('devCapexActual').value||null,siteScore:document.getElementById('devSiteScore').value||null,economicScore:document.getElementById('devEconomicScore').value||null,worksProgress:document.getElementById('devWorksProgress').value||0};try{const updated=await api(`/api/development/projects/${encodeURIComponent(p.id)}`,{method:'PATCH',body});renderDetail(updated);toast('Projet enregistré.')}catch(e){toast(e.message)}})}

export async function renderDevelopment(){const r=root();if(!r)return;r.innerHTML='<div class="ux191-shell"><div class="ux191-empty">Chargement du portefeuille Développement…</div></div>';try{await load();renderBoard()}catch(e){r.innerHTML=`<div class="banner ban-danger"><strong>Développement indisponible</strong><span>${esc(e.message)}</span></div>`}}
