import{api}from'../api.js';
import{app,canManage}from'../state.js';
import{$,status,esc,toast}from'../ui.js';

const categoryLabel=x=>({OPERATIONS:'Exploitation',STAFFING:'Équipe',SECURITY:'Sécurité',COLD:'Froid',TECHNICAL:'Technique',STOCK:'Stock',CASH:'Caisses',QUALITY:'Qualité',COMMERCIAL:'Prix & promos'}[x]||x||'Exploitation');
const priorityKind=x=>x==='CRITICAL'?'danger':x==='HIGH'?'warn':'neutral';
const statusLabel=x=>({OPEN:'À prendre en compte',ACKNOWLEDGED:'Pris en compte',RESOLVED:'Résolu',CANCELLED:'Annulé'}[x]||x);
const dt=v=>v?new Date(String(v).replace(' ','T')+(String(v).includes('Z')?'':'Z')).toLocaleString('fr-FR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'—';
const tomorrow=()=>{const d=new Date();d.setDate(d.getDate()+1);return d.toISOString().slice(0,10)};
let busy=false;

export async function renderHandover(){
 const [data,dash]=await Promise.all([api(`/api/stores/${app.storeId}/handover?status=ALL`),api(`/api/stores/${app.storeId}/dashboard`)]),s=data.stats||{},all=data.items||[],active=all.filter(x=>['OPEN','ACKNOWLEDGED'].includes(x.status)),history=all.filter(x=>!['OPEN','ACKNOWLEDGED'].includes(x.status)).slice(0,12),ro=!canManage(),reviewed=!!dash.cycle?.handoverReviewed;
 $('#handoverContent').innerHTML=`
 ${ro?'<div class="role-lock">Lecture seule : création, prise en compte et résolution réservées au Responsable magasin et au Directeur d’Exploitation.</div>':''}
 <div class="grid g4 handover-kpis" style="margin-top:14px">
  ${kpi('À traiter',s.pending||0,'passation(s) active(s)',s.pending?'warn':'')}
  ${kpi('Bloquantes ouverture',s.blocking||0,'à résoudre avant ouverture',s.blocking?'danger':'')}
  ${kpi('Non accusées',s.unacknowledged||0,'à prendre en compte',s.unacknowledged?'warn':'')}
  ${kpi('En retard',s.overdue||0,'date cible dépassée',s.overdue?'danger':'')}
 </div>
 ${!ro?createCard():''}
 <div class="card handover-review" style="margin-top:14px"><div class="row"><div><strong>Revue de passation de fin de journée</strong><div class="small muted">La fermeture magasin reste bloquée tant que la passation n’a pas été revue.</div></div>${status(reviewed?'Revue effectuée':'À revoir',reviewed?'ok':'warn')}</div>${!ro&&!reviewed?'<button class="btn brand" id="reviewHandoverClosing" style="margin-top:12px">Confirmer la revue de passation</button>':reviewed?'<div class="banner ban-info" style="margin-top:10px">Passation de fin de journée revue pour la journée en cours.</div>':''}</div>
 <div class="network-section-title"><div><strong>Passations actives</strong><span>Du sujet transmis jusqu’à sa résolution documentée.</span></div><span class="pill">${active.length}</span></div>
 <div class="handover-list">${active.length?active.map(x=>itemCard(x,ro)).join(''):'<div class="card empty">Aucune passation active.</div>'}</div>
 ${history.length?`<div class="network-section-title"><div><strong>Historique récent</strong><span>Passations clôturées ou annulées.</span></div></div><div class="handover-history">${history.map(x=>itemCard(x,true)).join('')}</div>`:''}`;
 bind();
}
function kpi(label,value,sub,type=''){return`<div class="card ${type==='danger'?'handover-danger':type==='warn'?'handover-warn':''}"><div class="label">${esc(label)}</div><div class="kpi">${value}</div><div class="small muted">${esc(sub)}</div></div>`}
function createCard(){return`<div class="card handover-create" style="margin-top:14px"><div class="row"><div><strong>Créer une passation</strong><div class="small muted">Transmettre au prochain responsable un sujet à surveiller, traiter ou résoudre.</div></div><span class="pill">Responsable / Direction</span></div><div class="form-grid" style="margin-top:10px"><div class="field full"><label>Sujet *</label><input id="hoTitle" maxlength="120" placeholder="Ex. TPE caisse 2 instable"></div><div class="field full"><label>Description</label><textarea id="hoDescription" rows="3" placeholder="Contexte, action attendue, point de vigilance..."></textarea></div><div class="field"><label>Catégorie</label><select id="hoCategory"><option value="OPERATIONS">Exploitation</option><option value="STAFFING">Équipe</option><option value="SECURITY">Sécurité</option><option value="COLD">Froid</option><option value="TECHNICAL">Technique</option><option value="STOCK">Stock</option><option value="CASH">Caisses</option><option value="QUALITY">Qualité</option><option value="COMMERCIAL">Prix & promos</option></select></div><div class="field"><label>Priorité</label><select id="hoPriority"><option value="NORMAL">Normale</option><option value="HIGH">Haute</option><option value="CRITICAL">Critique</option><option value="LOW">Basse</option></select></div><div class="field"><label>Date cible</label><input id="hoTargetDate" type="date" value="${tomorrow()}"></div><div class="field handover-blocking-field"><label>Ouverture</label><label class="handover-check"><input id="hoBlocking" type="checkbox"> Bloquer l’ouverture tant que non résolu</label></div></div><button class="btn brand" id="createHandover" style="margin-top:12px">Créer la passation</button></div>`}
function itemCard(x,ro){const overdue=x.target_business_date&&x.target_business_date<new Date().toISOString().slice(0,10)&&!['RESOLVED','CANCELLED'].includes(x.status),blocking=!!x.blocking_opening&&x.status!=='RESOLVED';return`<article class="card handover-item ${blocking?'handover-item-blocking':''}"><div class="handover-item-head"><div><div class="row handover-meta-row"><span class="pill">${esc(categoryLabel(x.category))}</span>${status(x.priority,priorityKind(x.priority))}${blocking?status('BLOQUE OUVERTURE','danger'):''}${overdue?status('EN RETARD','danger'):''}</div><h3>${esc(x.title)}</h3><div class="small muted">Cible ${esc(x.target_business_date||'—')} · créée par ${esc(x.created_by_name||'—')} · ${dt(x.created_at)}</div></div>${status(statusLabel(x.status),x.status==='RESOLVED'?'ok':x.status==='ACKNOWLEDGED'?'warn':'neutral')}</div>${x.description?`<p class="handover-description">${esc(x.description)}</p>`:''}${x.acknowledged_by_name?`<div class="small muted handover-audit">Pris en compte par ${esc(x.acknowledged_by_name)} · ${dt(x.acknowledged_at)}</div>`:''}${x.resolution_note?`<div class="banner ban-info handover-resolution"><strong>Résolution</strong><div>${esc(x.resolution_note)}</div><div class="small">${esc(x.resolved_by_name||'—')} · ${dt(x.resolved_at)}</div></div>`:''}${!ro&&['OPEN','ACKNOWLEDGED'].includes(x.status)?`<div class="handover-actions">${x.status==='OPEN'?`<button class="btn soft" data-ho-ack="${esc(x.id)}">Prendre en compte</button>`:''}<div class="handover-resolve"><input data-ho-note="${esc(x.id)}" placeholder="Note de résolution obligatoire"><button class="btn brand" data-ho-resolve="${esc(x.id)}">Résoudre</button></div></div>`:''}</article>`}
function bind(){
 $('#createHandover')?.addEventListener('click',create);
 $('#reviewHandoverClosing')?.addEventListener('click',reviewClosing);
 document.querySelectorAll('[data-ho-ack]').forEach(b=>b.addEventListener('click',()=>ack(b)));
 document.querySelectorAll('[data-ho-resolve]').forEach(b=>b.addEventListener('click',()=>resolve(b)));
}
async function create(){if(busy)return;const title=$('#hoTitle').value.trim();if(!title)return toast('Sujet de passation obligatoire.');busy=true;const b=$('#createHandover');b.disabled=true;try{await api(`/api/stores/${app.storeId}/handover`,{method:'POST',body:JSON.stringify({title,description:$('#hoDescription').value.trim(),category:$('#hoCategory').value,priority:$('#hoPriority').value,targetDate:$('#hoTargetDate').value||null,blockingOpening:$('#hoBlocking').checked})});toast('Passation créée.');await renderHandover()}catch(e){toast(e.message)}finally{busy=false;if(b)b.disabled=false}}
async function ack(btn){if(busy)return;busy=true;btn.disabled=true;try{await api(`/api/handover/${encodeURIComponent(btn.dataset.hoAck)}/acknowledge`,{method:'POST'});toast('Passation prise en compte.');await renderHandover()}catch(e){toast(e.message)}finally{busy=false;btn.disabled=false}}
async function resolve(btn){if(busy)return;const id=btn.dataset.hoResolve,note=document.querySelector(`[data-ho-note="${id}"]`)?.value.trim();if(!note)return toast('Ajoute une note de résolution.');busy=true;btn.disabled=true;try{await api(`/api/handover/${encodeURIComponent(id)}/resolve`,{method:'POST',body:JSON.stringify({note})});toast('Passation résolue.');await renderHandover()}catch(e){toast(e.message)}finally{busy=false;btn.disabled=false}}
async function reviewClosing(){if(busy)return;busy=true;const b=$('#reviewHandoverClosing');b.disabled=true;try{await api(`/api/stores/${app.storeId}/handover/review-closing`,{method:'POST'});toast('Revue de passation enregistrée.');await renderHandover()}catch(e){toast(e.message)}finally{busy=false;if(b)b.disabled=false}}
