import{api}from'../api.js';
import{app,canManage}from'../state.js';
import{$,status,esc,toast}from'../ui.js';
import{EQUIPMENT_TYPES,IMPACTS,buildMaintenanceIncident,maintenanceSummary}from'../maintenance-model.js';

let assignees=[];
const dt=v=>v?new Date(String(v).endsWith('Z')?v:String(v)+'Z').toLocaleString('fr-FR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'—';
const sev=v=>v==='CRITICAL'?'danger':v==='HIGH'?'warn':v==='MEDIUM'?'neutral':'ok';

export async function renderMaintenance(){
 const data=await api(`/api/stores/${app.storeId}/incidents?status=ALL`),s=maintenanceSummary(data.items||[]);assignees=canManage()?await api(`/api/stores/${app.storeId}/assignees`):[];
 $('#maintenanceContent').innerHTML=`
  <div class="grid g4 maintenance-kpis">
   ${kpi('Pannes ouvertes',s.openCount,'équipement(s) à traiter',s.openCount?'warn':'')}
   ${kpi('Critiques',s.critical,'priorité immédiate',s.critical?'danger':'')}
   ${kpi('Bloquantes',s.blocking,'impact process / magasin',s.blocking?'danger':'')}
   ${kpi('En retard',s.overdue,'SLA dépassé',s.overdue?'danger':'')}
  </div>
  ${s.topEquipment?`<div class="banner ${s.topEquipment[1]>1?'ban-danger':'ban-info'}" style="margin-top:14px"><strong>Équipement le plus incidenté actuellement : ${esc(s.topEquipment[0])}</strong><div class="small">${s.topEquipment[1]} incident(s) ouvert(s).</div></div>`:''}
  ${canManage()?createPanel():`<div class="role-lock" style="margin-top:14px">Lecture seule. Le signalement et le traitement des pannes sont réservés au Responsable magasin et au Directeur d’Exploitation.</div>`}
  <div class="network-section-title"><div><strong>Pannes & équipements à traiter</strong><span>Chaque fiche utilise le moteur d’incidents, SLA, actions et preuves StoreOps.</span></div><span class="pill">${s.openCount}</span></div>
  <div class="maintenance-list">${s.open.length?s.open.map(card).join(''):'<div class="card empty">Aucune panne technique ouverte.</div>'}</div>
  <div class="network-section-title"><div><strong>Historique maintenance</strong><span>Derniers équipements remis en service.</span></div><span class="pill">${s.resolved.length}</span></div>
  <div class="maintenance-list resolved">${s.resolved.length?s.resolved.slice(0,15).map(card).join(''):'<div class="card empty">Aucun historique maintenance.</div>'}</div>`;
 bind();
}
function kpi(label,value,sub,type=''){return`<div class="card ${type==='danger'?'maintenance-danger':type==='warn'?'maintenance-warn':''}"><div class="label">${esc(label)}</div><div class="kpi">${value}</div><div class="small muted">${esc(sub)}</div></div>`}
function createPanel(){return`<section class="card maintenance-create" style="margin-top:14px"><div class="row"><div><strong>Signaler une panne / indisponibilité</strong><div class="small muted">Le niveau de blocage détermine automatiquement la criticité minimale et l’exigence de preuve.</div></div><span class="pill">Responsable / Direction</span></div><div class="form-grid" style="margin-top:11px"><div class="field"><label>Équipement *</label><select id="mntType">${EQUIPMENT_TYPES.map(x=>`<option value="${x[0]}">${esc(x[1])}</option>`).join('')}</select></div><div class="field"><label>Identifiant / emplacement</label><input id="mntAsset" placeholder="Ex. Caisse 2, TPE 04, chambre froide"></div><div class="field full"><label>Panne / défaut *</label><input id="mntIssue" placeholder="Ex. ne démarre plus, impression illisible, porte ne ferme pas"></div><div class="field"><label>Impact opérationnel</label><select id="mntImpact">${Object.entries(IMPACTS).map(([k,v])=>`<option value="${k}" ${k==='DEGRADED'?'selected':''}>${esc(v.label)}</option>`).join('')}</select></div><div class="field"><label>Criticité</label><select id="mntCriticality"><option value="">Automatique selon impact</option><option value="LOW">LOW</option><option value="MEDIUM">MEDIUM</option><option value="HIGH">HIGH</option><option value="CRITICAL">CRITICAL</option></select></div><div class="field"><label>Affecter à</label><select id="mntAssignee"><option value="">Responsable magasin</option>${assignees.map(a=>`<option value="${esc(a.id)}">${esc(a.name)}</option>`).join('')}</select></div><div class="field"><label>Échéance spécifique</label><input id="mntDue" type="datetime-local"></div><div class="field full"><label>Détails / diagnostic initial</label><textarea id="mntDetails" rows="3" placeholder="Symptôme, sécurité mise en place, prestataire contacté, référence ticket…"></textarea></div></div><div id="mntImpactHint" class="banner ban-info" style="margin-top:10px"></div><button class="btn brand" id="mntCreate" style="margin-top:10px">Créer l’incident maintenance</button></section>`}
function card(i){const late=i.is_overdue||i.sla?.state==='BREACHED',actionsDone=(i.actions||[]).filter(a=>a.status==='DONE').length;return`<button class="card maintenance-item ${late?'late':''}" data-open-incident="${esc(i.id)}"><div class="row"><div><div class="small muted">${dt(i.created_at)} · ${esc(i.assigned_to_name||'Non affecté')}</div><h3>${esc(i.title)}</h3></div>${status(i.status==='RESOLVED'?'Résolu':i.criticality,i.status==='RESOLVED'?'ok':sev(i.criticality))}</div>${i.description?`<p>${esc(i.description).replaceAll('\n','<br>')}</p>`:''}<div class="maintenance-meta"><div><span>Blocage</span><strong>${esc(i.blocking_level||'NONE')}</strong></div><div><span>SLA</span><strong class="${late?'danger-text':''}">${esc(i.sla?.label||'—')}</strong></div><div><span>Actions</span><strong>${actionsDone}/${(i.actions||[]).length}</strong></div><div><span>Preuves</span><strong>${(i.evidence||[]).length}${i.requires_evidence?' requise':''}</strong></div></div><div class="small muted maintenance-open-hint">Ouvrir la fiche pour actions, preuve et résolution</div></button>`}
function bind(){
 const impact=$('#mntImpact');if(impact){const refresh=()=>{const r=IMPACTS[impact.value]||IMPACTS.DEGRADED;$('#mntImpactHint').innerHTML=`<strong>${esc(r.label)}</strong><div class="small">Blocage : ${esc(r.blockingLevel)} · criticité automatique : ${esc(r.criticality)}${r.blockingLevel!=='NONE'?' · preuve requise à la clôture':''}</div>`};impact.addEventListener('change',refresh);refresh()}
 $('#mntCreate')?.addEventListener('click',createMaintenance);
}
async function createMaintenance(){const b=$('#mntCreate');if(b.disabled)return;try{const payload=buildMaintenanceIncident({equipmentType:$('#mntType').value,equipmentId:$('#mntAsset').value,issue:$('#mntIssue').value,details:$('#mntDetails').value,impact:$('#mntImpact').value,criticality:$('#mntCriticality').value,assignedTo:$('#mntAssignee').value||null,dueAt:$('#mntDue').value||null});b.disabled=true;b.textContent='Création…';const inc=await api(`/api/stores/${app.storeId}/incidents`,{method:'POST',body:JSON.stringify(payload)});try{await api(`/api/incidents/${inc.id}/actions`,{method:'POST',body:JSON.stringify({title:'Diagnostiquer, sécuriser puis remettre l’équipement en service',assignedTo:payload.assignedTo,dueAt:payload.dueAt,note:'Action créée automatiquement par le module Maintenance.'})})}catch{}toast('Incident maintenance créé.');await renderMaintenance()}catch(e){toast(e.message)}finally{if(b){b.disabled=false;b.textContent='Créer l’incident maintenance'}}}
