import {esc} from '../ui.js';

const groups=[
 {code:'DAY',icon:'◷',title:'Journée magasin',subtitle:'Ouverture, passation, équipe et fermeture',actions:[['opening','Ouverture','Préparer et déclarer le magasin prêt'],['handover','Passation','Transmettre les sujets entre équipes'],['staffing','Équipe & prise de poste','Planning, présence et couverture'],['closing','Fermeture','Clôturer la journée en sécurité']]},
 {code:'COMMERCE',icon:'↗',title:'Commerce & stock',subtitle:'Prix, réception, disponibilité et pertes',actions:[['commercial','Prix & promotions','Exécuter et contrôler les changements'],['receipts','Réception','PO, quantités et conformité'],['inventory','Stock & inventaire','Ruptures, comptages et écarts'],['losses','Démarque & pertes','Casse, périmés, vols et closing pack']]},
 {code:'QUALITY',icon:'✓',title:'Qualité & risques',subtitle:'Sécurité produit, équipements et incidents',actions:[['coldChain','Chaîne du froid','Zones, températures et écarts'],['dlc','DLC / DDM','FEFO, dates et actions'],['quality','Qualité','Contrôles et non-conformités'],['maintenance','Maintenance','Pannes, SLA et remise en service'],['incidents','Incidents','Actions correctives et preuves']]},
 {code:'CASH',icon:'▣',title:'Caisses',subtitle:'Préparation et clôture financière',actions:[['cashOpening','Préparation caisses','Fonds, POS, TPE et shifts'],['cash','Caisses & clôture','Rapprochement et validation']]}
];
let selected=null;
function allActions(){return groups.flatMap(g=>g.actions.map(a=>({group:g.title,page:a[0],title:a[1],detail:a[2]})))}
function groupCard(g){return `<button class="ux-choice" data-ops-group="${g.code}"><span class="ux-icon">${g.icon}</span><strong>${esc(g.title)}</strong><small>${esc(g.subtitle)}</small><em>Ouvrir →</em></button>`}
function actionRow(a){return `<button class="ux-command" data-manager-go="${esc(a[0])}"><span><strong>${esc(a[1])}</strong><small>${esc(a[2])}</small></span><span class="arrow">›</span></button>`}
function renderHome(root){root.innerHTML=`<div class="ux-hero"><div><div class="ux-eyebrow">OPÉRATIONS</div><h2>Que voulez-vous faire ?</h2><p>Toutes les fonctions magasin restent disponibles, sans transformer la navigation en menu ERP.</p></div></div><div class="ux-search"><input id="opsSearch" type="search" autocomplete="off" placeholder="Rechercher : inventaire, prix, réception…"></div><div id="opsSearchResults"></div><div class="ux-grid" id="opsGroups">${groups.map(groupCard).join('')}</div>`;bindHome(root)}
function bindHome(root){root.querySelectorAll('[data-ops-group]').forEach(b=>b.onclick=()=>{selected=b.dataset.opsGroup;render(root)});const input=document.getElementById('opsSearch'),results=document.getElementById('opsSearchResults'),grid=document.getElementById('opsGroups');if(input)input.oninput=()=>{const q=input.value.trim().toLowerCase();if(!q){results.innerHTML='';grid.hidden=false;return}const rows=allActions().filter(x=>`${x.title} ${x.detail} ${x.group}`.toLowerCase().includes(q));grid.hidden=true;results.innerHTML=`<div class="ux-command-list">${rows.length?rows.map(x=>actionRow([x.page,x.title,`${x.group} · ${x.detail}`])).join(''):'<div class="ux-loading">Aucun résultat.</div>'}</div>`}}
function renderGroup(root,g){root.innerHTML=`<button class="ux-back" id="opsBack">← Opérations</button><div class="ux-hero"><div><div class="ux-eyebrow">${esc(g.title)}</div><h2>${esc(g.subtitle)}</h2><p>Choisissez l’action. StoreOps vous amène directement au bon parcours.</p></div></div><div class="ux-command-list" style="margin-top:14px">${g.actions.map(actionRow).join('')}</div>`;document.getElementById('opsBack').onclick=()=>{selected=null;render(root)}}
function render(root){const g=groups.find(x=>x.code===selected);if(g)return renderGroup(root,g);renderHome(root)}
export async function renderOperationsHub(){const root=document.getElementById('operationsHubContent');if(root)render(root)}
