import{api}from'../api.js';
import{app,canManage,isDirector}from'../state.js';
import{$,status,esc,toast}from'../ui.js';

export async function renderStaffing(){
 const [data,cfg]=await Promise.all([api(`/api/stores/${app.storeId}/staffing`),api('/api/staffing/config')]),d=data.day,p=cfg.policy;
 if(!d){
  const reason=data.emptyReason||data.sync?.error||'Aucun planning publié pour aujourd’hui.';
  $('#staffingContent').innerHTML=`<div class="card"><div class="row"><div><div class="label">ÉQUIPE & PRISE DE POSTE</div><h3>Aucun planning publié aujourd’hui</h3><p class="small muted">${esc(reason)}</p></div>${status('Planning requis','warn')}</div><div class="banner ban-info" style="margin-top:12px"><strong>Aucune équipe n’est inventée.</strong><span>Ajoutez les collaborateurs, créez leurs shifts puis publiez le planning. Les personnes publiées apparaîtront ici pour le pointage.</span></div><button class="btn brand" id="goTeamPlanning" style="margin-top:12px">Créer / publier le planning →</button></div>${isDirector()?policy(p):''}`;
  $('#goTeamPlanning')?.addEventListener('click',()=>document.querySelector('[data-page="managerTeam"]')?.click());bindPolicy();return
 }
 const m=d.metrics,locked=d.status==='OPENED';
 $('#staffingContent').innerHTML=`<div class="grid g4"><div class="card"><div class="label">Statut</div><div class="kpi">${d.status==='READY'||locked?'OK':m.pending}</div><div class="small muted">${esc(d.status)}</div></div><div class="card"><div class="label">Présents</div><div class="kpi">${m.present}</div><div class="small muted">${m.replaced} remplacement(s)</div></div><div class="card"><div class="label">Absents</div><div class="kpi">${m.absent}</div><div class="small muted">${m.pending} à pointer</div></div><div class="card"><div class="label">Couverture</div><div class="kpi">${m.coverageOk?'OK':'NOK'}</div><div class="small muted">Resp ${m.coverage.MANAGER}/${p.required_managers} · Caisse ${m.coverage.CASHIER}/${p.required_cashiers} · Surface ${m.coverage.FLOOR}/${p.required_floor}</div></div></div>${!m.coverageOk?`<div class="banner ban-danger" style="margin-top:14px"><strong>Couverture minimale non atteinte</strong><span>Manque : ${m.gaps.managers} responsable · ${m.gaps.cashiers} caisse · ${m.gaps.floor} surface.</span></div>`:''}<div class="card" style="margin-top:14px"><div class="row"><div><strong>Planning d’ouverture</strong><div class="small muted">Source ${esc(data.sync?.source||'StoreOps')} · pointage réel terrain</div></div>${status(locked?'Ouvert':d.status==='READY'?'Équipe prête':'À pointer',locked||d.status==='READY'?'ok':'warn')}</div><div class="staff-grid">${d.lines.map(x=>line(x,locked)).join('')}</div></div>${isDirector()?policy(p):''}`;bind()
}
function line(x,locked){const s=x.attendance_status,kind=s==='PRESENT'||s==='REPLACED'?'ok':s==='ABSENT'?'danger':'warn';return`<article class="staff-line"><div class="row"><div><div class="label">${esc(x.scheduled_start||'—')} · ${esc(x.role_label)}</div><strong>${esc(x.employee_name)}</strong></div>${status(s==='PENDING'?'À pointer':s==='PRESENT'?'Présent':s==='ABSENT'?'Absent':'Remplacé',kind)}</div>${x.replacement_name?`<div class="small">Remplaçant : <strong>${esc(x.replacement_name)}</strong></div>`:''}${canManage()&&!locked?`<div class="staff-actions"><button class="btn soft" data-staff="${x.id}" data-status="PRESENT">Présent</button><button class="btn soft" data-staff="${x.id}" data-status="ABSENT">Absent</button><button class="btn soft" data-staff="${x.id}" data-status="REPLACED">Remplacé</button></div>`:''}</article>`}
function policy(p){return`<div class="card" style="margin-top:14px"><div class="row"><div><strong>Couverture minimale réseau</strong><div class="small muted">Direction uniquement</div></div><button class="btn soft" id="saveStaffPolicy">Enregistrer</button></div><div class="form-grid" style="margin-top:10px"><div class="field"><label>Responsables</label><input id="staffPolMgr" type="number" min="1" value="${p.required_managers}"></div><div class="field"><label>Caissiers</label><input id="staffPolCash" type="number" min="1" value="${p.required_cashiers}"></div><div class="field"><label>Surface</label><input id="staffPolFloor" type="number" min="0" value="${p.required_floor}"></div></div></div>`}
function bindPolicy(){$('#saveStaffPolicy')?.addEventListener('click',async()=>{try{await api('/api/staffing/policy',{method:'PUT',body:{requiredManagers:Number($('#staffPolMgr').value),requiredCashiers:Number($('#staffPolCash').value),requiredFloor:Number($('#staffPolFloor').value)}});toast('Couverture réseau mise à jour.');renderStaffing()}catch(e){toast(e.message)}})}
function bind(){document.querySelectorAll('[data-staff]').forEach(b=>b.onclick=async()=>{try{let replacementName='';if(b.dataset.status==='REPLACED'){replacementName=prompt('Nom du remplaçant :','')||'';if(!replacementName.trim())return}await api(`/api/staffing/lines/${b.dataset.staff}/attendance`,{method:'POST',body:{status:b.dataset.status,replacementName}});toast('Pointage enregistré.');renderStaffing()}catch(e){toast(e.message)}});bindPolicy()}
