import{api}from'../api.js';import{app,isDirector}from'../state.js';import{$,status,esc}from'../ui.js';import{integrationReadiness,readinessCounts}from'../integration-readiness.js';
const check=(label,x)=>`<div class="focus-meta"><span>${esc(label)}</span>${status(x?.ok?'OK':x?.skipped?'À faire':'NOK',x?.ok?'ok':x?.skipped?'neutral':'danger')}</div>${x?.error?`<div class="small muted" style="margin:4px 0 10px">${esc(x.error)}</div>`:''}`;
const showcaseDiagnostics=()=>({connected:false,mode:'SIMULATED',expectedAudience:null,configuration:{baseUrl:{configured:false,value:null},tenantId:{configured:false,value:null},clientId:{configured:false,value:null},clientSecret:{configured:false},oauthVersion:'v2',readModes:{product:'simulated',stock:'simulated',price:'simulated',promotion:'simulated'},mappings:{}},checks:{config:{ok:true,simulated:true},token:{ok:false,skipped:true},metadata:{ok:false,skipped:true}},nextAction:'Le Showcase est volontairement simulé. La connexion Dynamics réelle se teste depuis un backend StoreOps sécurisé.'});
const cell=x=>`<div>${status(x.label,x.tone||'neutral')}</div>`;
const readinessTable=rows=>`<div class="table-wrap"><table class="table"><thead><tr><th>Domaine</th><th>Source opérationnelle</th><th>D365 READ</th><th>D365 WRITE</th><th>Pilote</th></tr></thead><tbody>${rows.map(r=>`<tr><td><strong>${esc(r.domain)}</strong></td><td>${cell(r.storeops)}</td><td>${cell(r.read)}</td><td>${cell(r.write)}</td><td class="small">${esc(r.pilot)}</td></tr>`).join('')}</tbody></table></div>`;
export async function renderSystem(){if(!isDirector())return;const d=app.showcase?showcaseDiagnostics():await api('/api/dynamics/diagnostics');const c=d.configuration||{},m=c.mappings||{},readModes=c.readModes||{},ready=integrationReadiness({connected:d.connected,mappings:m,readModes}),counts=readinessCounts(ready);$('#systemContent').innerHTML=`
<div class="grid g2">
 <div class="card"><div class="row"><div><strong>Connexion Dynamics 365</strong><div class="small muted">Diagnostic service-to-service StoreOps → Finance & Operations. Connexion technique ≠ domaine métier LIVE.</div></div>${status(d.connected?'Connexion D365 OK':d.mode==='SIMULATED'?'D365 désactivé':'Connexion à configurer',d.connected?'ok':d.mode==='SIMULATED'?'neutral':'danger')}</div><div style="margin-top:14px">${check('1. Configuration',d.checks?.config)}${check('2. Jeton Microsoft Entra',d.checks?.token)}${check('3. Metadata/DataEntities',d.checks?.metadata)}</div>${d.nextAction?`<div class="banner ${d.connected?'ban-info':'ban-danger'}" style="margin-top:12px"><strong>Prochaine action</strong><span>${esc(d.nextAction)}</span></div>`:''}${!app.showcase?'<button id="dynRetest" class="btn brand" style="margin-top:12px">Retester la connexion</button>':''}</div>
 <div class="card"><strong>Configuration backend</strong><div class="focus-meta"><span>StoreOps version</span><strong>${esc(app.version||'—')}</strong></div><div class="focus-meta"><span>D365 transport</span><strong>${esc(d.mode)}</strong></div><div class="focus-meta"><span>Article / EAN</span><strong>${esc((readModes.product||'simulated').toUpperCase())}</strong></div><div class="focus-meta"><span>Stock</span><strong>${esc((readModes.stock||'simulated').toUpperCase())}</strong></div><div class="focus-meta"><span>Prix</span><strong>${esc((readModes.price||'simulated').toUpperCase())}</strong></div><div class="focus-meta"><span>Promotions</span><strong>${esc((readModes.promotion||'simulated').toUpperCase())}</strong></div><div class="focus-meta"><span>Environment URL</span><strong>${esc(c.baseUrl?.value||'Non configurée')}</strong></div><div class="focus-meta"><span>Tenant ID</span><strong>${esc(c.tenantId?.value||'Non configuré')}</strong></div><div class="focus-meta"><span>Client ID</span><strong>${esc(c.clientId?.value||'Non configuré')}</strong></div><div class="focus-meta"><span>Client secret</span><strong>${c.clientSecret?.configured?'Configuré ✓':'Non configuré'}</strong></div><div class="focus-meta"><span>OAuth</span><strong>${esc(c.oauthVersion||'v2')}</strong></div><p class="small muted">Le secret et le jeton ne sont jamais renvoyés au navigateur. Audience attendue : ${esc(d.expectedAudience||'—')}</p></div>
</div>
<div class="card" style="margin-top:14px"><div class="row"><div><strong>Sources & readiness</strong><div class="small muted">Statuts explicites : LIVE Dynamics = testé et activé ; StoreOps = donnée/process StoreOps ; Simulé = fallback non Dynamics ; À mapper = intégration non qualifiée.</div></div><div class="row"><span class="pill">${counts.liveReads} READ LIVE</span><span class="pill">${counts.simulatedReads} simulé(s)</span><span class="pill">${counts.writeMapping} write(s) à mapper</span></div></div><div style="margin-top:12px">${readinessTable(ready)}</div><div class="banner ban-info" style="margin-top:12px"><strong>Règle pilote</strong><span>Aucun posting F&O n’est présenté comme LIVE tant que son mapping exact et son test de bout en bout ne sont pas validés. Réception, ajustement inventaire, démarque et caisse restent bloqués.</span></div></div>
<div class="grid g2" style="margin-top:14px">
 <div class="card"><div class="row"><div><strong>Découverte Data Entities</strong><div class="small muted">La REST Metadata de F&O permet de retrouver les noms publics réellement disponibles dans votre environnement.</div></div><span class="pill">${d.checks?.metadata?.entityCount??0} entité(s)</span></div>${app.showcase?'<div class="empty" style="margin-top:12px">Disponible après connexion du backend Dynamics réel.</div>':`<div class="row" style="margin-top:10px"><input id="entitySearch" placeholder="Ex. barcode, released product, purchase order, inventory" style="flex:1"><button id="entitySearchBtn" class="btn soft">Rechercher</button></div><div id="entityResults"></div>`}</div>
 <div class="card"><strong>Mapping actuel StoreOps</strong><div class="focus-meta"><span>EAN / Barcode entity</span><strong>${esc(m.barcodeEntity||'À découvrir')}</strong></div><div class="focus-meta"><span>Product entity</span><strong>${esc(m.productEntity||'Optionnel')}</strong></div><div class="focus-meta"><span>Stock entity</span><strong>${esc(m.stockEntity||'À découvrir')}</strong></div><div class="focus-meta"><span>Prix de base</span><strong>${esc(m.basePriceEntity||'À découvrir')}</strong></div><div class="focus-meta"><span>Promo headers</span><strong>${esc(m.retailDiscountEntity||'À découvrir')}</strong></div><div class="focus-meta"><span>Promo lines</span><strong>${esc(m.retailDiscountLineEntity||'À découvrir')}</strong></div><div class="small muted">EAN : ${esc(m.barcodeField||'Barcode')} → ${esc(m.barcodeProductField||'ItemNumber')} · produit ${esc(m.productNumberField||'ProductNumber')} / ${esc(m.productNameField||'ProductName')}.</div><div class="banner ban-info" style="margin-top:12px"><strong>Ordre d’activation</strong><span>1. Article/EAN → 2. Stock → 3. Prix → 4. Promotions. PO/réception reste à auditer ; tous les writes restent à mapper.</span></div></div>
</div>`;
if(app.showcase)return;
$('#dynRetest').onclick=async()=>{const b=$('#dynRetest');b.disabled=true;b.textContent='Test en cours…';try{await api('/api/dynamics/diagnostics?force=1');await renderSystem()}catch(e){b.disabled=false;b.textContent='Retester la connexion';alert(e.message)}};
$('#entitySearchBtn').onclick=async()=>{const host=$('#entityResults');try{const rows=await api(`/api/dynamics/entities?q=${encodeURIComponent($('#entitySearch').value.trim())}`);host.innerHTML=rows.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Entity</th><th>Collection / label</th><th></th></tr></thead><tbody>${rows.slice(0,40).map(x=>{const name=x.PublicCollectionName||x.PublicEntityName||x.Name||x.EntityName||'';return`<tr><td><code>${esc(x.PublicEntityName||x.Name||x.EntityName||name||'Entity')}</code></td><td>${esc(x.PublicCollectionName||x.Label||'')}</td><td>${name?`<button class="btn soft" data-probe-entity="${esc(name)}">Tester</button>`:''}</td></tr>`}).join('')}</tbody></table></div>`:'<div class="empty">Aucune entité trouvée.</div>';host.querySelectorAll('[data-probe-entity]').forEach(b=>b.onclick=async()=>{try{const p=await api(`/api/dynamics/probe?entity=${encodeURIComponent(b.dataset.probeEntity)}&top=1`);alert(p.ok?`OData OK · ${p.entity} · ${p.rowCount} ligne(s) · ${p.latencyMs} ms`:p.message)}catch(e){alert(e.message)}})}catch(e){host.innerHTML=`<div class="banner ban-danger">${esc(e.message)}</div>`}};
}
