import{api}from'../api.js';import{app,isDirector}from'../state.js';import{$,status,esc}from'../ui.js';
const check=(label,x)=>`<div class="focus-meta"><span>${esc(label)}</span>${status(x?.ok?'OK':x?.skipped?'À faire':'NOK',x?.ok?'ok':x?.skipped?'neutral':'danger')}</div>${x?.error?`<div class="small muted" style="margin:4px 0 10px">${esc(x.error)}</div>`:''}`;
const showcaseDiagnostics=()=>({connected:false,mode:'SIMULATED',expectedAudience:null,configuration:{baseUrl:{configured:false,value:null},tenantId:{configured:false,value:null},clientId:{configured:false,value:null},clientSecret:{configured:false},oauthVersion:'v2',mappings:{}},checks:{config:{ok:true,simulated:true},token:{ok:false,skipped:true},metadata:{ok:false,skipped:true}},nextAction:'Le Showcase est volontairement simulé. La connexion Dynamics réelle se teste depuis un backend StoreOps sécurisé.'});
export async function renderSystem(){if(!isDirector())return;const d=app.showcase?showcaseDiagnostics():await api('/api/dynamics/diagnostics');const c=d.configuration||{},m=c.mappings||{};$('#systemContent').innerHTML=`
<div class="grid g2">
 <div class="card"><div class="row"><div><strong>Connexion Dynamics 365</strong><div class="small muted">Diagnostic service-to-service StoreOps → Finance & Operations</div></div>${status(d.connected?'Connecté':d.mode==='SIMULATED'?'Simulation':'À configurer',d.connected?'ok':d.mode==='SIMULATED'?'warn':'danger')}</div><div style="margin-top:14px">${check('1. Configuration',d.checks?.config)}${check('2. Jeton Microsoft Entra',d.checks?.token)}${check('3. Metadata/DataEntities',d.checks?.metadata)}</div>${d.nextAction?`<div class="banner ${d.connected?'ban-info':'ban-danger'}" style="margin-top:12px"><strong>Prochaine action</strong><span>${esc(d.nextAction)}</span></div>`:''}${!app.showcase?'<button id="dynRetest" class="btn brand" style="margin-top:12px">Retester la connexion</button>':''}</div>
 <div class="card"><strong>Configuration backend</strong><div class="focus-meta"><span>D365_MODE</span><strong>${esc(d.mode)}</strong></div><div class="focus-meta"><span>Environment URL</span><strong>${esc(c.baseUrl?.value||'Non configurée')}</strong></div><div class="focus-meta"><span>Tenant ID</span><strong>${esc(c.tenantId?.value||'Non configuré')}</strong></div><div class="focus-meta"><span>Client ID</span><strong>${esc(c.clientId?.value||'Non configuré')}</strong></div><div class="focus-meta"><span>Client secret</span><strong>${c.clientSecret?.configured?'Configuré ✓':'Non configuré'}</strong></div><div class="focus-meta"><span>OAuth</span><strong>${esc(c.oauthVersion||'v2')}</strong></div><p class="small muted">Le secret et le jeton ne sont jamais renvoyés au navigateur. Audience attendue : ${esc(d.expectedAudience||'—')}</p></div>
</div>
<div class="grid g2" style="margin-top:14px">
 <div class="card"><div class="row"><div><strong>Découverte Data Entities</strong><div class="small muted">La REST Metadata de F&O permet de retrouver les noms publics réellement disponibles dans votre environnement.</div></div><span class="pill">${d.checks?.metadata?.entityCount??0} entité(s)</span></div>${app.showcase?'<div class="empty" style="margin-top:12px">Disponible après connexion du backend Dynamics réel.</div>':`<div class="row" style="margin-top:10px"><input id="entitySearch" placeholder="Ex. barcode, released product, purchase order, inventory" style="flex:1"><button id="entitySearchBtn" class="btn soft">Rechercher</button></div><div id="entityResults"></div>`}</div>
 <div class="card"><strong>Mapping actuel StoreOps</strong><div class="focus-meta"><span>EAN / Barcode entity</span><strong>${esc(m.barcodeEntity||'À découvrir')}</strong></div><div class="focus-meta"><span>Product entity</span><strong>${esc(m.productEntity||'À découvrir')}</strong></div><div class="small muted">Champs actuels : ${esc(m.barcodeField||'Barcode')} → ${esc(m.barcodeProductField||'ItemNumber')} · produit ${esc(m.productNumberField||'ProductNumber')} / ${esc(m.productNameField||'ProductName')}.</div><div class="banner ban-info" style="margin-top:12px"><strong>Ordre recommandé</strong><span>1. Article/EAN → 2. Stock → 3. PO/réception → 4. Prix/promos → 5. shifts/caisses. Aucun write réel n’est activé tant que le mapping n’est pas validé.</span></div></div>
</div>`;
if(app.showcase)return;
$('#dynRetest').onclick=async()=>{const b=$('#dynRetest');b.disabled=true;b.textContent='Test en cours…';try{await api('/api/dynamics/diagnostics?force=1');await renderSystem()}catch(e){b.disabled=false;b.textContent='Retester la connexion';alert(e.message)}};
$('#entitySearchBtn').onclick=async()=>{const host=$('#entityResults');try{const rows=await api(`/api/dynamics/entities?q=${encodeURIComponent($('#entitySearch').value.trim())}`);host.innerHTML=rows.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Entity</th><th>Collection / label</th><th></th></tr></thead><tbody>${rows.slice(0,40).map(x=>{const name=x.PublicCollectionName||x.PublicEntityName||x.Name||x.EntityName||'';return`<tr><td><code>${esc(x.PublicEntityName||x.Name||x.EntityName||name||'Entity')}</code></td><td>${esc(x.PublicCollectionName||x.Label||'')}</td><td>${name?`<button class="btn soft" data-probe-entity="${esc(name)}">Tester</button>`:''}</td></tr>`}).join('')}</tbody></table></div>`:'<div class="empty">Aucune entité trouvée.</div>';host.querySelectorAll('[data-probe-entity]').forEach(b=>b.onclick=async()=>{try{const p=await api(`/api/dynamics/probe?entity=${encodeURIComponent(b.dataset.probeEntity)}&top=1`);alert(p.ok?`OData OK · ${p.entity} · ${p.rowCount} ligne(s) · ${p.latencyMs} ms`:p.message)}catch(e){alert(e.message)}})}catch(e){host.innerHTML=`<div class="banner ban-danger">${esc(e.message)}</div>`}};
}
