import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const frontend=path.join(root,'frontend');
const sw=fs.readFileSync(path.join(frontend,'sw.js'),'utf8');
const index=fs.readFileSync(path.join(frontend,'index.html'),'utf8');
const rescue=fs.readFileSync(path.join(frontend,'js/boot-rescue.js'),'utf8');
const bootClassic=fs.readFileSync(path.join(frontend,'js/boot-classic.js'),'utf8');
const authEntry=fs.readFileSync(path.join(frontend,'js/auth-entry.js'),'utf8');
const pwa=fs.readFileSync(path.join(frontend,'js/pwa.js'),'utf8');
const repair=fs.readFileSync(path.join(frontend,'repair.html'),'utf8');
const redirects=fs.readFileSync(path.join(frontend,'_redirects'),'utf8');
const netlifyBuild=fs.readFileSync(path.join(frontend,'netlify-build.sh'),'utf8');
const netlifyToml=fs.readFileSync(path.join(root,'netlify.toml'),'utf8');
const coreBlock=sw.match(/const CORE=\[([\s\S]*?)\];/)?.[1]||'';
const assets=[...coreBlock.matchAll(/'([^']+)'/g)].map(m=>m[1]);
assert.ok(assets.length>20,'PWA core should include the complete application shell');
for(const asset of assets){
  const local=asset==='/'?path.join(frontend,'index.html'):path.join(frontend,asset.replace(/^\//,''));
  assert.ok(fs.existsSync(local),`PWA precache asset missing: ${asset}`);
}
assert.match(sw,/url\.pathname\.startsWith\('\/api\/'\)/,'service worker must explicitly exclude API routes');
assert.match(sw,/if\(req\.method!==['"]GET['"]\)return/,'service worker must never cache writes');
assert.match(sw,/async function networkFirst/,'mutable application assets must use network-first delivery');
assert.match(sw,/cache:'no-store'/,'network-first shell refresh must bypass stale HTTP caches');
assert.match(sw,/Promise\.allSettled\(CORE\.map/,'one failed precache asset must not prevent service worker activation');
assert.ok(assets.includes('/js/boot-rescue.js'),'boot rescue must be part of the PWA shell');
assert.match(index,/\/js\/boot-rescue\.js/,'boot rescue must load before application startup');
assert.match(index,/\/manager-dlc-focus\.css/,'DLC focused manager stylesheet must be linked');
assert.match(index,/\/manager-commercial-focus\.css/,'commercial focused manager stylesheet must be linked');
assert.match(rescue,/storeops_boot_rescue_v153/,'boot rescue must guard against reload loops');
assert.match(rescue,/getRegistrations\(\)/,'boot rescue must be able to remove a broken service worker');
assert.match(rescue,/caches\.delete/,'boot rescue must clear stale StoreOps shell caches');
assert.match(bootClassic,/STOREOPS_BOOT_PREP/,'classic runtime must prepare a cache-clean startup before modules');
assert.match(bootClassic,/Impossible de démarrer StoreOps/,'classic runtime must surface module startup failures');
assert.match(netlifyBuild,/cat \.\/js\/boot-classic\.js >> runtime-config\.js/,'Netlify runtime config must include the classic boot guard');
assert.match(authEntry,/waitForStoreOpsUi/,'auth entry must wait for real profile/store readiness');
assert.match(authEntry,/STOREOPS_BOOT_PREP/,'auth entry must await cache cleanup before module loading');
assert.match(authEntry,/import\(`\.\/api\.js\?v=\$\{BUILD\}`\)/,'critical startup modules must be cache-busted');
assert.doesNotMatch(pwa,/serviceWorker\.register/,'pilot must not re-register a service worker while boot stability is being validated');
assert.match(netlifyToml,/for = "\/js\/\*"[\s\S]*Cache-Control = "no-store, max-age=0"/,'Netlify must disable JS caching during pilot hardening');
assert.match(netlifyToml,/for = "\/runtime-config\.js"[\s\S]*Cache-Control = "no-store, max-age=0"/,'runtime config must never be stale during pilot hardening');
assert.match(repair,/serviceWorker\.getRegistrations\(\)/,'repair gateway must unregister legacy service workers independently of app modules');
assert.match(repair,/caches\.keys\(\)/,'repair gateway must clear legacy browser caches');
assert.match(repair,/storeops_showcase_state_v7/,'repair gateway must reset potentially stale Showcase state');
assert.match(repair,/index\.html\?storeops_clean=1550/,'repair gateway must reopen a fresh index URL');
assert.doesNotMatch(redirects,/^\/\s+\/repair\.html\s+30[12]/m,'root must stay direct so Microsoft OAuth callback query parameters are preserved');
assert.match(redirects,/^\/repair\s+\/repair\.html\s+200/m,'repair must remain available as an explicit manual route');
assert.match(netlifyToml,/for = "\/repair\.html"[\s\S]*Cache-Control = "no-store, max-age=0"/,'repair gateway must never be cached');
const manifest=JSON.parse(fs.readFileSync(path.join(frontend,'manifest.webmanifest'),'utf8'));
assert.equal(manifest.display,'standalone');
assert.equal(manifest.start_url,'/');
console.log(`StoreOps V1.66 OAuth-safe boot contract passed · ${assets.length} cached assets`);
