import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const frontend=path.join(root,'frontend');
const sw=fs.readFileSync(path.join(frontend,'sw.js'),'utf8');
const index=fs.readFileSync(path.join(frontend,'index.html'),'utf8');
const rescue=fs.readFileSync(path.join(frontend,'js/boot-rescue.js'),'utf8');
const bootClassic=fs.readFileSync(path.join(frontend,'js/boot-classic.js'),'utf8');
const authEntry=fs.readFileSync(path.join(frontend,'js/auth-entry.js'),'utf8');
const pwa=fs.readFileSync(path.join(frontend,'js/pwa.js'),'utf8');
const repair=fs.readFileSync(path.join(frontend,'repair.html'),'utf8');
const redirects=fs.readFileSync(path.join(frontend,'_redirects'),'utf8');
const netlifyBuild=fs.readFileSync(path.join(frontend,'netlify-build.sh'),'utf8');
const netlifyToml=fs.readFileSync(path.join(root,'netlify.toml'),'utf8');

assert.match(sw,/registration\.unregister/,'legacy service worker must unregister itself');
assert.match(sw,/caches\.delete/,'legacy service worker must purge StoreOps shell caches');
assert.doesNotMatch(sw,/addEventListener\('fetch'/,'StoreOps service worker must never intercept runtime requests');
assert.doesNotMatch(sw,/const CORE=/,'StoreOps must not precache the application shell');
assert.match(index,/\/js\/boot-rescue\.js/,'boot rescue must load before application startup');
assert.match(index,/\/manager-dlc-focus\.css/);
assert.match(index,/\/manager-commercial-focus\.css/);
assert.match(rescue,/storeops_boot_rescue_v2243/,'boot rescue key must follow the current hard-recovery generation');
assert.match(rescue,/getRegistrations\(\)/);
assert.match(rescue,/caches\.delete/);
assert.match(bootClassic,/STOREOPS_BOOT_PREP/);
assert.match(bootClassic,/storeops-legacy-runtime-cleaned-'\+BUILD/,'legacy cleanup must run once per build, not once forever');
assert.match(bootClassic,/Impossible de démarrer StoreOps/);
assert.match(bootClassic,/STOREOPS_BOOT_HEARTBEAT/);
assert.match(bootClassic,/30000/);
assert.match(netlifyBuild,/cat \.\/js\/boot-classic\.js >> runtime-config\.js/);
assert.match(authEntry,/waitForStoreOpsUi\(ms=25000\)/);
assert.match(authEntry,/STOREOPS_BOOT_HEARTBEAT/);
assert.match(authEntry,/innerText/);
assert.match(authEntry,/STOREOPS_BOOT_PREP/);
assert.match(authEntry,/api\.js\?v=/);
assert.doesNotMatch(pwa,/serviceWorker\.register/,'current runtime must never register a new service worker');
assert.match(netlifyToml,/for = "\/"[\s\S]*Cache-Control = "no-store, max-age=0, must-revalidate"/,'root document must never be cached');
assert.match(netlifyToml,/for = "\/index\.html"[\s\S]*Cache-Control = "no-store, max-age=0"/);
assert.match(netlifyToml,/for = "\/runtime-config\.js"[\s\S]*Cache-Control = "no-store, max-age=0"/);
assert.match(netlifyToml,/for = "\/js\/auth-entry\.js"[\s\S]*Cache-Control = "no-cache, max-age=0, must-revalidate"/);
assert.match(netlifyToml,/for = "\/js\/app\.js"[\s\S]*Cache-Control = "no-cache, max-age=0, must-revalidate"/);
assert.match(repair,/serviceWorker\.getRegistrations\(\)/);
assert.match(repair,/caches\.keys\(\)/);
assert.match(repair,/storeops_showcase_state_v7/);
assert.doesNotMatch(redirects,/^\/\s+\/repair\.html\s+30[12]/m);
assert.match(redirects,/^\/repair\s+\/repair\.html\s+200/m);
const manifest=JSON.parse(fs.readFileSync(path.join(frontend,'manifest.webmanifest'),'utf8'));
assert.equal(manifest.display,'standalone');
assert.equal(manifest.start_url,'/');
console.log('StoreOps hard-recovery no-service-worker shell contract passed');
