import assert from 'node:assert/strict';
import {recommendReplenishment,decisionPresentation,weightedDailyVelocity} from '../services/replenishment-engine.mjs';
assert.equal(weightedDailyVelocity({dailySales7:10,dailySales28:6}),8.6);
let r=recommendReplenishment({storeAvailable:3,supplyAvailable:31,confirmedInbound:0,dailySales7:11,dailySales28:9,leadTimeDays:1,safetyDays:1,packSize:6});
assert.equal(r.decision,'REPLENISH');
assert.equal(r.actionQty%6,0);
assert.equal(decisionPresentation(r).cta,'Commander');
r=recommendReplenishment({storeAvailable:50,supplyAvailable:31,dailySales7:5,dailySales28:5,leadTimeDays:1,safetyDays:1,packSize:6});
assert.equal(r.decision,'OK');
r=recommendReplenishment({storeAvailable:0,supplyAvailable:0,dailySales7:10,dailySales28:10,leadTimeDays:1,safetyDays:1,packSize:6});
assert.equal(r.decision,'WAREHOUSE_OUT');
r=recommendReplenishment({storeAvailable:0,supplyAvailable:5,dailySales7:10,dailySales28:10,leadTimeDays:1,safetyDays:1,packSize:6});
assert.equal(r.decision,'PARTIAL');
r=recommendReplenishment({storeAvailable:-2,supplyAvailable:100,dailySales7:10,dailySales28:10});
assert.equal(r.decision,'CHECK_STOCK');
r=recommendReplenishment({storeAvailable:3,supplyAvailable:100});
assert.equal(r.decision,'NEED_SALES_DATA');
console.log('StoreOps replenishment recommendation engine contract OK');
