const nativeFetch=globalThis.fetch;
const preparedCash=new Set(),preparedCold=new Set(),preparedStaff=new Set();
function headerValue(headers,name){if(!headers)return null;if(headers instanceof Headers)return headers.get(name);if(Array.isArray(headers)){const x=headers.find(([k])=>String(k).toLowerCase()===name.toLowerCase());return x?.[1]||null}for(const [k,v] of Object.entries(headers))if(k.toLowerCase()===name.toLowerCase())return v;return null}
function validateTarget(url){const u=new URL(url),m=u.pathname.match(/^\/api\/stores\/([^/]+)\/process\/opening\/validate$/);return m?{u,storeId:m[1]}:null}
async function prepareStaffing(url,user){const t=validateTarget(url);if(!t)return;const key=`${t.storeId}:${user||'u-ops'}`;if(preparedStaff.has(key))return;const headers={'content-type':'application/json','x-demo-user':user||'u-ops'},r=await nativeFetch(`${t.u.origin}/api/stores/${t.storeId}/staffing`,{headers});if(!r.ok)return;const data=await r.json();for(const line of data.day?.lines||[]){if(line.attendance_status!=='PENDING')continue;await nativeFetch(`${t.u.origin}/api/staffing/lines/${line.id}/attendance`,{method:'POST',headers,body:JSON.stringify({status:'PRESENT',note:'Préparation automatique smoke historique'})})}preparedStaff.add(key)}
async function prepareCashOpening(url,user){const t=validateTarget(url);if(!t)return;const key=`${t.storeId}:${user||'u-ops'}`;if(preparedCash.has(key))return;const headers={'content-type':'application/json','x-demo-user':user||'u-ops'},r=await nativeFetch(`${t.u.origin}/api/stores/${t.storeId}/cash-opening`,{headers});if(!r.ok)return;const data=await r.json();for(const line of data.opening?.lines||[]){if(line.status==='READY'||data.opening?.status==='OPENED')continue;await nativeFetch(`${t.u.origin}/api/cash-opening/lines/${line.id}/check`,{method:'POST',headers,body:JSON.stringify({cashierName:line.cashier_name||`Caissier ${line.till_code}`,declaredFloat:Number(line.expected_float||0),posOk:true,tpeOk:true,printerOk:true,shiftOpened:true,note:'Préparation automatique smoke historique'})})}preparedCash.add(key)}
async function prepareColdChain(url,user){const t=validateTarget(url);if(!t)return;const key=`${t.storeId}:${user||'u-ops'}`;if(preparedCold.has(key))return;const headers={'content-type':'application/json','x-demo-user':user||'u-ops'},r=await nativeFetch(`${t.u.origin}/api/stores/${t.storeId}/cold-chain`,{headers});if(!r.ok)return;const data=await r.json();for(const line of data.day?.lines||[]){if(line.status==='READY'||data.day?.status==='OPENED')continue;const p=line.profile||{},temp=(Number(p.temp_min)+Number(p.temp_max))/2;await nativeFetch(`${t.u.origin}/api/cold-chain/lines/${line.id}/check`,{method:'POST',headers,body:JSON.stringify({temperature:temp,doorOk:true,note:'Préparation automatique smoke historique'})})}preparedCold.add(key)}
globalThis.fetch=async(input,init={})=>{const url=typeof input==='string'?input:input.url,user=headerValue(init.headers,'x-demo-user');if(String(url).includes('/process/opening/validate')){try{await prepareStaffing(url,user);await prepareCashOpening(url,user);await prepareColdChain(url,user)}catch{}}return nativeFetch(input,init)};
await import('./smoke.mjs');
