import assert from 'node:assert/strict';
import {calculateStoreHealth} from '../../frontend/js/store-health.js';

const base={dashboard:{day:{opening_status:'OPENED',closing_status:'NOT_STARTED'},incidents:0,criticalIncidents:0,overdueIncidents:0,escalatedIncidents:0,dlc:{expired:0,critical:0,pendingActions:0},commercial:{blocking:0,mismatch:0,pending:0},inventory:{pendingRecounts:0,varianceLines:0},opening:{blockers:0},cash:{pending:0,recounts:0}},staff:{},cold:{},cashOpen:{},receipts:{},quality:{},maintenance:{},loss:{}};
let h=calculateStoreHealth(base);assert.equal(h.score,100);assert.equal(h.state,'EXCELLENT');assert.equal(h.penalties.length,0);
h=calculateStoreHealth({...base,maintenance:{openCount:1,critical:1,blocking:1,overdue:0}});assert.ok(h.score<90);assert.ok(h.penalties.some(x=>x.key==='MAINTENANCE'));
h=calculateStoreHealth({...base,quality:{nonConform:1,temperatureNok:1,rejected:2}});assert.ok(h.penalties.some(x=>x.key==='QUALITY'));assert.ok(h.score<=90);
h=calculateStoreHealth({...base,receipts:{overdue:2,pendingLines:4,dueToday:0}});assert.equal(h.penalties.find(x=>x.key==='RECEIVING')?.points,12);
h=calculateStoreHealth({...base,dashboard:{...base.dashboard,incidents:1,criticalIncidents:1,overdueIncidents:1},maintenance:{openCount:1,critical:1,blocking:0,overdue:1}});assert.equal(h.penalties.some(x=>x.key==='INCIDENTS'),false);assert.equal(h.penalties.some(x=>x.key==='MAINTENANCE'),true);
h=calculateStoreHealth({...base,dashboard:{...base.dashboard,day:{opening_status:'OPENED',closing_status:'NOT_STARTED'},opening:{blockers:5}},staff:{blocking:3},cold:{blocking:2,mismatch:2},cashOpen:{blocking:2,mismatch:2}});assert.equal(h.penalties.some(x=>['STAFFING','COLD','CASH_OPENING','OPENING'].includes(x.key)),false);
h=calculateStoreHealth({...base,dashboard:{...base.dashboard,day:{opening_status:'OPENED',closing_status:'NOT_STARTED'},cash:{pending:4,recounts:2}}});assert.equal(h.penalties.some(x=>x.key==='CASH_CLOSING'),false);
h=calculateStoreHealth({...base,dashboard:{...base.dashboard,day:{opening_status:'OPENED',closing_status:'IN_PROGRESS'},cash:{pending:4,recounts:2}}});assert.equal(h.penalties.find(x=>x.key==='CASH_CLOSING')?.points,10);
h=calculateStoreHealth({dashboard:{day:{opening_status:'NOT_STARTED',closing_status:'IN_PROGRESS'},incidents:99,criticalIncidents:99,overdueIncidents:99,escalatedIncidents:99,dlc:{expired:99,critical:99,pendingActions:99},commercial:{blocking:99,mismatch:99,pending:99},inventory:{pendingRecounts:99,varianceLines:99},opening:{blockers:99},cash:{pending:99,recounts:99}},staff:{blocking:99},cold:{blocking:99,mismatch:99},cashOpen:{blocking:99,mismatch:99},receipts:{overdue:99,pendingLines:99,dueToday:99},quality:{nonConform:99,temperatureNok:99,rejected:99},maintenance:{openCount:99,critical:99,blocking:99,overdue:99},loss:{blocking:99}});assert.equal(h.score,0);assert.ok(h.penalties.every(x=>x.points>=0));
console.log('StoreOps V1.31 Store Health V2 tests passed');
