import assert from 'node:assert/strict';
process.env.STOREOPS_DB='/tmp/storeops-workforce-v179.db';
const {db}=await import('../db.mjs');
const w=await import('../services/workforce.mjs');
const user=db.prepare(`SELECT * FROM users WHERE id='u-vf'`).get();
const storeId='val-fleuri';
const emp=w.createEmployee({storeId,user,employeeCode:'VF-001',firstName:'Sara',lastName:'Test',roleCode:'CASHIER',contractType:'CDI',contractStart:'2026-09-01'});
assert.equal(emp.display_name,'Sara Test');
assert.equal(emp.store_id,storeId);
assert.equal(w.listEmployees(storeId).length,1);
const shift=w.createShift({storeId,user,employeeId:emp.id,shiftDate:'2026-09-11',startTime:'08:00',endTime:'16:00'});
assert.equal(shift.status,'DRAFT');
w.setShiftStatus({shiftId:shift.id,user,status:'PUBLISHED'});
const snap=w.staffingSnapshotFromPublishedShifts(storeId,'2026-09-11');
assert.equal(snap.source,'STOREOPS_SHIFTS');
assert.equal(snap.lines.length,1);
assert.equal(snap.lines[0].employeeName,'Sara Test');
assert.equal(snap.lines[0].scheduledStart,'08:00');
assert.throws(()=>w.createShift({storeId,user,employeeId:emp.id,shiftDate:'2026-09-11',startTime:'12:00',endTime:'18:00'}),/conflit/i);
const obj=w.createObjective({storeId,user,employeeId:emp.id,title:'Contrôles prix',metricCode:'PRICE_CHECKS',targetValue:10,unit:'contrôles',periodStart:'2026-09-01',periodEnd:'2026-09-30'});
assert.equal(obj.status,'ACTIVE');
const done=w.updateObjectiveProgress({objectiveId:obj.id,user,progressValue:10});
assert.equal(done.status,'COMPLETED');
const ended=w.endEmployeeContract({employeeId:emp.id,user,endDate:'2026-09-15',reason:'Fin contrat test'});
assert.equal(ended.status,'ENDED');
assert.equal(w.listEmployees(storeId).length,0);
assert.equal(w.listEmployees(storeId,{includeEnded:true}).length,1);
console.log('StoreOps workforce lifecycle + shifts + objectives contract OK');
