const KEY='storeops_showcase_loss_v1';
const REASONS=[['BREAKAGE','Casse'],['EXPIRED','Périmé / DLC'],['DAMAGED','Avarie / produit détérioré'],['THEFT','Vol constaté'],['UNKNOWN_SHRINK','Démarque inconnue'],['DONATION','Don'],['RETURN_SUPPLIER','Retour fournisseur'],['INTERNAL_USE','Consommation / usage interne'],['OTHER','Autre']].map(([code,label])=>({code,label}));
const UNITS=['pièce','kg','g','L','barquette','colis'];
const round=v=>Math.round(Number(v||0)*100)/100;
const today=()=>new Date().toISOString().slice(0,10);
const uid=()=>`loss_demo_${Date.now()}_${Math.random().toString(36).slice(2,8)}`;
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{policy:{evidence_threshold_dh:100,approval_threshold_dh:500},records:[]}}catch{return{policy:{evidence_threshold_dh:100,approval_threshold_dh:500},records:[]}}}
function save(s){localStorage.setItem(KEY,JSON.stringify(s))}
function err(message,status=400,details){const e=new Error(message);e.status=status;e.details=details;return e}
async function user(core){return(await core('/api/session')).user}
function access(u,storeId){if(u.role==='ops_director')return true;return u.store_id===storeId}
function manage(u,storeId){return access(u,storeId)&&['store_manager','ops_director'].includes(u.role)}
async function hydrate(row,core){let incident=null;if(row.incident_id)try{incident=await core(`/api/incidents/${row.incident_id}`)}catch{}return{...row,incident}}
function summarySync(storeId,businessDate=today()){const s=load(),rows=s.records.filter(x=>x.store_id===storeId&&x.business_date===businessDate),open=rows.filter(x=>!['POSTED','CANCELLED'].includes(x.status));return{records:rows.length,open:open.length,posted:rows.filter(x=>x.status==='POSTED').length,pendingApproval:rows.filter(x=>x.status==='APPROVAL_REQUIRED').length,pendingEvidence:open.filter(x=>x.requires_evidence&&!x.evidence_satisfied).length,totalQty:round(rows.reduce((a,x)=>a+Number(x.quantity||0),0)),retailValue:round(rows.reduce((a,x)=>a+Number(x.total_retail_value||0),0)),blocking:open.length}}
export function lossShowcaseSummary(storeId,businessDate=today()){return summarySync(storeId,businessDate)}
export function resetLossShowcase(){localStorage.removeItem(KEY)}
export async function mockLossApi(path,options={},core){
 const url=new URL(path,'https://showcase.local'),clean=url.pathname,method=String(options.method||'GET').toUpperCase(),body=options.body?JSON.parse(options.body):{},s=load(),u=await user(core);let m;
 if(clean==='/api/loss/config')return{reasons:REASONS,units:UNITS,policy:s.policy};
 if(clean==='/api/loss/policy'&&(method==='PUT'||method==='PATCH')){if(u.role!=='ops_director')throw err('Réservé au Directeur d’exploitation',403);const e=Number(body.evidenceThreshold),a=Number(body.approvalThreshold);if(!Number.isFinite(e)||!Number.isFinite(a)||e<0||a<e)throw err('Seuils invalides : approbation ≥ preuve ≥ 0.');s.policy={evidence_threshold_dh:e,approval_threshold_dh:a};save(s);return s.policy}
 if((m=clean.match(/^\/api\/stores\/([^/]+)\/losses$/))){const storeId=m[1];if(!access(u,storeId))throw err('Accès interdit à ce magasin.',403);const date=url.searchParams.get('date')||today();if(method==='GET'){const status=(url.searchParams.get('status')||'ALL').toUpperCase(),rows=s.records.filter(x=>x.store_id===storeId&&x.business_date===date&&(status==='ALL'||x.status===status));return{summary:summarySync(storeId,date),items:await Promise.all(rows.sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))).map(x=>hydrate(x,core)))}}
  if(method==='POST'){
   if(!manage(u,storeId))throw err('Réservé au Responsable magasin ou Directeur d’exploitation',403);
   if(body.sourceId){const existing=s.records.find(x=>x.source_type===(body.sourceType||'MANUAL')&&x.source_id===body.sourceId);if(existing)return hydrate(existing,core)}
   const product=await core(`/api/products/${encodeURIComponent(String(body.ean||'').trim())}`);const qty=Number(body.quantity);if(!Number.isFinite(qty)||qty<=0)throw err('Quantité de perte invalide.');if(!REASONS.some(x=>x.code===body.reasonCode))throw err('Motif de perte invalide.');const price=product.price==null?null:Number(product.price),total=Number.isFinite(price)?round(price*qty):null,requiresEvidence=total==null||total>=Number(s.policy.evidence_threshold_dh),requiresApproval=total==null||total>=Number(s.policy.approval_threshold_dh),id=uid(),evidenceSatisfied=body.evidenceAlreadySatisfied===true,row={id,store_id:storeId,business_date:date,ean:product.ean,product_number:product.productNumber||null,product_name:product.name,category:product.category||null,reason_code:body.reasonCode,source_type:body.sourceType||'MANUAL',source_id:body.sourceId||null,quantity:qty,unit:body.unit||'pièce',unit_retail_value:Number.isFinite(price)?price:null,total_retail_value:total,requires_evidence:requiresEvidence?1:0,evidence_satisfied:evidenceSatisfied?1:0,evidence_source_type:body.evidenceSourceType||null,evidence_source_id:body.evidenceSourceId||null,external_evidence:body.externalEvidence||null,status:requiresApproval?'APPROVAL_REQUIRED':'READY_TO_POST',note:body.note||'',incident_id:null,created_by:u.id,created_by_name:u.name,created_at:new Date().toISOString()};
   if(requiresEvidence&&!evidenceSatisfied){const inc=await core(`/api/stores/${storeId}/incidents`,{method:'POST',body:JSON.stringify({title:`Perte à documenter · ${product.name}`,description:`${qty} ${row.unit} · ${REASONS.find(x=>x.code===body.reasonCode)?.label||body.reasonCode}${total==null?'':` · valeur vente estimée ${total} DH`}`,category:'LOSS',criticality:requiresApproval?'HIGH':'MEDIUM',blockingLevel:'STORE_CLOSING',requiresEvidence:true})});await core(`/api/incidents/${inc.id}/actions`,{method:'POST',body:JSON.stringify({title:'Joindre la preuve et documenter la sortie de stock',note:body.note||''})});row.incident_id=inc.id}
   s.records.push(row);save(s);return hydrate(row,core)}
 }
 if((m=clean.match(/^\/api\/losses\/([^/]+)$/))&&method==='GET'){const row=s.records.find(x=>x.id===m[1]);if(!row)throw err('Perte introuvable.',404);if(!access(u,row.store_id))throw err('Accès interdit à ce magasin.',403);return hydrate(row,core)}
 if((m=clean.match(/^\/api\/losses\/([^/]+)\/approve$/))&&method==='POST'){const row=s.records.find(x=>x.id===m[1]);if(!row)throw err('Perte introuvable.',404);if(u.role!=='ops_director')throw err('Validation de perte réservée au Directeur d’exploitation.',403);if(row.status!=='APPROVAL_REQUIRED')throw err('Cette perte ne nécessite pas de validation Direction.',409);row.status='APPROVED';row.approved_by=u.id;row.approved_by_name=u.name;row.approved_at=new Date().toISOString();save(s);return hydrate(row,core)}
 if((m=clean.match(/^\/api\/losses\/([^/]+)\/post$/))&&method==='POST'){const row=s.records.find(x=>x.id===m[1]);if(!row)throw err('Perte introuvable.',404);if(!manage(u,row.store_id))throw err('Réservé au Responsable magasin ou Directeur d’exploitation',403);if(!['READY_TO_POST','APPROVED'].includes(row.status))throw err('La perte doit être prête ou approuvée avant posting.',409);if(row.requires_evidence&&!row.evidence_satisfied){const inc=await core(`/api/incidents/${row.incident_id}`);if(inc.status!=='RESOLVED')throw err('La preuve et l’action corrective doivent être clôturées avant posting.',409,{incidentId:row.incident_id})}row.status='POSTED';row.posted_by=u.id;row.posted_by_name=u.name;row.posted_at=new Date().toISOString();save(s);return{dynamics:{ok:true,simulated:true,lossId:row.id,postedAt:row.posted_at,quantity:-Math.abs(Number(row.quantity))},record:await hydrate(row,core)}}
 throw err('Route démo Démarque inconnue.',404);
}
