const KEY='storeops_cash_showcase_v1';
const clone=v=>JSON.parse(JSON.stringify(v));
const today=()=>new Date().toISOString().slice(0,10);
const now=()=>new Date().toISOString().replace('Z','');
const uid=p=>p+'_'+Math.random().toString(36).slice(2,10);
const round=v=>Math.round(Number(v||0)*100)/100;
const managers={'val-fleuri':'u-vf','trefle':'u-tr','zeraoui':'u-ze','sindibad':'u-si','carita':'u-ca'};
const roles={'u-vf':['store_manager','val-fleuri'],'u-tr':['store_manager','trefle'],'u-ze':['store_manager','zeraoui'],'u-si':['store_manager','sindibad'],'u-ca':['store_manager','carita'],'u-ops':['ops_director',null],'u-emp-vf':['employee','val-fleuri']};
const REASONS=[{code:'COUNT_ERROR',label:'Erreur de comptage'},{code:'CHANGE_FLOAT',label:'Écart de fond de caisse / monnaie'},{code:'CARD_SETTLEMENT',label:'Écart de remise TPE'},{code:'REFUND',label:'Remboursement / annulation'},{code:'SHIFT_TIMING',label:'Décalage de shift / synchronisation'},{code:'CASH_HANDLING',label:'Erreur manipulation espèces'},{code:'OTHER',label:'Autre'}];
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'null')||seed()}catch{return seed()}}
function seed(){const s={policy:{id:'default',tolerance_dh:1,recount_threshold_dh:5,evidence_threshold_dh:20},closings:{}};save(s);return s}
function save(s){localStorage.setItem(KEY,JSON.stringify(s))}
function currentUser(){const id=localStorage.getItem('storeops_user')||'u-vf',r=roles[id]||roles['u-vf'];return{id,role:r[0],store_id:r[1]}}
function access(u,store){if(u.role!=='ops_director'&&u.store_id!==store)throw error('Accès interdit à ce magasin.',403)}
function manage(u,store){access(u,store);if(!['store_manager','ops_director'].includes(u.role))throw error('Réservé au Responsable magasin ou Directeur d’exploitation.',403)}
function director(u){if(u.role!=='ops_director')throw error('Réservé au Directeur d’exploitation.',403)}
function error(message,status=400,details){const e=new Error(message);e.status=status;e.details=details;return e}
function body(options){try{return options?.body?JSON.parse(options.body):{}}catch{return{}}}
function pathOnly(p){return p.split('?')[0]}
function storeSnapshot(store,date){return{sourceKey:`CASH-CLOSING-${store}-${date}`,lines:[{tillCode:'C01',shiftId:`${store.toUpperCase()}-C01-${date}`,cashierName:'Caissier 1',expectedSales:4200,expectedCash:1600,expectedCard:2400,expectedOther:200},{tillCode:'C02',shiftId:`${store.toUpperCase()}-C02-${date}`,cashierName:'Caissier 2',expectedSales:3500,expectedCash:1400,expectedCard:2000,expectedOther:100},{tillCode:'C03',shiftId:`${store.toUpperCase()}-C03-${date}`,cashierName:'Caissier 3',expectedSales:2800,expectedCash:900,expectedCard:1800,expectedOther:100}]}}
function ensure(s,store,date=today()){
 const k=`${store}_${date}`;if(s.closings[k])return s.closings[k];const snap=storeSnapshot(store,date),c={id:uid('cash'),store_id:store,business_date:date,source_key:snap.sourceKey,status:'COUNTING',reviewed_at:null,closed_at:null,lines:snap.lines.map(l=>({id:uid('cashl'),till_code:l.tillCode,shift_id:l.shiftId,cashier_name:l.cashierName,expected_sales:l.expectedSales,expected_cash:l.expectedCash,expected_card:l.expectedCard,expected_other:l.expectedOther,declared_cash:null,card_settlement:null,statement_ok:null,cash_variance:null,card_variance:null,requires_recount:0,recount_cash:null,recount_card:null,final_cash:null,final_card:null,final_cash_variance:null,final_card_variance:null,reason_code:null,note:'',status:'PENDING',counted_at:null,incident:null}))};s.closings[k]=c;save(s);return c
}
function hydrate(c){const lines=clone(c.lines),done=lines.filter(x=>x.status==='COUNTED'),sum=(arr,k)=>round(arr.reduce((a,x)=>a+Number(x[k]||0),0));return{...clone(c),lines,metrics:{lines:lines.length,counted:done.length,pending:lines.filter(x=>x.status==='PENDING').length,recounts:lines.filter(x=>x.status==='RECOUNT').length,expectedSales:sum(lines,'expected_sales'),expectedCash:sum(lines,'expected_cash'),expectedCard:sum(lines,'expected_card'),expectedOther:sum(lines,'expected_other'),finalCash:sum(done,'final_cash'),finalCard:sum(done,'final_card'),cashVariance:sum(done,'final_cash_variance'),cardVariance:sum(done,'final_card_variance')}}}
function summary(s,store,date=today()){const k=`${store}_${date}`,raw=s.closings[k];if(!raw)return{exists:false,status:'NOT_STARTED',lines:0,pending:0,recounts:0,varianceLines:0,blocking:1,cashVariance:0,cardVariance:0};const c=hydrate(raw),tol=Number(s.policy.tolerance_dh),v=c.lines.filter(x=>x.status==='COUNTED'&&Math.max(Math.abs(Number(x.final_cash_variance||0)),Math.abs(Number(x.final_card_variance||0)))>tol).length;return{exists:true,id:c.id,status:c.status,lines:c.metrics.lines,pending:c.metrics.pending,recounts:c.metrics.recounts,varianceLines:v,expectedSales:c.metrics.expectedSales,cashVariance:c.metrics.cashVariance,cardVariance:c.metrics.cardVariance,blocking:['READY','CLOSED'].includes(c.status)?0:1}}
function findLine(s,id){for(const c of Object.values(s.closings)){const line=c.lines.find(x=>x.id===id);if(line)return{c,line}}return null}
export function resetCashShowcase(){localStorage.removeItem(KEY)}
export function cashShowcaseSummary(store,date=today()){return summary(load(),store,date)}
export async function mockCashApi(path,options={}){
 const s=load(),u=currentUser(),p=pathOnly(path),method=(options.method||'GET').toUpperCase(),b=body(options);let m;
 if(p==='/api/cash/config')return{reasons:clone(REASONS),policy:clone(s.policy)};
 if(p==='/api/cash/policy'&&(method==='PUT'||method==='PATCH')){director(u);const t=Number(b.tolerance),r=Number(b.recountThreshold),e=Number(b.evidenceThreshold);if(!Number.isFinite(t)||!Number.isFinite(r)||!Number.isFinite(e)||t<0||r<t||e<r)throw error('Seuils invalides : preuve ≥ recomptage ≥ tolérance ≥ 0.',400);Object.assign(s.policy,{tolerance_dh:t,recount_threshold_dh:r,evidence_threshold_dh:e});save(s);return clone(s.policy)}
 if((m=p.match(/^\/api\/stores\/([^/]+)\/cash-closing$/))){const store=m[1];access(u,store);const c=ensure(s,store);return{summary:summary(s,store),closing:hydrate(c),sync:{ok:true,showcase:true}}}
 if((m=p.match(/^\/api\/stores\/([^/]+)\/cash-closing\/sync$/))){const store=m[1];manage(u,store);const c=ensure(s,store);return{summary:summary(s,store),closing:hydrate(c),sync:{ok:true,showcase:true}}}
 if((m=p.match(/^\/api\/cash\/lines\/([^/]+)\/count$/))){const f=findLine(s,m[1]);if(!f)throw error('Shift caisse introuvable.',404);manage(u,f.c.store_id);if(!['COUNTING','REVIEW'].includes(f.c.status))throw error('Cette clôture caisse n’est plus modifiable.',409);const cash=Number(b.declaredCash),card=Number(b.cardSettlement);if(!Number.isFinite(cash)||cash<0||!Number.isFinite(card)||card<0)throw error('Montants espèces/TPE invalides.',400);if(b.reasonCode&&!REASONS.some(x=>x.code===b.reasonCode))throw error('Motif d’écart invalide.',400);if(b.recount){if(!f.line.requires_recount)throw error('Ce shift ne nécessite pas de recomptage.',409);const cv=round(cash-f.line.expected_cash),tv=round(card-f.line.expected_card),reason=b.reasonCode||f.line.reason_code||null;if((cv!==0||tv!==0)&&!reason)throw error('Un motif est obligatoire pour tout écart final.',409);if(b.statementOk!==true)throw error('Le statement / shift Dynamics doit être contrôlé avant validation.',409);Object.assign(f.line,{recount_cash:cash,recount_card:card,final_cash:cash,final_card:card,final_cash_variance:cv,final_card_variance:tv,statement_ok:1,requires_recount:0,reason_code:reason,note:b.note||f.line.note||'',status:'COUNTED',counted_at:now()})}else{if(f.line.declared_cash!=null)throw error('Le premier comptage existe déjà. Utilise le recomptage.',409);const cv=round(cash-f.line.expected_cash),tv=round(card-f.line.expected_card),max=Math.max(Math.abs(cv),Math.abs(tv)),needs=max>=Number(s.policy.recount_threshold_dh)||b.statementOk!==true;if(!needs&&(cv!==0||tv!==0)&&!b.reasonCode)throw error('Un motif est obligatoire pour tout écart.',409);Object.assign(f.line,{declared_cash:cash,card_settlement:card,statement_ok:b.statementOk===true?1:0,cash_variance:cv,card_variance:tv,requires_recount:needs?1:0,final_cash:needs?null:cash,final_card:needs?null:card,final_cash_variance:needs?null:cv,final_card_variance:needs?null:tv,reason_code:b.reasonCode||null,note:b.note||'',status:needs?'RECOUNT':'COUNTED',counted_at:now()})}if(f.c.status==='COUNTING')f.c.status='REVIEW';save(s);return hydrate(f.c)}
 if((m=p.match(/^\/api\/cash\/([^/]+)\/finalize$/))){const c=Object.values(s.closings).find(x=>x.id===m[1]);if(!c)throw error('Clôture caisse introuvable.',404);manage(u,c.store_id);const h=hydrate(c);if(h.metrics.pending||h.metrics.recounts)throw error(`${h.metrics.pending+h.metrics.recounts} shift(s) restent à compter ou recomptabiliser.`,409);const tol=Number(s.policy.tolerance_dh),ev=Number(s.policy.evidence_threshold_dh),variance=h.lines.filter(x=>Math.max(Math.abs(Number(x.final_cash_variance||0)),Math.abs(Number(x.final_card_variance||0)))>tol);for(const l of variance){const max=Math.max(Math.abs(Number(l.final_cash_variance||0)),Math.abs(Number(l.final_card_variance||0))),raw=c.lines.find(x=>x.id===l.id);raw.incident={id:'cashinc_'+l.id,status:'OPEN',criticality:max>=ev?'CRITICAL':'HIGH',requires_evidence:max>=ev?1:0,title:`Écart caisse · ${l.till_code}`}}c.status='READY';c.reviewed_at=now();save(s);return{closing:hydrate(c),varianceLines:clone(variance)}}
 if((m=p.match(/^\/api\/cash\/([^/]+)\/close$/))){const c=Object.values(s.closings).find(x=>x.id===m[1]);if(!c)throw error('Clôture caisse introuvable.',404);manage(u,c.store_id);if(c.status!=='READY')throw error('La clôture caisse doit être validée avant fermeture.',409);if(c.lines.some(x=>x.incident?.status==='OPEN'))throw error('Des incidents caisse restent ouverts.',409);c.status='CLOSED';c.closed_at=now();save(s);return hydrate(c)}
 throw error('Route Showcase caisse non implémentée : '+p,404);
}
