const KEY='storeops_showcase_state_v6';

const clone=v=>JSON.parse(JSON.stringify(v));
const now=()=>new Date().toISOString().replace('Z','');
const today=()=>new Date().toISOString().slice(0,10);
const uid=p=>p+'_'+Math.random().toString(36).slice(2,9);
const addDays=(n)=>{const d=new Date();d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
const addMinutes=(n)=>{const d=new Date(Date.now()+n*60000);return d.toISOString().replace('Z','')};

const STORES=[
  {id:'val-fleuri',name:'Val Fleuri',code:'VF',opening_time:'08:00',closing_time:'22:00',active:1},
  {id:'trefle',name:'Trèfle',code:'TR',opening_time:'08:00',closing_time:'22:00',active:1},
  {id:'zeraoui',name:'Zeraoui',code:'ZE',opening_time:'08:00',closing_time:'22:00',active:1},
  {id:'sindibad',name:'Sindibad',code:'SI',opening_time:'08:00',closing_time:'22:00',active:1},
  {id:'carita',name:'Carita',code:'CA',opening_time:'08:00',closing_time:'22:00',active:1}
];
const USERS=[
  {id:'u-vf',name:'Responsable Val Fleuri',role:'store_manager',store_id:'val-fleuri',active:1},
  {id:'u-tr',name:'Responsable Trèfle',role:'store_manager',store_id:'trefle',active:1},
  {id:'u-ze',name:'Responsable Zeraoui',role:'store_manager',store_id:'zeraoui',active:1},
  {id:'u-si',name:'Responsable Sindibad',role:'store_manager',store_id:'sindibad',active:1},
  {id:'u-ca',name:'Responsable Carita',role:'store_manager',store_id:'carita',active:1},
  {id:'u-ops',name:'Directeur Exploitation',role:'ops_director',store_id:null,active:1},
  {id:'u-emp-vf',name:'Employé Val Fleuri',role:'employee',store_id:'val-fleuri',active:1}
];
const PRODUCTS={
  '6111040001111':{ean:'6111040001111',name:'Lait frais entier 1L',category:'Frais',price:12.90,stock:24,productNumber:'LAIT1L'},
  '3274080005003':{ean:'3274080005003',name:'Yaourt nature 4x110g',category:'Frais',price:18.50,stock:36,productNumber:'YAOURT4'},
  '3017620422003':{ean:'3017620422003',name:'Nutella 750g',category:'Épicerie',price:64.90,stock:17,productNumber:'NUT750'}
};
const PROFILES=[
  {id:'qp-frais',category:'Frais',label:'Produits frais',temperature_required:1,temp_min:0,temp_max:4,packaging_required:1,appearance_required:1,expiry_required:1,lot_required:0,photo_on_nonconform:1,active:1},
  {id:'qp-surgele',category:'Surgelé',label:'Produits surgelés',temperature_required:1,temp_min:-30,temp_max:-18,packaging_required:1,appearance_required:1,expiry_required:1,lot_required:0,photo_on_nonconform:1,active:1},
  {id:'qp-fl',category:'F&L',label:'Fruits & légumes',temperature_required:0,temp_min:null,temp_max:null,packaging_required:1,appearance_required:1,expiry_required:0,lot_required:0,photo_on_nonconform:1,active:1},
  {id:'qp-epicerie',category:'Épicerie',label:'Épicerie',temperature_required:0,temp_min:null,temp_max:null,packaging_required:1,appearance_required:0,expiry_required:1,lot_required:0,photo_on_nonconform:1,active:1},
  {id:'qp-default',category:'Autre',label:'Contrôle standard',temperature_required:0,temp_min:null,temp_max:null,packaging_required:1,appearance_required:0,expiry_required:0,lot_required:0,photo_on_nonconform:1,active:1}
];
const SLA=[
  {criticality:'CRITICAL',response_minutes:15,resolution_minutes:30,escalation_minutes:15,active:1},
  {criticality:'HIGH',response_minutes:60,resolution_minutes:120,escalation_minutes:90,active:1},
  {criticality:'MEDIUM',response_minutes:120,resolution_minutes:240,escalation_minutes:180,active:1},
  {criticality:'LOW',response_minutes:240,resolution_minutes:480,escalation_minutes:480,active:1}
];

const DLC_DEPARTMENTS=[
 ['Fruits & Légumes',0,1,2],['Boucherie',0,1,2],['Volaille',0,1,2],['Poissonnerie',0,0,1],['Charcuterie / Traiteur',0,1,3],['Fromagerie coupe',1,2,5],['Crémerie / PLS',1,3,7],['Boulangerie / Pâtisserie',0,1,2],['Surgelés',7,15,30],['Épicerie salée',15,30,60],['Épicerie sucrée',15,30,60],['Boissons',15,30,60],['Droguerie / Hygiène-Beauté',15,30,60]
].map(x=>({department:x[0],critical_days:x[1],alert_days:x[2],watch_days:x[3],active:1}));
const DLC_FAMILIES={
 'Fruits & Légumes':['Fruits frais','Légumes frais','Herbes aromatiques','4ème gamme (prédécoupé)','Fruits secs / oléagineux'],
 'Boucherie':['Viande bovine','Viande ovine','Viande hachée','Abats','Préparations bouchères'],
 'Volaille':['Poulet entier','Découpes de volaille','Dinde','Volaille marinée / panée'],
 'Poissonnerie':['Poissons frais entiers','Filets et découpes','Crustacés','Coquillages','Poissons préparés / marinés'],
 'Charcuterie / Traiteur':['Charcuterie sèche','Charcuterie cuite','Charcuterie de volaille','Salades traiteur','Plats cuisinés traiteur','Olives et condiments'],
 'Fromagerie coupe':['Pâtes pressées cuites','Pâtes pressées non cuites','Pâtes molles','Pâtes persillées','Fromages frais / chèvre'],
 'Crémerie / PLS':['Lait frais','Yaourts et desserts lactés','Beurre et crème','Fromages préemballés','Œufs','Jus frais / PLS boissons'],
 'Boulangerie / Pâtisserie':['Pain','Viennoiserie','Pâtisserie fraîche','Panification préemballée'],
 'Surgelés':['Légumes surgelés','Viandes / volailles surgelées','Poissons surgelés','Plats cuisinés surgelés','Glaces et desserts glacés','Panification surgelée'],
 'Épicerie salée':['Conserves','Pâtes / riz / semoule','Huiles et condiments','Sauces','Apéritif salé','Épices'],
 'Épicerie sucrée':['Biscuits et gâteaux','Chocolat et confiserie','Petit-déjeuner (céréales, confitures)','Sucre / farine / aides pâtisserie','Compotes et desserts ambiants'],
 'Boissons':['Eaux','Boissons gazeuses','Jus de fruits ambiants','Boissons chaudes (thé, café)','Sirops'],
 'Droguerie / Hygiène-Beauté':['Produits d’entretien','Hygiène corporelle','Papier / ouate','Bébé','Insecticides']
};
const DLC_ACTIONS=[
 {code:'WITHDRAW_SHELF',label:'Retrait rayon',removesStock:false,proof:false},
 {code:'MARKDOWN',label:'Démarque',removesStock:false,proof:false},
 {code:'SHORT_DATE_PROMO',label:'Mise en avant DLC courte',removesStock:false,proof:false},
 {code:'DESTROY',label:'Destruction (PV établi)',removesStock:true,proof:true},
 {code:'RETURN_SUPPLIER',label:'Retour fournisseur',removesStock:true,proof:true},
 {code:'DONATE',label:'Don / valorisation',removesStock:true,proof:true},
 {code:'FEFO_ROTATE',label:'Rotation FEFO',removesStock:false,proof:false},
 {code:'QUALITY_REVIEW',label:'Isolement / décision qualité',removesStock:false,proof:true},
 {code:'NO_ACTION',label:'Aucune (conforme)',removesStock:false,proof:false}
];

const TASK_DEFS={
 opening:[
  ['Équipe et prise de poste','Présences, responsable d’ouverture et capacité minimale à ouvrir.','MEDIUM','PROCESS'],
  ['Sécurité des accès','Contrôle physique des accès, issues et caméras.','CRITICAL','STORE_OPENING'],
  ['Technique & équipements','Réseau, POS, TPE, imprimantes et balances.','HIGH','PROCESS'],
  ['Chaîne du froid','Relevés chiffrés froid positif et négatif.','CRITICAL','STORE_OPENING'],
  ['Surface de vente','Propreté, remplissage, fraîcheur et FEFO.','MEDIUM','PROCESS'],
  ['Prix, promos & nouveautés','Tous les changements commerciaux du jour sont exécutés.','HIGH','PROCESS'],
  ['Caisses prêtes','Affectation, fonds et shifts opérationnels.','CRITICAL','STORE_OPENING']
 ],
 closing:[
  ['Tour commerce','Surface remise en état et clients sortis.','MEDIUM','PROCESS'],
  ['DLC, frais & froid','DLC critiques traitées et températures de fin de journée.','HIGH','PROCESS'],
  ['Clôture caisses','Shifts, espèces, TPE, CA et statement rapprochés.','CRITICAL','STORE_CLOSING'],
  ['Stock & réceptions','Réceptions postées et anomalies stock identifiées.','HIGH','PROCESS'],
  ['Technique','Équipements et éclairage mis en sécurité.','MEDIUM','PROCESS'],
  ['Sécurité finale','Portes, alarme, réserve et accès sécurisés.','CRITICAL','STORE_CLOSING']
 ]
};
function fieldsFor(group,step){
 const b=(code,label)=>({id:uid('f'),code,label,input_type:'BOOLEAN',required:1,unit:null,min_value:null,max_value:null,options:null,value:null});
 const n=(code,label,min,max,unit='°C')=>({id:uid('f'),code,label,input_type:'NUMBER',required:1,unit,min_value:min,max_value:max,options:null,value:null});
 const t=(code,label,required=0)=>({id:uid('f'),code,label,input_type:'TEXT',required,unit:null,min_value:null,max_value:null,options:null,value:''});
 const m=(code,label)=>({id:uid('f'),code,label,input_type:'MONEY',required:1,unit:'DH',min_value:null,max_value:null,options:null,value:null});
 if(group==='opening'&&step===1)return[b('responsable_present','Responsable d’ouverture présent'),b('caissier_present','Au moins un caissier présent'),t('absence_note','Absences / retards / remplacements')];
 if(group==='opening'&&step===2)return[b('porte_principale','Porte principale sécurisée'),b('porte_secondaire','Porte secondaire sécurisée'),b('issue_secours','Issue de secours accessible'),b('cameras','Caméras opérationnelles')];
 if(group==='opening'&&step===3)return[b('reseau','Réseau opérationnel'),b('pos','POS opérationnels'),b('tpe','TPE opérationnels'),b('imprimantes','Imprimantes tickets opérationnelles'),b('balances','Balances opérationnelles')];
 if(group==='opening'&&step===4)return[n('froid_positif','Température froid positif',0,4),n('froid_negatif','Température surgelés',-30,-18)];
 if(group==='opening'&&step===5)return[b('proprete','Propreté conforme'),b('rayons','Rayons remplis'),b('fraicheur','Fraîcheur F&L conforme'),b('fefo','Rotation FEFO réalisée')];
 if(group==='opening'&&step===6)return[b('prix','Changements de prix traités'),b('promos','Promotions installées / retirées'),b('nouveaux','Nouveaux articles balisés et mis en rayon')];
 if(group==='opening'&&step===7)return[b('affectation','Caissiers affectés aux caisses'),b('fonds','Fonds de caisse déclarés'),b('shifts','Shifts Dynamics ouverts')];
 if(group==='closing'&&step===1)return[b('clients_sortis','Tous les clients sont sortis'),b('surface','Surface remise en état'),b('promos_expirees','Promotions expirées retirées')];
 if(group==='closing'&&step===2)return[b('dlc','DLC critiques traitées'),n('temp_pos','Température froid positif',0,4),n('temp_neg','Température surgelés',-30,-18)];
 if(group==='closing'&&step===3)return[m('ca_commercial','CA commercial'),m('ca_comptable','CA comptable'),m('especes_attendues','Espèces attendues'),m('especes_declarees','Espèces déclarées'),m('tpe_systeme','TPE système'),m('tpe_cloture','TPE clôturé'),b('statement','Statement Dynamics contrôlé')];
 if(group==='closing'&&step===4)return[b('receptions','Toutes les réceptions physiques sont postées'),b('stocks_negatifs','Stocks négatifs contrôlés')];
 if(group==='closing'&&step===5)return[b('postes','Postes / équipements sécurisés'),b('eclairage','Éclairage hors zones nécessaires')];
 return[b('portes','Toutes les portes sécurisées'),b('alarme','Alarme activée'),b('reserve','Réserve sécurisée'),t('transmission','Transmission au lendemain')];
}

function seedTasks(storeId,group,doneCount){
 return TASK_DEFS[group].map((d,i)=>{
  const step=i+1,id=`${storeId}:${group}:${step}`,done=step<=doneCount;
  const fields=fieldsFor(group,step);
  if(done) for(const f of fields){if(f.input_type==='BOOLEAN')f.value=true;else if(f.input_type==='NUMBER')f.value=f.min_value!=null&&f.max_value!=null?(f.min_value+f.max_value)/2:0;else if(f.input_type==='MONEY')f.value=1000;else f.value='RAS';}
  return{id,store_id:storeId,group_name:group,step_order:step,title:d[0],description:d[1],priority:'HIGH',criticality:d[2],blocking_level:d[3],status:done?'COMPLETED':'OPEN',completed_by:done?'u-'+(storeId==='val-fleuri'?'vf':storeId==='trefle'?'tr':storeId==='zeraoui'?'ze':storeId==='sindibad'?'si':'ca'):null,completed_by_name:done?'Responsable '+STORES.find(s=>s.id===storeId).name:null,completed_at:done?now():null,fields};
 });
}
function seed(){
 const states={'val-fleuri':4,'trefle':7,'zeraoui':3,'sindibad':0,'carita':6};
 const days={},tasks={};
 for(const s of STORES){
  const dc=states[s.id];days[s.id]={id:s.id+'_'+today(),store_id:s.id,business_date:today(),opening_status:dc===7?'OPENED':dc>0?'IN_PROGRESS':'NOT_STARTED',closing_status:'NOT_STARTED',opening_owner_id:dc>0?'u-'+(s.id==='val-fleuri'?'vf':s.id==='trefle'?'tr':s.id==='zeraoui'?'ze':s.id==='sindibad'?'si':'ca'):null,closing_owner_id:null,opening_started_at:dc>0?addMinutes(-45):null,closing_started_at:null,handover_reviewed_at:null,handover_reviewed_by:null,opened_at:dc===7?addMinutes(-15):null,closed_at:null};
  tasks[s.id]={opening:seedTasks(s.id,'opening',dc),closing:seedTasks(s.id,'closing',0)};
 }
 const incidents=[
  {id:'inc_demo_z',store_id:'zeraoui',title:'Température chambre froide hors tolérance',description:'Relevé à 7,8°C lors de l’ouverture.',category:'COLD',criticality:'CRITICAL',blocking_level:'STORE_OPENING',status:'OPEN',assigned_to:'u-ze',assigned_to_name:'Responsable Zeraoui',due_at:addMinutes(-20),requires_evidence:1,created_by:'u-ze',created_by_name:'Responsable Zeraoui',created_at:addMinutes(-55),actions:[{id:'ia_z1',title:'Contrôler porte et groupe froid',status:'OPEN',assigned_to:'u-ze',assigned_to_name:'Responsable Zeraoui',due_at:addMinutes(-10),created_at:addMinutes(-50)}],evidence:[],resolution_note:null,resolved_by_name:null,resolved_at:null},
  {id:'inc_demo_vf',store_id:'val-fleuri',title:'Imprimante étiquettes rayon instable',description:'Redémarrage nécessaire ce matin.',category:'TECHNICAL',criticality:'MEDIUM',blocking_level:'NONE',status:'OPEN',assigned_to:'u-vf',assigned_to_name:'Responsable Val Fleuri',due_at:addMinutes(180),requires_evidence:0,created_by:'u-vf',created_by_name:'Responsable Val Fleuri',created_at:addMinutes(-35),actions:[],evidence:[],resolution_note:null,resolved_by_name:null,resolved_at:null},
  {id:'inc_demo_tr',store_id:'trefle',title:'Écart réception fournisseur',description:'2 unités refusées pour emballage endommagé.',category:'RECEPTION',criticality:'HIGH',blocking_level:'NONE',status:'RESOLVED',assigned_to:'u-tr',assigned_to_name:'Responsable Trèfle',due_at:addMinutes(-60),requires_evidence:1,created_by:'u-tr',created_by_name:'Responsable Trèfle',created_at:addMinutes(-180),actions:[{id:'ia_tr1',title:'Isoler les unités',status:'DONE',assigned_to:'u-tr',assigned_to_name:'Responsable Trèfle',completed_by_name:'Responsable Trèfle',completed_at:addMinutes(-120)}],evidence:[],resolution_note:'Unités refusées et fournisseur informé.',resolved_by_name:'Responsable Trèfle',resolved_at:addMinutes(-100)}
 ];
 const dlc=[
  {id:'dlc1',store_id:'val-fleuri',ean:'6111040001111',product_name:'Lait frais entier 1L',expiry_type:'DLC',department:'Crémerie / PLS',family:'Lait frais',expiry_date:addDays(2),quantity:12,original_quantity:12,remaining_quantity:12,unit:'pièce',zone:'Chambre froide',lot_ref:'L2408',comment:'',operational_state:'SELLABLE',source_type:'MANUAL',last_control_at:now(),next_control_at:addMinutes(24),created_by:'u-vf',created_by_name:'Responsable Val Fleuri',created_at:addMinutes(-20),status:'ACTIVE',treatments:[],evidence:[]},
  {id:'dlc2',store_id:'val-fleuri',ean:'3274080005003',product_name:'Yaourt nature 4x110g',expiry_type:'DLC',department:'Crémerie / PLS',family:'Yaourts et desserts lactés',expiry_date:addDays(6),quantity:18,original_quantity:18,remaining_quantity:18,unit:'pièce',zone:'Rayon',lot_ref:'Y2608',comment:'',operational_state:'FEFO',source_type:'MANUAL',last_control_at:now(),next_control_at:addMinutes(-30),created_by:'u-vf',created_by_name:'Responsable Val Fleuri',created_at:addMinutes(-80),status:'ACTIVE',treatments:[{id:'dt1',action_type:'FEFO_ROTATE',quantity:0,quantity_before:18,quantity_after:18,note:'Lot avancé en facing',performed_by_name:'Responsable Val Fleuri',performed_at:addMinutes(-60)}],evidence:[]},
  {id:'dlc4',store_id:'val-fleuri',ean:'3017620422003',product_name:'Nutella 750g',expiry_type:'DDM',department:'Épicerie sucrée',family:'Chocolat et confiserie',expiry_date:addDays(28),quantity:6,original_quantity:6,remaining_quantity:6,unit:'pièce',zone:'Rayon',lot_ref:'N0826',comment:'',operational_state:'SELLABLE',source_type:'MANUAL',last_control_at:now(),next_control_at:addMinutes(48),created_by:'u-vf',created_by_name:'Responsable Val Fleuri',created_at:addMinutes(-15),status:'ACTIVE',treatments:[],evidence:[]},
  {id:'dlc3',store_id:'trefle',ean:'6111040001111',product_name:'Lait frais entier 1L',expiry_type:'DLC',department:'Crémerie / PLS',family:'Lait frais',expiry_date:addDays(1),quantity:8,original_quantity:8,remaining_quantity:8,unit:'pièce',zone:'Chambre froide',lot_ref:'L2508',comment:'',operational_state:'SHORT_DATE',source_type:'MANUAL',last_control_at:now(),next_control_at:addMinutes(4),created_by:'u-tr',created_by_name:'Responsable Trèfle',created_at:addMinutes(-40),status:'ACTIVE',treatments:[{id:'dt3',action_type:'MARKDOWN',quantity:0,quantity_before:8,quantity_after:8,note:'Démarque DLC courte',performed_by_name:'Responsable Trèfle',performed_at:addMinutes(-25)}],evidence:[]},
  {id:'dlc_z',store_id:'zeraoui',ean:'3274080005003',product_name:'Yaourt nature 4x110g',expiry_type:'DLC',department:'Crémerie / PLS',family:'Yaourts et desserts lactés',expiry_date:addDays(-1),quantity:9,original_quantity:9,remaining_quantity:9,unit:'pièce',zone:'Zone non conforme',lot_ref:'YZ2708',comment:'À traiter',operational_state:'ISOLATED',source_type:'MANUAL',last_control_at:addMinutes(-120),next_control_at:addMinutes(-90),created_by:'u-ze',created_by_name:'Responsable Zeraoui',created_at:addMinutes(-120),status:'ACTIVE',treatments:[{id:'dtz',action_type:'WITHDRAW_SHELF',quantity:0,quantity_before:9,quantity_after:9,note:'Retiré du rayon',performed_by_name:'Responsable Zeraoui',performed_at:addMinutes(-100)}],evidence:[]}
 ];
 const receipts=[
  {id:'rcpt_vf',store_id:'val-fleuri',po_number:'PO-10482',vendor:'Centrale Frais',eta:'10:30',status:'EXPECTED',lines:[
   {id:'rl_vf_1',ean:'6111040001111',product_name:'Lait frais entier 1L',category:'Frais',ordered_qty:24,delivered_qty:null,accepted_qty:null,rejected_qty:null,quality_control_id:null},
   {id:'rl_vf_2',ean:'3274080005003',product_name:'Yaourt nature 4x110g',category:'Frais',ordered_qty:36,delivered_qty:null,accepted_qty:null,rejected_qty:null,quality_control_id:null},
   {id:'rl_vf_3',ean:'3017620422003',product_name:'Nutella 750g',category:'Épicerie',ordered_qty:12,delivered_qty:null,accepted_qty:null,rejected_qty:null,quality_control_id:null}
  ]},
  {id:'rcpt_tr',store_id:'trefle',po_number:'PO-20411',vendor:'Fournisseur Épicerie',eta:'14:00',status:'EXPECTED',lines:[{id:'rl_tr_1',ean:'3017620422003',product_name:'Nutella 750g',category:'Épicerie',ordered_qty:18,delivered_qty:18,accepted_qty:18,rejected_qty:0,quality_control_id:'qc_seed_tr'}]}
 ];
 const qualityControls=[
  {id:'qc_seed_tr',store_id:'trefle',context:'Réception',po_number:'PO-20411',ean:'3017620422003',product_name:'Nutella 750g',category:'Épicerie',ordered_qty:18,delivered_qty:18,accepted_qty:18,rejected_qty:0,temperature:null,temperature_status:'NA',packaging_status:'OK',appearance_status:'NA',expiry_date:addDays(120),lot_ref:'NUT24',decision:'ACCEPT',comment:'',controlled_by:'u-tr',controlled_by_name:'Responsable Trèfle',created_at:addMinutes(-90)}
 ];
 const inventoryPolicy={id:'default',recount_qty_threshold:2,incident_qty_threshold:5};
 const inventorySessions=[
  {id:'inv_vf_demo',store_id:'val-fleuri',business_date:today(),inventory_type:'CYCLE',zone:'PLS & Épicerie',comment:'Contrôle tournant du matin',status:'REVIEW',created_by:'u-vf',created_by_name:'Responsable Val Fleuri',created_at:addMinutes(-70),reviewed_by:null,reviewed_at:null,posted_by:null,posted_at:null,lines:[
    {id:'invl_vf_nut',ean:'3017620422003',product_number:'NUT750',product_name:'Nutella 750g',category:'Épicerie',theoretical_qty:17,count1_qty:16,count1_by:'u-vf',count1_by_name:'Responsable Val Fleuri',count1_at:addMinutes(-55),variance1:-1,requires_recount:0,count2_qty:null,count2_by:null,count2_at:null,final_qty:16,final_variance:-1,reason_code:'SHRINK',note:'1 unité manquante à investiguer',status:'COUNTED'},
    {id:'invl_vf_lait',ean:'6111040001111',product_number:'LAIT1L',product_name:'Lait frais entier 1L',category:'Frais',theoretical_qty:24,count1_qty:20,count1_by:'u-vf',count1_by_name:'Responsable Val Fleuri',count1_at:addMinutes(-45),variance1:-4,requires_recount:1,count2_qty:null,count2_by:null,count2_at:null,final_qty:null,final_variance:null,reason_code:null,note:'',status:'RECOUNT'}
  ]},
  {id:'inv_tr_hist',store_id:'trefle',business_date:addDays(-1),inventory_type:'TARGETED',zone:'Réserve',comment:'Contrôle après réception',status:'POSTED',created_by:'u-tr',created_by_name:'Responsable Trèfle',created_at:addMinutes(-900),reviewed_by:'u-tr',reviewed_by_name:'Responsable Trèfle',reviewed_at:addMinutes(-850),posted_by:'u-tr',posted_by_name:'Responsable Trèfle',posted_at:addMinutes(-840),lines:[
    {id:'invl_tr_nut',ean:'3017620422003',product_number:'NUT750',product_name:'Nutella 750g',category:'Épicerie',theoretical_qty:18,count1_qty:18,count1_by:'u-tr',count1_by_name:'Responsable Trèfle',count1_at:addMinutes(-880),variance1:0,requires_recount:0,count2_qty:null,count2_by:null,count2_at:null,final_qty:18,final_variance:0,reason_code:null,note:'',status:'COUNTED'}
  ]}
 ];
 const handovers=[
  {id:'ho_vf_1',store_id:'val-fleuri',source_business_date:addDays(-1),target_business_date:today(),title:'TPE caisse 2 à surveiller',description:'Deux pertes de connexion hier soir. Vérifier avant rush et remonter si récidive.',category:'CASH',priority:'HIGH',blocking_opening:0,status:'OPEN',created_by:'u-vf',created_by_name:'Responsable Val Fleuri',created_at:addMinutes(-720),acknowledged_by:null,acknowledged_at:null,resolved_by:null,resolved_at:null,resolution_note:null},
  {id:'ho_tr_1',store_id:'trefle',source_business_date:addDays(-1),target_business_date:today(),title:'Réception fournisseur à finaliser',description:'Vérifier le bon de livraison papier avec le contrôle qualité déjà saisi.',category:'STOCK',priority:'NORMAL',blocking_opening:0,status:'ACKNOWLEDGED',created_by:'u-tr',created_by_name:'Responsable Trèfle',created_at:addMinutes(-650),acknowledged_by:'u-tr',acknowledged_by_name:'Responsable Trèfle',acknowledged_at:addMinutes(-25),resolved_by:null,resolved_at:null,resolution_note:null},
  {id:'ho_ze_1',store_id:'zeraoui',source_business_date:addDays(-1),target_business_date:today(),title:'Chambre froide : accès à sécuriser',description:'Le ferme-porte reste instable après intervention. Ne pas ouvrir le magasin sans contrôle du Responsable.',category:'COLD',priority:'CRITICAL',blocking_opening:1,status:'OPEN',created_by:'u-ze',created_by_name:'Responsable Zeraoui',created_at:addMinutes(-700),acknowledged_by:null,acknowledged_at:null,resolved_by:null,resolved_at:null,resolution_note:null}
 ];
 return{version:6,stores:clone(STORES),users:clone(USERS),days,tasks,incidents,handovers,inventoryPolicy,inventorySessions,dlc,dlcThresholds:clone(DLC_DEPARTMENTS),receipts,qualityControls,profiles:clone(PROFILES),sla:clone(SLA),audit:[]};
}
function load(){try{const s=JSON.parse(localStorage.getItem(KEY)||'null');if(s?.version===6)return s}catch{}const s=seed();save(s);return s}
function save(s){localStorage.setItem(KEY,JSON.stringify(s))}
function user(s){const id=localStorage.getItem('storeops_user')||'u-vf';return s.users.find(x=>x.id===id)||s.users[0]}
function assertStore(u,storeId){if(u.role!=='ops_director'&&u.store_id!==storeId)throw err('Accès interdit à ce magasin.',403)}
function assertManage(u,storeId){assertStore(u,storeId);if(!['store_manager','ops_director'].includes(u.role))throw err('Réservé au Responsable magasin ou Directeur d’exploitation.',403)}
function assertDirector(u){if(u.role!=='ops_director')throw err('Réservé au Directeur d’exploitation.',403)}
function err(message,status=400,details){const e=new Error(message);e.status=status;e.details=details;return e}
function body(options){try{return options?.body?JSON.parse(options.body):{}}catch{return{}}}
function pathOnly(path){return path.split('?')[0]}
function qs(path){return new URL(path,'https://showcase.local').searchParams}
function dlcRisk(s,r){const d=Math.floor((new Date(r.expiry_date+'T23:59:59')-new Date())/86400000),t=s.dlcThresholds.find(x=>x.department===r.department)||{critical_days:1,alert_days:3,watch_days:7};let stage;if(d<0)stage=r.expiry_type==='DDM'?'DDM_PASSED':'EXPIRED';else if(d<=t.critical_days)stage='CRITICAL';else if(d<=t.alert_days)stage='ALERT';else if(d<=t.watch_days)stage='WATCH';else stage='CONFORM';const map={EXPIRED:{label:'PÉRIMÉ',severity:'CRITICAL',action:'Retrait immédiat du rayon · isolement · destruction/retour/don selon décision, avec preuve.'},DDM_PASSED:{label:'DDM DÉPASSÉE',severity:'CRITICAL',action:'Isoler le lot et appliquer la décision qualité définie par l’enseigne.'},CRITICAL:{label:'CRITIQUE',severity:'CRITICAL',action:'Traitement le jour même : retrait/démarque/disposition selon décision du responsable.'},ALERT:{label:'ALERTE',severity:'HIGH',action:'Démarque ou mise en avant DLC courte · contrôle quotidien jusqu’à écoulement.'},WATCH:{label:'À SURVEILLER',severity:'MEDIUM',action:'Rotation FEFO · avancer le lot en facing · recontrôler.'},CONFORM:{label:'CONFORME',severity:'LOW',action:'Aucune action corrective · poursuite du contrôle périodique.'}};const allowedActions={EXPIRED:['WITHDRAW_SHELF','DESTROY','RETURN_SUPPLIER','DONATE','QUALITY_REVIEW'],DDM_PASSED:['QUALITY_REVIEW','WITHDRAW_SHELF','DESTROY','RETURN_SUPPLIER','DONATE'],CRITICAL:['WITHDRAW_SHELF','MARKDOWN','SHORT_DATE_PROMO','DESTROY','RETURN_SUPPLIER','DONATE','QUALITY_REVIEW'],ALERT:['MARKDOWN','SHORT_DATE_PROMO','FEFO_ROTATE','WITHDRAW_SHELF','RETURN_SUPPLIER'],WATCH:['FEFO_ROTATE','MARKDOWN','SHORT_DATE_PROMO','NO_ACTION'],CONFORM:['NO_ACTION','FEFO_ROTATE']}[stage]||[];return{stage,daysRemaining:d,threshold:t,allowedActions,...map[stage]}}
function dlcHydrate(s,r){const x={...r,original_quantity:Number(r.original_quantity??r.quantity??0),remaining_quantity:Number(r.remaining_quantity??r.quantity??0),unit:r.unit||'pièce',expiry_type:r.expiry_type||'DLC',department:r.department||null,family:r.family||null,operational_state:r.operational_state||'SELLABLE',treatments:r.treatments||[],evidence:r.evidence||[]};x.quantity=x.remaining_quantity;x.risk=dlcRisk(s,x);x.overdue_control=x.status==='ACTIVE'&&x.next_control_at&&new Date(x.next_control_at)<new Date();const latest=x.treatments?.[0]?.action_type||null,remaining=x.remaining_quantity,partialDisposal=['DESTROY','RETURN_SUPPLIER','DONATE'].includes(latest)&&remaining>0;const sat={EXPIRED:x.operational_state==='DISPOSED',DDM_PASSED:['ISOLATED','DISPOSED'].includes(x.operational_state)&&['QUALITY_REVIEW','WITHDRAW_SHELF','DESTROY','RETURN_SUPPLIER','DONATE'].includes(latest),CRITICAL:!partialDisposal&&['SHORT_DATE','ISOLATED','DISPOSED'].includes(x.operational_state)&&['MARKDOWN','SHORT_DATE_PROMO','WITHDRAW_SHELF','QUALITY_REVIEW','DESTROY','RETURN_SUPPLIER','DONATE'].includes(latest),ALERT:!partialDisposal&&['SHORT_DATE','FEFO','ISOLATED','DISPOSED'].includes(x.operational_state)&&['MARKDOWN','SHORT_DATE_PROMO','FEFO_ROTATE','WITHDRAW_SHELF','RETURN_SUPPLIER'].includes(latest),WATCH:['FEFO','SHORT_DATE','ISOLATED','DISPOSED'].includes(x.operational_state)&&['FEFO_ROTATE','MARKDOWN','SHORT_DATE_PROMO','NO_ACTION'].includes(latest),CONFORM:true}[x.risk.stage]??false;x.action_satisfied=sat;x.pending_action=x.status==='ACTIVE'&&x.risk.stage!=='CONFORM'&&(!sat||x.overdue_control);return x}
function dlcSummaryMock(s,storeId){const rows=s.dlc.filter(x=>x.store_id===storeId&&x.status==='ACTIVE').map(x=>dlcHydrate(s,x)),by={};for(const x of rows)by[x.risk.stage]=(by[x.risk.stage]||0)+1;return{active:rows.length,expired:(by.EXPIRED||0)+(by.DDM_PASSED||0),critical:by.CRITICAL||0,alert:by.ALERT||0,watch:by.WATCH||0,conform:by.CONFORM||0,pendingActions:rows.filter(x=>x.pending_action).length,overdueControls:rows.filter(x=>x.overdue_control).length,quantityAtRisk:rows.filter(x=>['EXPIRED','DDM_PASSED','CRITICAL','ALERT'].includes(x.risk.stage)).reduce((a,x)=>a+x.remaining_quantity,0)}}
function audit(s,storeId,u,action,entityId,entityType='GENERIC'){s.audit.unshift({id:uid('a'),store_id:storeId,action,entity_type:entityType,entity_id:entityId,user_id:u.id,actor:u.name,created_at:now()});s.audit=s.audit.slice(0,100)}
function handoverHydrate(s,h){return{...h,created_by_name:h.created_by_name||s.users.find(u=>u.id===h.created_by)?.name||null,acknowledged_by_name:h.acknowledged_by_name||s.users.find(u=>u.id===h.acknowledged_by)?.name||null,resolved_by_name:h.resolved_by_name||s.users.find(u=>u.id===h.resolved_by)?.name||null}}
function handoverListMock(s,storeId,businessDate=today(),status='ACTIVE'){let rows=s.handovers.filter(x=>x.store_id===storeId);if(status!=='ALL')rows=rows.filter(x=>x.target_business_date<=businessDate&&['OPEN','ACKNOWLEDGED'].includes(x.status));return rows.map(x=>handoverHydrate(s,x)).sort((a,b)=>({CRITICAL:0,HIGH:1,NORMAL:2,LOW:3}[a.priority]-({CRITICAL:0,HIGH:1,NORMAL:2,LOW:3}[b.priority]))||a.target_business_date.localeCompare(b.target_business_date))}
function handoverStatsMock(s,storeId,businessDate=today()){const rows=handoverListMock(s,storeId,businessDate,'ACTIVE');return{pending:rows.length,critical:rows.filter(x=>x.priority==='CRITICAL').length,high:rows.filter(x=>['HIGH','CRITICAL'].includes(x.priority)).length,blocking:rows.filter(x=>x.blocking_opening&&x.status!=='RESOLVED').length,unacknowledged:rows.filter(x=>x.status==='OPEN').length,overdue:rows.filter(x=>x.target_business_date<businessDate).length}}
function dayCycleMock(day){const minutes=(a,b)=>{if(!a||!b)return null;return Math.max(0,Math.round((new Date(String(b).replace(' ','T')+'Z')-new Date(String(a).replace(' ','T')+'Z'))/60000))};return{openingDurationMinutes:minutes(day.opening_started_at,day.opened_at),closingDurationMinutes:minutes(day.closing_started_at,day.closed_at),handoverReviewed:!!day.handover_reviewed_at}}
function process(s,storeId,group){const rows=s.tasks[storeId][group],done=rows.filter(x=>x.status==='COMPLETED').length,current=rows.find(x=>x.status!=='COMPLETED')||null,blockers=rows.filter(x=>x.blocking_level!=='NONE'&&x.status!=='COMPLETED').length;return{total:rows.length,done,percent:Math.round(done*100/rows.length),blockers,currentStep:current?.step_order||null,currentTaskId:current?.id||null,currentTitle:current?.title||null}}
const INVENTORY_REASONS=[{code:'COUNT_ERROR',label:'Erreur de comptage'},{code:'BREAKAGE',label:'Casse / avarie'},{code:'SHRINK',label:'Démarque inconnue / perte'},{code:'RECEIPT',label:'Écart de réception'},{code:'TRANSFER',label:'Transfert en attente / mal imputé'},{code:'SALE_TIMING',label:'Décalage vente / synchronisation'},{code:'OTHER',label:'Autre'}];
function inventorySessionHydrate(s,inv){const lines=(inv.lines||[]).map(l=>({...l,count1_by_name:l.count1_by_name||s.users.find(u=>u.id===l.count1_by)?.name||null,count2_by_name:l.count2_by_name||s.users.find(u=>u.id===l.count2_by)?.name||null,variance_abs:l.final_variance==null?null:Math.abs(Number(l.final_variance))})),pending=lines.filter(x=>x.status!=='COUNTED').length,recounts=lines.filter(x=>x.status==='RECOUNT').length,varianceLines=lines.filter(x=>x.final_variance!=null&&Math.abs(Number(x.final_variance))>0),abs=varianceLines.reduce((a,x)=>a+Math.abs(Number(x.final_variance)),0);return{...inv,lines,metrics:{lines:lines.length,counted:lines.length-pending,pending,recounts,varianceLines:varianceLines.length,absoluteVarianceQty:abs}}}
function inventoryListMock(s,storeId,status='ALL'){let rows=s.inventorySessions.filter(x=>x.store_id===storeId);if(status!=='ALL')rows=rows.filter(x=>x.status===status);return rows.map(x=>inventorySessionHydrate(s,x)).sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at)))}
function inventorySummaryMock(s,storeId){const all=inventoryListMock(s,storeId,'ALL'),active=all.filter(x=>!['POSTED','CANCELLED'].includes(x.status));return{openSessions:active.length,readyToPost:active.filter(x=>x.status==='READY_TO_POST').length,pendingRecounts:active.reduce((a,x)=>a+x.metrics.recounts,0),varianceLines:active.reduce((a,x)=>a+x.metrics.varianceLines,0),absoluteVarianceQty:active.reduce((a,x)=>a+x.metrics.absoluteVarianceQty,0)}}
function findInventoryLine(s,id){for(const inv of s.inventorySessions){const line=(inv.lines||[]).find(x=>x.id===id);if(line)return{inv,line}}return null}
function incidentHydrate(s,i){const ass=s.users.find(u=>u.id===i.assigned_to);const actions=(i.actions||[]).map(a=>({...a,assigned_to_name:a.assigned_to_name||s.users.find(u=>u.id===a.assigned_to)?.name||null}));const ev=i.evidence||[];return{...i,assigned_to_name:i.assigned_to_name||ass?.name||null,actions,evidence:ev,open_actions:actions.filter(a=>a.status==='OPEN').length,is_overdue:i.status==='OPEN'&&i.due_at&&new Date(i.due_at)<new Date(),sla:{state:i.status==='RESOLVED'?'MET':i.due_at&&new Date(i.due_at)<new Date()?'BREACHED':'ON_TRACK'},escalation_level:i.status==='OPEN'&&i.due_at&&new Date(i.due_at)<new Date()?'OPS_DIRECTOR':'NONE'}}
function incidentStats(s,storeId){const rows=s.incidents.filter(i=>i.store_id===storeId).map(i=>incidentHydrate(s,i)),open=rows.filter(i=>i.status==='OPEN');return{open:open.length,critical:open.filter(i=>i.criticality==='CRITICAL').length,overdue:open.filter(i=>i.is_overdue).length,escalated:open.filter(i=>i.escalation_level==='OPS_DIRECTOR').length,watch:0,resolvedToday:rows.filter(i=>i.status==='RESOLVED').length}}
function createIncident(s,storeId,u,b){const pol=s.sla.find(x=>x.criticality===(b.criticality||'MEDIUM'))||s.sla[2];const i={id:uid('inc'),store_id:storeId,title:b.title||'Incident',description:b.description||'',category:b.category||'OPERATIONS',criticality:b.criticality||'MEDIUM',blocking_level:b.blockingLevel||'NONE',status:'OPEN',assigned_to:b.assignedTo||('u-'+(storeId==='val-fleuri'?'vf':storeId==='trefle'?'tr':storeId==='zeraoui'?'ze':storeId==='sindibad'?'si':'ca')),due_at:b.dueAt||addMinutes(pol.resolution_minutes),requires_evidence:b.requiresEvidence?1:0,created_by:u.id,created_by_name:u.name,created_at:now(),actions:[],evidence:[],resolution_note:null,resolved_at:null};s.incidents.unshift(i);audit(s,storeId,u,'INCIDENT_CREATED',i.id);return incidentHydrate(s,i)}
function profile(s,category){return s.profiles.find(p=>p.category===category)||s.profiles.find(p=>p.category==='Autre')}
function qualityIssues(p,b){const issues=[];if(p.temperature_required){if(b.temperature==null||b.temperature==='')issues.push('Température obligatoire');else if(Number(b.temperature)<p.temp_min||Number(b.temperature)>p.temp_max)issues.push(`Température hors tolérance ${p.temp_min} à ${p.temp_max} °C`)}if(p.packaging_required&&b.packagingStatus==='NOK')issues.push('Conditionnement non conforme');if(p.appearance_required&&b.appearanceStatus==='NOK')issues.push('Aspect / fraîcheur non conforme');if(p.expiry_required&&!b.expiryDate)issues.push('DLC obligatoire');return issues}

export function resetShowcase(){localStorage.removeItem(KEY);localStorage.removeItem('storeops_user');return load()}
export function isShowcase(){return (window.STOREOPS_CONFIG?.mode||'showcase')==='showcase'||!window.STOREOPS_CONFIG?.apiBase}

export async function mockApi(path,options={}){
 const s=load(),u=user(s),method=(options.method||'GET').toUpperCase(),p=pathOnly(path),q=qs(path),b=body(options);let m;
 if(p==='/api/health')return{ok:true,service:'StoreOps Showcase',version:'1.7-showcase',authMode:'demo',dynamicsMode:'simulated',showcase:true};
 if(p==='/api/session')return{user:clone(u),authMode:'demo',availableDemoUsers:clone(s.users)};
 if(p==='/api/config')return{authMode:'demo',dynamicsMode:'simulated',version:'1.7-showcase',showcase:true};
 if(p==='/api/dlc/config'&&method==='GET')return{departments:clone(s.dlcThresholds.map(x=>({...x,families:DLC_FAMILIES[x.department]||[]}))),units:['kg','g','L','pièce','barquette','colis'],expiryTypes:[{code:'DLC',label:'DLC'},{code:'DDM',label:'DDM'}],actions:clone(DLC_ACTIONS)};
 if((m=p.match(/^\/api\/dlc\/thresholds\/(.+)$/))){assertDirector(u);const dept=decodeURIComponent(m[1]),x=s.dlcThresholds.find(y=>y.department===dept);if(!x)throw err('Rayon inconnu',404);const c=Number(b.criticalDays),a=Number(b.alertDays),w=Number(b.watchDays);if(c<0||a<c||w<a)throw err('Seuils invalides : CRITIQUE ≤ ALERTE ≤ À SURVEILLER.',400);Object.assign(x,{critical_days:c,alert_days:a,watch_days:w});save(s);return clone(x)}
 if(p==='/api/stores')return clone(u.role==='ops_director'?s.stores:s.stores.filter(x=>x.id===u.store_id));
 if((m=p.match(/^\/api\/stores\/([^/]+)\/handover$/))){const storeId=m[1];assertStore(u,storeId);if(method==='GET'){const businessDate=q.get('date')||today(),st=(q.get('status')||'ACTIVE').toUpperCase();return{stats:handoverStatsMock(s,storeId,businessDate),items:clone(handoverListMock(s,storeId,businessDate,st))}}assertManage(u,storeId);if(!b.title?.trim())throw err('Sujet de passation obligatoire.',400);const h={id:uid('ho'),store_id:storeId,source_business_date:b.sourceBusinessDate||today(),target_business_date:b.targetDate||addDays(1),title:b.title.trim(),description:b.description||'',category:b.category||'OPERATIONS',priority:['LOW','NORMAL','HIGH','CRITICAL'].includes(b.priority)?b.priority:'NORMAL',blocking_opening:b.blockingOpening?1:0,status:'OPEN',created_by:u.id,created_by_name:u.name,created_at:now(),acknowledged_by:null,acknowledged_at:null,resolved_by:null,resolved_at:null,resolution_note:null};s.handovers.unshift(h);const day=s.days[storeId];if(day&&day.business_date===h.source_business_date){day.handover_reviewed_at=null;day.handover_reviewed_by=null}audit(s,storeId,u,'HANDOVER_CREATED',h.id,'HANDOVER');save(s);return clone(handoverHydrate(s,h))}
 if((m=p.match(/^\/api\/handover\/([^/]+)\/acknowledge$/))){const h=s.handovers.find(x=>x.id===m[1]);if(!h)throw err('Passation introuvable.',404);assertManage(u,h.store_id);if(!['RESOLVED','CANCELLED'].includes(h.status)){h.status='ACKNOWLEDGED';h.acknowledged_by=u.id;h.acknowledged_by_name=u.name;h.acknowledged_at=now();audit(s,h.store_id,u,'HANDOVER_ACKNOWLEDGED',h.id,'HANDOVER');save(s)}return clone(handoverHydrate(s,h))}
 if((m=p.match(/^\/api\/handover\/([^/]+)\/resolve$/))){const h=s.handovers.find(x=>x.id===m[1]);if(!h)throw err('Passation introuvable.',404);assertManage(u,h.store_id);if(!b.note?.trim())throw err('Note de résolution obligatoire.',400);h.status='RESOLVED';h.resolved_by=u.id;h.resolved_by_name=u.name;h.resolved_at=now();h.resolution_note=b.note||'';audit(s,h.store_id,u,'HANDOVER_RESOLVED',h.id,'HANDOVER');save(s);return clone(handoverHydrate(s,h))}
 if((m=p.match(/^\/api\/stores\/([^/]+)\/handover\/review-closing$/))){const storeId=m[1];assertManage(u,storeId);const day=s.days[storeId];day.handover_reviewed_at=now();day.handover_reviewed_by=u.id;audit(s,storeId,u,'HANDOVER_REVIEWED',day.id,'STORE_DAY');save(s);return{day:clone(day),stats:handoverStatsMock(s,storeId,day.business_date)}}
 if(p==='/api/inventory/config')return{types:[{code:'CYCLE',label:'Inventaire tournant'},{code:'TARGETED',label:'Inventaire ciblé'},{code:'FULL',label:'Inventaire complet'}],reasons:clone(INVENTORY_REASONS),policy:clone(s.inventoryPolicy)};
 if(p==='/api/inventory/policy'&&(method==='PUT'||method==='PATCH')){assertDirector(u);const r=Number(b.recountThreshold),i=Number(b.incidentThreshold);if(!Number.isFinite(r)||!Number.isFinite(i)||r<0||i<r)throw err('Seuils invalides : incident ≥ recomptage ≥ 0.',400);Object.assign(s.inventoryPolicy,{recount_qty_threshold:r,incident_qty_threshold:i,updated_by:u.id,updated_at:now()});save(s);return clone(s.inventoryPolicy)}
 if((m=p.match(/^\/api\/stores\/([^/]+)\/inventory$/))){const storeId=m[1];assertStore(u,storeId);if(method==='GET'){const st=(q.get('status')||'ALL').toUpperCase();return{summary:inventorySummaryMock(s,storeId),items:clone(inventoryListMock(s,storeId,st))}}assertManage(u,storeId);if(!['CYCLE','TARGETED','FULL'].includes(b.type))throw err('Type d’inventaire invalide.',400);const inv={id:uid('inv'),store_id:storeId,business_date:today(),inventory_type:b.type,zone:b.zone||'',comment:b.comment||'',status:'COUNTING',created_by:u.id,created_by_name:u.name,created_at:now(),reviewed_by:null,reviewed_at:null,posted_by:null,posted_at:null,lines:[]};s.inventorySessions.unshift(inv);audit(s,storeId,u,'INVENTORY_STARTED',inv.id,'INVENTORY_SESSION');save(s);return clone(inventorySessionHydrate(s,inv))}
 if((m=p.match(/^\/api\/inventory\/([^/]+)$/))&&method==='GET'){const inv=s.inventorySessions.find(x=>x.id===m[1]);if(!inv)throw err('Inventaire introuvable',404);assertStore(u,inv.store_id);return clone(inventorySessionHydrate(s,inv))}
 if((m=p.match(/^\/api\/inventory\/([^/]+)\/lines$/))&&method==='POST'){const inv=s.inventorySessions.find(x=>x.id===m[1]);if(!inv)throw err('Inventaire introuvable',404);assertManage(u,inv.store_id);const product=PRODUCTS[b.ean];if(!product)throw err('Article introuvable Dynamics',404);if(inv.lines.some(x=>x.ean===b.ean))return clone(inv.lines.find(x=>x.ean===b.ean));const line={id:uid('invl'),ean:b.ean,product_number:product.productNumber||null,product_name:product.name,category:product.category,theoretical_qty:Number(product.stock),count1_qty:null,count1_by:null,count1_at:null,variance1:null,requires_recount:0,count2_qty:null,count2_by:null,count2_at:null,final_qty:null,final_variance:null,reason_code:null,note:'',status:'TO_COUNT'};inv.lines.push(line);audit(s,inv.store_id,u,'INVENTORY_LINE_ADDED',line.id,'INVENTORY_LINE');save(s);return clone(line)}
 if((m=p.match(/^\/api\/inventory\/lines\/([^/]+)\/count$/))&&method==='POST'){const found=findInventoryLine(s,m[1]);if(!found)throw err('Ligne inventaire introuvable',404);const {inv,line}=found;assertManage(u,inv.store_id);const qty=Number(b.quantity);if(!Number.isFinite(qty)||qty<0)throw err('Quantité comptée invalide.',400);if(b.reasonCode&&!INVENTORY_REASONS.some(x=>x.code===b.reasonCode))throw err('Motif d’écart invalide.',400);if(b.recount){if(!line.requires_recount)throw err('Cette ligne ne nécessite pas de recomptage.',409);const v=qty-Number(line.theoretical_qty),finalReason=b.reasonCode||line.reason_code||null;if(v!==0&&!finalReason)throw err('Un motif est obligatoire pour tout écart final.',409);Object.assign(line,{count2_qty:qty,count2_by:u.id,count2_by_name:u.name,count2_at:now(),final_qty:qty,final_variance:v,reason_code:finalReason,note:b.note||line.note||'',requires_recount:0,status:'COUNTED'});audit(s,inv.store_id,u,'INVENTORY_RECOUNTED',line.id,'INVENTORY_LINE')}else{if(line.count1_qty!=null)throw err('Le premier comptage existe déjà.',409);const v=qty-Number(line.theoretical_qty),needs=Math.abs(v)>=Number(s.inventoryPolicy.recount_qty_threshold);if(!needs&&v!==0&&!b.reasonCode)throw err('Un motif est obligatoire pour tout écart.',409);Object.assign(line,{count1_qty:qty,count1_by:u.id,count1_by_name:u.name,count1_at:now(),variance1:v,requires_recount:needs?1:0,final_qty:needs?null:qty,final_variance:needs?null:v,reason_code:b.reasonCode||null,note:b.note||'',status:needs?'RECOUNT':'COUNTED'});audit(s,inv.store_id,u,needs?'INVENTORY_RECOUNT_REQUIRED':'INVENTORY_COUNTED',line.id,'INVENTORY_LINE')}if(inv.status==='COUNTING')inv.status='REVIEW';save(s);return clone(inventorySessionHydrate(s,inv))}
 if((m=p.match(/^\/api\/inventory\/([^/]+)\/finalize$/))&&method==='POST'){const inv=s.inventorySessions.find(x=>x.id===m[1]);if(!inv)throw err('Inventaire introuvable',404);assertManage(u,inv.store_id);const h=inventorySessionHydrate(s,inv);if(!h.lines.length)throw err('Ajoute au moins un article avant validation.',409);if(h.metrics.pending)throw err(h.metrics.pending+' ligne(s) restent à compter ou recomptabiliser.',409);const missing=h.lines.filter(x=>Number(x.final_variance)!==0&&!x.reason_code);if(missing.length)throw err('Tout écart final doit avoir un motif.',409);inv.status='READY_TO_POST';inv.reviewed_by=u.id;inv.reviewed_by_name=u.name;inv.reviewed_at=now();const high=h.lines.filter(x=>Math.abs(Number(x.final_variance||0))>=Number(s.inventoryPolicy.incident_qty_threshold));for(const line of high){if(!s.incidents.some(i=>i.source_type==='INVENTORY_LINE'&&i.source_id===line.id&&i.status==='OPEN')){const inc=createIncident(s,inv.store_id,u,{title:'Écart inventaire · '+line.product_name,description:'Stock théorique '+line.theoretical_qty+' · compté '+line.final_qty+' · écart '+line.final_variance+' · motif '+(line.reason_code||'—'),category:'STOCK',criticality:Math.abs(Number(line.final_variance))>=Number(s.inventoryPolicy.incident_qty_threshold)*2?'CRITICAL':'HIGH',requiresEvidence:true});inc.source_type='INVENTORY_LINE';inc.source_id=line.id;inc.actions.push({id:uid('ia'),title:'Analyser et documenter l’écart de stock',status:'OPEN',assigned_to:u.id,assigned_to_name:u.name,created_at:now()})}}audit(s,inv.store_id,u,'INVENTORY_READY_TO_POST',inv.id,'INVENTORY_SESSION');save(s);return{session:clone(inventorySessionHydrate(s,inv)),highVarianceLines:clone(high)}}
 if((m=p.match(/^\/api\/inventory\/([^/]+)\/post$/))&&method==='POST'){const inv=s.inventorySessions.find(x=>x.id===m[1]);if(!inv)throw err('Inventaire introuvable',404);assertManage(u,inv.store_id);if(inv.status!=='READY_TO_POST')throw err('L’inventaire doit être validé avant posting.',409);inv.status='POSTED';inv.posted_by=u.id;inv.posted_by_name=u.name;inv.posted_at=now();audit(s,inv.store_id,u,'INVENTORY_POSTED',inv.id,'INVENTORY_SESSION');save(s);return{dynamics:{ok:true,simulated:true,sessionId:inv.id,postedAt:now()},session:clone(inventorySessionHydrate(s,inv))}}
 if(p==='/api/quality-profiles')return clone(s.profiles);
 if(p==='/api/sla-policies'){assertDirector(u);return clone(s.sla)}
 if(p==='/api/dynamics/health'){assertDirector(u);return{connected:false,mode:'SIMULATED',message:'Données Dynamics simulées pour le MVP.'}}
 if(p==='/api/dynamics/entities'){assertDirector(u);const x=(q.get('q')||'').toLowerCase(),rows=[{PublicEntityName:'ReleasedProductsV2',PublicCollectionName:'Released products'},{PublicEntityName:'EcoResProductBarcodeV2',PublicCollectionName:'Product barcodes'},{PublicEntityName:'PurchaseOrderHeadersV2',PublicCollectionName:'Purchase orders'},{PublicEntityName:'RetailPeriodicDiscounts',PublicCollectionName:'Retail promotions'}];return rows.filter(r=>!x||JSON.stringify(r).toLowerCase().includes(x))}
 if((m=p.match(/^\/api\/quality-profiles\/(.+)$/))){const cat=decodeURIComponent(m[1]),pr=profile(s,cat);if(method==='GET')return clone(pr);assertDirector(u);Object.assign(pr,{label:b.label??pr.label,temperature_required:b.temperatureRequired?1:0,temp_min:b.tempMin??null,temp_max:b.tempMax??null,packaging_required:b.packagingRequired?1:0,appearance_required:b.appearanceRequired?1:0,expiry_required:b.expiryRequired?1:0,lot_required:b.lotRequired?1:0,photo_on_nonconform:b.photoOnNonconform?1:0,active:b.active?1:0});save(s);return clone(pr)}
 if((m=p.match(/^\/api\/sla-policies\/(.+)$/))){assertDirector(u);const pol=s.sla.find(x=>x.criticality===m[1]);Object.assign(pol,{response_minutes:Number(b.responseMinutes),resolution_minutes:Number(b.resolutionMinutes),escalation_minutes:Number(b.escalationMinutes),active:b.active?1:0});save(s);return clone(pol)}
 if((m=p.match(/^\/api\/stores\/([^/]+)\/assignees$/))){const storeId=m[1];assertManage(u,storeId);return clone(s.users.filter(x=>x.role==='ops_director'||(x.role==='store_manager'&&x.store_id===storeId)))}
 if((m=p.match(/^\/api\/products\/(.+)$/))){const prod=PRODUCTS[decodeURIComponent(m[1])];if(!prod)throw err('Article introuvable',404);return{...clone(prod),qualityProfile:clone(profile(s,prod.category))}}
 if((m=p.match(/^\/api\/stores\/([^/]+)\/dashboard$/))){const storeId=m[1];assertStore(u,storeId);const day=s.days[storeId],opening=process(s,storeId,'opening'),closing=process(s,storeId,'closing'),ist=incidentStats(s,storeId),qcs=s.qualityControls.filter(x=>x.store_id===storeId),dlc=dlcSummaryMock(s,storeId),handover=handoverStatsMock(s,storeId,day.business_date),inventory=inventorySummaryMock(s,storeId),cycle=dayCycleMock(day);return{day:clone(day),cycle,handover,inventory,opening,closing,dlc,dlcAtRisk:dlc.expired+dlc.critical+dlc.alert+dlc.watch,incidents:ist.open,criticalIncidents:ist.critical,overdueIncidents:ist.overdue,escalatedIncidents:ist.escalated,watchIncidents:ist.watch,qualityControls:qcs.length,qualityRejected:qcs.reduce((a,x)=>a+Number(x.rejected_qty||0),0),health:Math.max(0,100-ist.open*6-ist.escalated*8-opening.blockers*4),lastActions:clone(s.audit.filter(x=>x.store_id===storeId).slice(0,12))}}
 if((m=p.match(/^\/api\/stores\/([^/]+)\/tasks$/))){const storeId=m[1],group=q.get('group')||'opening';assertStore(u,storeId);const day=s.days[storeId],ownerId=group==='opening'?day.opening_owner_id:day.closing_owner_id,owner=s.users.find(x=>x.id===ownerId),tasks=clone(s.tasks[storeId][group]),block=group==='opening'?'STORE_OPENING':'STORE_CLOSING';return{day:{...clone(day),opening_owner_name:group==='opening'?owner?.name:s.users.find(x=>x.id===day.opening_owner_id)?.name||null,closing_owner_name:group==='closing'?owner?.name:s.users.find(x=>x.id===day.closing_owner_id)?.name||null},cycle:dayCycleMock(day),handover:{stats:handoverStatsMock(s,storeId,day.business_date),items:clone(handoverListMock(s,storeId,day.business_date,'ACTIVE'))},tasks,incidents:clone(s.incidents.filter(i=>i.store_id===storeId&&i.status==='OPEN'&&(i.blocking_level===block||i.source_type==='TASK')).map(i=>incidentHydrate(s,i))),timeline:clone(s.audit.filter(a=>a.store_id===storeId).slice(0,60)),opening:process(s,storeId,'opening'),closing:process(s,storeId,'closing')}}
 if((m=p.match(/^\/api\/tasks\/([^/]+)\/form$/))){const id=decodeURIComponent(m[1]);for(const st of Object.values(s.tasks))for(const g of ['opening','closing']){const t=st[g].find(x=>x.id===id);if(t)return{task:clone(t),fields:clone(t.fields)}}throw err('Tâche introuvable',404)}
 if((m=p.match(/^\/api\/tasks\/([^/]+)\/submit$/))){const id=decodeURIComponent(m[1]);let task=null;for(const st of Object.values(s.tasks))for(const g of ['opening','closing']){task=st[g].find(x=>x.id===id)||task}if(!task)throw err('Tâche introuvable',404);assertManage(u,task.store_id);const vals=b.values||{},issues=[];for(const f of task.fields){const v=vals[f.code];if(f.required&&(v===null||v===undefined||v===''))issues.push({label:f.label,message:f.label+' est obligatoire'});if(f.input_type==='BOOLEAN'&&v===false)issues.push({label:f.label,message:f.label+' : non conforme'});if(['NUMBER','MONEY'].includes(f.input_type)&&v!=null){if(f.min_value!=null&&Number(v)<f.min_value)issues.push({label:f.label,message:`${f.label} sous le minimum ${f.min_value}`});if(f.max_value!=null&&Number(v)>f.max_value)issues.push({label:f.label,message:`${f.label} au-dessus du maximum ${f.max_value}`})}}
  if(task.group_name==='closing'&&task.step_order===3){const tol=1;if(Math.abs(Number(vals.ca_commercial)-Number(vals.ca_comptable))>tol)issues.push({message:'Écart CA commercial / comptable supérieur à 1 DH'});if(Math.abs(Number(vals.especes_attendues)-Number(vals.especes_declarees))>tol)issues.push({message:'Écart espèces supérieur à 1 DH'});if(Math.abs(Number(vals.tpe_systeme)-Number(vals.tpe_cloture))>tol)issues.push({message:'Écart TPE supérieur à 1 DH'})}
  task.fields.forEach(f=>f.value=vals[f.code]);if(issues.length){task.status='IN_PROGRESS';const existing=s.incidents.find(i=>i.source_id===task.id&&i.status==='OPEN');if(!existing){const inc=createIncident(s,task.store_id,u,{title:'Non-conformité · '+task.title,description:issues.map(x=>x.message).join(' · '),category:'OPERATIONS',criticality:task.criticality,blockingLevel:task.blocking_level,requiresEvidence:task.criticality==='CRITICAL'});inc.source_type='TASK';inc.source_id=task.id}audit(s,task.store_id,u,'TASK_NONCONFORM',task.id);save(s);throw err('Contrôle non conforme.',409,issues)}
  task.status='COMPLETED';task.completed_by=u.id;task.completed_by_name=u.name;task.completed_at=now();const inc=s.incidents.find(i=>i.source_id===task.id&&i.status==='OPEN');if(inc){inc.status='RESOLVED';inc.resolution_note='Recontrôle conforme';inc.resolved_by_name=u.name;inc.resolved_at=now()}audit(s,task.store_id,u,'TASK_COMPLETED',task.id);save(s);return{ok:true}}
 if((m=p.match(/^\/api\/stores\/([^/]+)\/process\/(opening|closing)\/take$/))){const storeId=m[1],group=m[2];assertManage(u,storeId);const day=s.days[storeId];if(group==='closing'&&day.opening_status!=='OPENED')throw err('La fermeture ne peut commencer qu’après validation de l’ouverture.',409);if(group==='opening'){day.opening_status='IN_PROGRESS';day.opening_owner_id=u.id;day.opening_started_at=day.opening_started_at||now()}else{day.closing_status='IN_PROGRESS';day.closing_owner_id=u.id;day.closing_started_at=day.closing_started_at||now()}audit(s,storeId,u,group.toUpperCase()+'_TAKEN',day.id,'STORE_DAY');save(s);return{ok:true}}
 if((m=p.match(/^\/api\/stores\/([^/]+)\/process\/(opening|closing)\/validate$/))){const storeId=m[1],group=m[2];assertManage(u,storeId);const day=s.days[storeId],pr=process(s,storeId,group);if(pr.done<pr.total)throw err('Tous les contrôles obligatoires ne sont pas conformes.',409,{...pr});const block=group==='opening'?'STORE_OPENING':'STORE_CLOSING',blocked=s.incidents.filter(i=>i.store_id===storeId&&i.status==='OPEN'&&i.blocking_level===block).length;if(blocked)throw err('Un incident bloquant reste ouvert.',409,{openCritical:blocked});if(group==='opening'){const hb=handoverStatsMock(s,storeId,day.business_date).blocking;if(hb)throw err(hb+' passation(s) bloquante(s) doivent être résolues avant ouverture.',409,{handoverBlocking:hb})}if(group==='closing'){if(!day.handover_reviewed_at)throw err('La passation de fin de journée doit être revue avant fermeture.',409,{handoverReviewed:false});const urgent=s.dlc.filter(x=>x.store_id===storeId&&x.status==='ACTIVE').map(x=>dlcHydrate(s,x)).filter(x=>['EXPIRED','DDM_PASSED','CRITICAL'].includes(x.risk.stage)&&x.remaining_quantity>0&&x.pending_action).length;if(urgent)throw err(urgent+' lot(s) DLC/DDM périmé(s) ou critique(s) restent à traiter avant fermeture.',409,{dlcBlocking:urgent})}if(group==='opening'){day.opening_status='OPENED';day.opened_at=now();audit(s,storeId,u,'STORE_OPENED',day.id,'STORE_DAY')}else{day.closing_status='CLOSED';day.closed_at=now();audit(s,storeId,u,'STORE_CLOSED',day.id,'STORE_DAY')}save(s);return{ok:true,progress:process(s,storeId,group)}}
 if((m=p.match(/^\/api\/stores\/([^/]+)\/dlc$/))){const storeId=m[1];assertStore(u,storeId);if(method==='GET'){const st=(q.get('status')||'ACTIVE').toUpperCase(),items=s.dlc.filter(x=>x.store_id===storeId&&(st==='ALL'||x.status===st)).map(x=>dlcHydrate(s,x)).sort((a,b)=>a.risk.daysRemaining-b.risk.daysRemaining);return{summary:dlcSummaryMock(s,storeId),items:clone(items)}}assertManage(u,storeId);const prod=PRODUCTS[b.ean];if(!prod)throw err('EAN inconnu Dynamics',400);if(!b.expiryDate||!(Number(b.quantity)>0))throw err('Date et quantité obligatoires',400);const qn=Number(b.quantity),d={id:uid('dlc'),store_id:storeId,ean:b.ean,product_name:prod.name,expiry_type:b.expiryType||'DLC',department:b.department||null,family:b.family||null,expiry_date:b.expiryDate,quantity:qn,original_quantity:qn,remaining_quantity:qn,unit:b.unit||'pièce',zone:b.zone||'Rayon',lot_ref:b.lotRef||null,comment:b.comment||'',operational_state:'SELLABLE',source_type:b.sourceType||'MANUAL',last_control_at:now(),next_control_at:addMinutes(24),created_by:u.id,created_by_name:u.name,created_at:now(),status:'ACTIVE',treatments:[],evidence:[]};s.dlc.push(d);audit(s,storeId,u,'DLC_CREATED',d.id);save(s);return clone(dlcHydrate(s,d))}
 if((m=p.match(/^\/api\/dlc\/([^/]+)\/treatments$/))){const d=s.dlc.find(x=>x.id===m[1]);if(!d)throw err('Lot DLC introuvable',404);assertManage(u,d.store_id);const ac=DLC_ACTIONS.find(x=>x.code===b.actionType);if(!ac)throw err('Action DLC inconnue',400);const curRisk=dlcRisk(s,d);if(!curRisk.allowedActions.includes(ac.code))throw err('Action non autorisée pour le statut '+curRisk.label,409);const before=Number(d.remaining_quantity??d.quantity),qty=Number(b.quantity||0);if(ac.removesStock&&(!(qty>0)||qty>before))throw err('Quantité traitée invalide',400);if(ac.proof&&!b.dataUrl)throw err('Une preuve photo/PDF est obligatoire pour cette action.',409);const after=ac.removesStock?before-qty:before,t={id:uid('dt'),action_type:ac.code,quantity:ac.removesStock?qty:0,quantity_before:before,quantity_after:after,note:b.note||'',performed_by:u.id,performed_by_name:u.name,performed_at:now()};d.treatments=d.treatments||[];d.treatments.unshift(t);if(b.dataUrl){d.evidence=d.evidence||[];d.evidence.unshift({id:uid('dev'),file_name:b.fileName||'preuve',caption:b.caption||'',created_by_name:u.name,created_at:now(),dataUrl:b.dataUrl})}d.remaining_quantity=after;d.quantity=after;d.operational_state=['DESTROY','RETURN_SUPPLIER','DONATE'].includes(ac.code)?(after<=0?'DISPOSED':'ISOLATED'):{WITHDRAW_SHELF:'ISOLATED',QUALITY_REVIEW:'ISOLATED',MARKDOWN:'SHORT_DATE',SHORT_DATE_PROMO:'SHORT_DATE',FEFO_ROTATE:'FEFO',NO_ACTION:'SELLABLE'}[ac.code]||d.operational_state;if(after<=0){d.status='CLOSED';d.closed_by_name=u.name;d.closed_at=now()}else d.next_control_at=addMinutes(['EXPIRED','DDM_PASSED','CRITICAL'].includes(dlcRisk(s,d).stage)?4:24);audit(s,d.store_id,u,'DLC_TREATMENT',d.id);save(s);return clone(dlcHydrate(s,d))}
 if((m=p.match(/^\/api\/dlc\/([^/]+)\/recheck$/))){const d=s.dlc.find(x=>x.id===m[1]);if(!d)throw err('Lot DLC introuvable',404);assertManage(u,d.store_id);const qn=Number(b.quantity);if(!Number.isFinite(qn)||qn<0)throw err('Quantité invalide',400);d.remaining_quantity=qn;d.quantity=qn;d.last_control_at=now();if(qn===0){d.status='CLOSED';d.closed_by_name=u.name;d.closed_at=now()}else d.next_control_at=addMinutes(24);audit(s,d.store_id,u,'DLC_RECHECKED',d.id);save(s);return clone(dlcHydrate(s,d))}
 if((m=p.match(/^\/api\/stores\/([^/]+)\/receipts$/))){const storeId=m[1];assertStore(u,storeId);return clone(s.receipts.filter(x=>x.store_id===storeId))}
 if((m=p.match(/^\/api\/receipts\/([^/]+)\/lines\/([^/]+)\/quality$/))){const po=decodeURIComponent(m[1]),lineId=m[2],r=s.receipts.find(x=>x.po_number===po);if(!r)throw err('PO introuvable',404);assertManage(u,r.store_id);const line=r.lines.find(x=>x.id===lineId);if(!line)throw err('Ligne introuvable',404);const delivered=Number(b.deliveredQty),accepted=Number(b.acceptedQty),rejected=Number(b.rejectedQty);if(Math.abs(accepted+rejected-delivered)>.0001)throw err('Accepté + refusé doit être égal au livré',400);const pr=profile(s,line.category),issues=qualityIssues(pr,b);if(issues.length&&rejected===0)throw err('Non-conformité détectée : renseigner la quantité refusée.',409,issues);const decision=rejected===0?'ACCEPT':accepted===0?'REJECT':'PARTIAL',qc={id:uid('qc'),store_id:r.store_id,context:'Réception',po_number:r.po_number,ean:line.ean,product_name:line.product_name,category:line.category,ordered_qty:line.ordered_qty,delivered_qty:delivered,accepted_qty:accepted,rejected_qty:rejected,temperature:b.temperature,temperature_status:issues.some(x=>String(x).includes('Température'))?'NOK':b.temperature==null?'NA':'OK',packaging_status:b.packagingStatus||'NA',appearance_status:b.appearanceStatus||'NA',expiry_date:b.expiryDate||null,lot_ref:b.lotRef||null,decision,comment:b.comment||'',controlled_by:u.id,controlled_by_name:u.name,created_at:now()};s.qualityControls.unshift(qc);Object.assign(line,{delivered_qty:delivered,accepted_qty:accepted,rejected_qty:rejected,quality_control_id:qc.id});if(b.expiryDate&&accepted>0)s.dlc.push({id:uid('dlc'),store_id:r.store_id,ean:line.ean,product_name:line.product_name,expiry_date:b.expiryDate,quantity:accepted,zone:'Réserve',lot_ref:b.lotRef||null,comment:'Réception '+r.po_number,created_by:u.id,created_by_name:u.name,status:'ACTIVE'});if(decision!=='ACCEPT'||issues.length){const inc=createIncident(s,r.store_id,u,{title:'Non-conformité réception · '+line.product_name,description:issues.join(' · ')||b.comment,category:'RECEPTION',criticality:issues.some(x=>String(x).includes('Température'))?'CRITICAL':'HIGH',requiresEvidence:true});inc.actions.push({id:uid('ia'),title:'Décider du traitement fournisseur / produit',status:'OPEN',assigned_to:u.id,assigned_to_name:u.name,created_at:now()})}audit(s,r.store_id,u,'RECEIPT_LINE_CONTROLLED',line.id);save(s);return{id:qc.id,decision,issues,qualityProfile:clone(pr)}}
 if((m=p.match(/^\/api\/receipts\/([^/]+)\/post$/))){const po=decodeURIComponent(m[1]),r=s.receipts.find(x=>x.po_number===po);if(!r)throw err('PO introuvable',404);assertManage(u,r.store_id);if(r.lines.some(l=>!l.quality_control_id))throw err('Toutes les lignes doivent avoir un contrôle qualité avant réception système',409);r.status='POSTED';audit(s,r.store_id,u,'RECEIPT_POSTED',r.id);save(s);return{ok:true,mode:'SIMULATED',po}}
 if((m=p.match(/^\/api\/stores\/([^/]+)\/quality$/))){const storeId=m[1];assertStore(u,storeId);return clone(s.qualityControls.filter(x=>x.store_id===storeId))}
 if((m=p.match(/^\/api\/stores\/([^/]+)\/incidents$/))){const storeId=m[1];assertStore(u,storeId);if(method==='GET'){const st=(q.get('status')||'OPEN').toUpperCase(),rows=s.incidents.filter(i=>i.store_id===storeId&&(st==='ALL'||i.status===st)).map(i=>incidentHydrate(s,i));return{stats:incidentStats(s,storeId),items:clone(rows)}}assertManage(u,storeId);const i=createIncident(s,storeId,u,b);save(s);return clone(i)}
 if((m=p.match(/^\/api\/incidents\/([^/]+)$/))){const i=s.incidents.find(x=>x.id===m[1]);if(!i)throw err('Incident introuvable',404);assertStore(u,i.store_id);return clone(incidentHydrate(s,i))}
 if((m=p.match(/^\/api\/incidents\/([^/]+)\/actions$/))){const i=s.incidents.find(x=>x.id===m[1]);if(!i)throw err('Incident introuvable',404);assertManage(u,i.store_id);i.actions.push({id:uid('ia'),title:b.title||'Action corrective',note:b.note||'',status:'OPEN',assigned_to:b.assignedTo||i.assigned_to,assigned_to_name:s.users.find(x=>x.id===(b.assignedTo||i.assigned_to))?.name||null,due_at:b.dueAt||i.due_at,created_at:now()});save(s);return clone(incidentHydrate(s,i))}
 if((m=p.match(/^\/api\/incidents\/([^/]+)\/actions\/([^/]+)\/complete$/))){const i=s.incidents.find(x=>x.id===m[1]);if(!i)throw err('Incident introuvable',404);assertManage(u,i.store_id);const a=i.actions.find(x=>x.id===m[2]);if(!a)throw err('Action introuvable',404);Object.assign(a,{status:'DONE',completion_note:b.note||'',completed_by_name:u.name,completed_at:now()});save(s);return clone(incidentHydrate(s,i))}
 if((m=p.match(/^\/api\/incidents\/([^/]+)\/evidence$/))){const i=s.incidents.find(x=>x.id===m[1]);if(!i)throw err('Incident introuvable',404);assertManage(u,i.store_id);i.evidence.push({id:uid('ev'),file_name:b.fileName||'preuve.jpg',caption:b.caption||'',created_by_name:u.name,created_at:now(),dataUrl:b.dataUrl});save(s);return clone(incidentHydrate(s,i))}
 if((m=p.match(/^\/api\/incidents\/([^/]+)\/resolve$/))){const i=s.incidents.find(x=>x.id===m[1]);if(!i)throw err('Incident introuvable',404);assertManage(u,i.store_id);if(i.actions.some(a=>a.status==='OPEN'))throw err(i.actions.filter(a=>a.status==='OPEN').length+' action(s) corrective(s) restent ouvertes.',409);if(i.requires_evidence&&!i.evidence.length)throw err('Une preuve photo est obligatoire avant clôture.',409);if(!b.resolutionNote?.trim())throw err('Compte-rendu de résolution obligatoire.',400);Object.assign(i,{status:'RESOLVED',resolution_note:b.resolutionNote,resolved_by_name:u.name,resolved_at:now()});audit(s,i.store_id,u,'INCIDENT_RESOLVED',i.id);save(s);return clone(incidentHydrate(s,i))}
 if((m=p.match(/^\/api\/incidents\/([^/]+)\/reopen$/))){const i=s.incidents.find(x=>x.id===m[1]);if(!i)throw err('Incident introuvable',404);assertManage(u,i.store_id);Object.assign(i,{status:'OPEN',resolution_note:null,resolved_by_name:null,resolved_at:null,due_at:addMinutes(120)});save(s);return clone(incidentHydrate(s,i))}
 if(p==='/api/network'){assertDirector(u);return clone(s.stores.map(st=>{const day=s.days[st.id],ist=incidentStats(s,st.id),qcs=s.qualityControls.filter(x=>x.store_id===st.id),owner=s.users.find(x=>x.id===day.opening_owner_id);return{...st,day:{...day,opening_owner_name:owner?.name||null},cycle:dayCycleMock(day),handover:handoverStatsMock(s,st.id,day.business_date),inventory:inventorySummaryMock(s,st.id),opening:process(s,st.id,'opening'),closing:process(s,st.id,'closing'),dlc:dlcSummaryMock(s,st.id),openIncidents:ist.open,criticalIncidents:ist.critical,overdueIncidents:ist.overdue,escalatedIncidents:ist.escalated,watchIncidents:ist.watch,qualityControls:qcs.length,qualityRejected:qcs.reduce((a,x)=>a+Number(x.rejected_qty||0),0),lastAction:s.audit.find(a=>a.store_id===st.id)||null}}))}
 throw err('Route Showcase non implémentée : '+p,404);
}

export async function mockBlob(path){
 const s=load(),m=pathOnly(path).match(/^\/api\/(?:media|dlc-media)\/([^/]+)$/);if(!m)throw err('Preuve introuvable',404);
 for(const i of s.incidents){const e=(i.evidence||[]).find(x=>x.id===m[1]);if(e?.dataUrl){const [head,data]=e.dataUrl.split(',');const mime=head.match(/data:([^;]+)/)?.[1]||'image/jpeg';const bytes=Uint8Array.from(atob(data),c=>c.charCodeAt(0));return new Blob([bytes],{type:mime})}}for(const d of s.dlc){const e=(d.evidence||[]).find(x=>x.id===m[1]);if(e?.dataUrl){const [head,data]=e.dataUrl.split(',');const mime=head.match(/data:([^;]+)/)?.[1]||'image/jpeg';const bytes=Uint8Array.from(atob(data),c=>c.charCodeAt(0));return new Blob([bytes],{type:mime})}}
 throw err('Preuve introuvable',404);
}
