import {api} from './api.js';
import {isDirector,isSupplyChain} from './state.js';
import {esc,toast} from './ui.js';

let loading=false,snapshot=null,dcRequests=[];
const hasAccess=()=>isDirector()||isSupplyChain();
const n=v=>v==null||v===''?'—':Number(v).toLocaleString('fr-FR',{maximumFractionDigits:2});
function injectStyle(){if(document.getElementById('warehouseControlCss'))return;const s=document.createElement('style');s.id='warehouseControlCss';s.textContent=`
.wh-shell{max-width:1180px;margin:0 auto}.wh-hero{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;padding:24px;border:1px solid var(--line);border-radius:24px;background:linear-gradient(135deg,#fff,#f8fbfa)}.wh-hero h2{margin:4px 0 7px;font-size:30px}.wh-hero p{margin:0;color:var(--muted);max-width:760px}.wh-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin:12px 0}.wh-kpi,.wh-card{border:1px solid var(--line);border-radius:17px;background:#fff;padding:13px}.wh-kpi span,.wh-card small{display:block;color:var(--muted);font-size:10px}.wh-kpi strong{display:block;font-size:24px;margin-top:4px}.wh-section{margin-top:16px}.wh-section-head{display:flex;justify-content:space-between;gap:12px;align-items:end;margin-bottom:9px}.wh-section-head h3{margin:0;font-size:19px}.wh-section-head p{margin:3px 0 0;color:var(--muted);font-size:11px}.wh-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.wh-group{border:1px solid var(--line);border-radius:18px;padding:14px;background:#fff}.wh-group header{display:flex;justify-content:space-between;gap:12px}.wh-group h4{margin:2px 0}.wh-lines{display:grid;gap:6px;margin-top:10px}.wh-line{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;padding:9px;border-radius:11px;background:#f8f6f7}.wh-line strong,.wh-line span{display:block}.wh-line span{font-size:10px;color:var(--muted);margin-top:2px}.wh-table-wrap{overflow:auto;border:1px solid var(--line);border-radius:18px;background:#fff}.wh-table{width:100%;border-collapse:collapse;min-width:800px}.wh-table th,.wh-table td{padding:11px;border-bottom:1px solid var(--line);text-align:left;font-size:11px}.wh-table th{font-size:9px;text-transform:uppercase;color:var(--muted)}.wh-status{display:inline-flex;padding:4px 7px;border-radius:999px;background:#f3eef0;font-size:9px;font-weight:850}.wh-status.danger{background:#fff0f3;color:#a20c3a}.wh-status.ok{background:#edf8f1;color:#18743e}.wh-request-actions{display:flex;gap:8px;margin-top:10px}.wh-request-actions .btn{width:100%;min-height:44px}.wh-empty{padding:24px;text-align:center;color:var(--muted);border:1px dashed var(--line);border-radius:18px}.director-experience #warehouseControlNav,.supply-chain-only #warehouseControlNav{display:block!important}.supply-chain-only #nav button:not(#warehouseControlNav){display:none!important}.supply-chain-only #storeSelect{display:none!important}@media(max-width:900px){.wh-kpis{grid-template-columns:repeat(3,1fr)}.wh-grid{grid-template-columns:1fr}}@media(max-width:620px){.wh-hero{flex-direction:column}.wh-kpis{grid-template-columns:1fr 1fr}}
`;document.head.appendChild(s)}
function ensureShell(){if(!hasAccess())return null;injectStyle();const nav=document.getElementById('nav');let b=document.getElementById('warehouseControlNav');if(nav&&!b){b=document.createElement('button');b.id='warehouseControlNav';b.dataset.page='warehouseControl';b.dataset.mobileLabel='Entrepôt';b.textContent='Entrepôt';const network=nav.querySelector('[data-page="network"]');network?.after(b)}else if(b&&!b.dataset.mobileLabel)b.dataset.mobileLabel='Entrepôt'let page=document.getElementById('warehouseControlPage');if(!page){page=document.createElement('section');page.className='page';page.id='warehouseControlPage';page.innerHTML='<div id="warehouseControlContent"></div>';document.querySelector('main')?.appendChild(page)}return page}
function lineHtml(x,qtyKey){return `<div class="wh-line"><div><strong>${esc(x.product||x.productNumber||'Article')}</strong><span>${esc(x.productNumber||'')}${x.ean&&x.ean!==x.productNumber?` · EAN ${esc(x.ean)}`:''}${x.storeName?` · ${esc(x.storeName)}`:''} · stock magasin ${n(x.availableQty)} · ventes ${x.dailySales==null?'—':n(x.dailySales)+'/j'}${x.coverageDays==null?'':` · ${n(x.coverageDays)} j de couverture`}</span></div><strong>${n(x[qtyKey])} u.</strong></div>`}
function supplierGroups(groups=[]){if(!groups.length)return'<div class="wh-empty">Aucun besoin d’achat fournisseur détecté.</div>';return `<div class="wh-grid">${groups.map(g=>`<article class="wh-group"><header><div><span class="manager-eyebrow">${g.storeName?'DIRECT · '+esc(g.storeName):'PO FOURNISSEUR · DC'}</span><h4>${esc(g.supplier||'À affecter')}</h4><small>${esc(g.supplierAccount||'Compte fournisseur non identifié')}</small></div><strong>${n(g.totalQty)} u.</strong></header><div class="wh-lines">${(g.lines||[]).map(x=>lineHtml(x,'purchaseQty')).join('')}</div></article>`).join('')}</div>`}
function transferGroups(groups=[]){if(!groups.length)return'<div class="wh-empty">Aucun transfert entrepôt → magasin à préparer.</div>';return `<div class="wh-grid">${groups.map(g=>`<article class="wh-group"><header><div><span class="manager-eyebrow">TRANSFERT MAGASIN</span><h4>${esc(g.storeName||g.storeCode||g.storeId)}</h4><small>${esc(g.sourceWarehouse||'Entrepôt source')}</small></div><strong>${n(g.totalQty)} u.</strong></header><div class="wh-lines">${(g.lines||[]).map(x=>lineHtml(x,'transferQty')).join('')}</div></article>`).join('')}</div>`}
function requestStatusLabel(s){return{REQUESTED:'À valider',APPROVED:'Validé',SENT:'Envoyé',PARTIAL_RECEIVED:'Partiel',RECEIVED:'Reçu',REJECTED:'Refusé',CANCELLED:'Annulé'}[s]||s}
function dcRequestList(rows=[]){
 const active=rows.filter(x=>x?.recommendationSnapshot?.decision==='DC_BACKORDER'&&!['RECEIVED','REJECTED','CANCELLED'].includes(x.status));
 if(!active.length)return'<div class="wh-empty">Aucun besoin DC transmis par les magasins.</div>';
 return `<div class="wh-grid">${active.map(x=>`<article class="wh-group wh-dc-request"><header><div><span class="manager-eyebrow">BESOIN DC · ${esc(x.store_id||'')}</span><h4>${esc(x.product_name||x.product_number)}</h4><small>${esc(x.product_number||'')} · ${n(x.requested_qty)} ${esc(x.unit||'u.')}</small></div><span class="wh-status ${x.status==='REQUESTED'?'danger':'ok'}">${esc(requestStatusLabel(x.status))}</span></header><div class="wh-lines"><div class="wh-line"><div><strong>LVE Lakhyayta à 0</strong><span>Besoin transmis par le magasin · ${esc(x.requested_by_name||'')}</span></div><strong>${n(x.requested_qty)} u.</strong></div></div><div class="wh-request-actions">${x.status==='REQUESTED'?`<button class="btn brand" data-wh-request-action="APPROVE" data-wh-request-id="${esc(x.id)}">Valider le besoin</button>`:''}${x.status==='APPROVED'?`<button class="btn brand" data-wh-request-action="SEND" data-wh-request-id="${esc(x.id)}">Marquer traité / ERP</button>`:''}</div></article>`).join('')}</div>`
}
async function actOnDcRequest(button){
 const id=button?.dataset.whRequestId,action=button?.dataset.whRequestAction;if(!id||!action)return;
 let externalReference='';if(action==='SEND'){externalReference=prompt('Référence Dynamics / ERP du traitement DC :','')||'';if(!externalReference.trim())return}
 button.disabled=true;
 try{await api(`/api/replenishment-requests/${encodeURIComponent(id)}/status`,{method:'POST',body:JSON.stringify({action,externalReference})});toast(action==='APPROVE'?'Besoin DC validé.':'Besoin DC marqué envoyé / traité.');await load(true)}
 catch(e){toast(e.message);button.disabled=false}
}
function productsTable(rows=[]){if(!rows.length)return'<div class="wh-empty">Aucun produit sous tension.</div>';return `<div class="wh-table-wrap"><table class="wh-table"><thead><tr><th>Article</th><th>Magasins</th><th>Besoin réseau</th><th>Stock entrepôt</th><th>Transfert</th><th>Achat</th><th>Fournisseur</th></tr></thead><tbody>${rows.slice(0,120).map(x=>`<tr><td><strong>${esc(x.product||x.productNumber)}</strong><br><span class="small muted">${esc(x.productNumber||x.ean||'')}</span></td><td>${n(x.storeCount)}</td><td>${n(x.networkNeedQty)}</td><td>${x.centralStock==null?'—':n(x.centralStock)}</td><td>${n(x.transferQty)}</td><td>${n(x.purchaseQty)}</td><td>${esc(x.supplier||'À affecter')}</td></tr>`).join('')}</tbody></table></div>`}
function storesTable(rows=[]){return `<div class="wh-table-wrap"><table class="wh-table"><thead><tr><th>Magasin</th><th>Ruptures</th><th>Proches ruptures</th><th>Transferts</th><th>Achats</th><th>Stock source</th></tr></thead><tbody>${rows.map(x=>`<tr><td><strong>${esc(x.name||x.code)}</strong></td><td>${x.status==='READY'?n(x.ruptures):'—'}</td><td>${x.status==='READY'?n(x.nearStockouts):'—'}</td><td>${x.status==='READY'?n(x.transfers):'—'}</td><td>${x.status==='READY'?n(x.purchases):'—'}</td><td><span class="wh-status ${x.status==='READY'?'ok':'danger'}">${esc(x.status==='READY'?'Connecté':'À vérifier')}</span></td></tr>`).join('')}</tbody></table></div>`}
function render(){const root=document.getElementById('warehouseControlContent');if(!root)return;if(!snapshot){root.innerHTML='<div class="wh-shell"><div class="wh-empty">Chargement du cockpit approvisionnement…</div></div>';return}const m=snapshot.metrics||{};root.innerHTML=`<div class="wh-shell"><div class="wh-hero"><div><span class="manager-eyebrow">ENTREPÔT & APPROVISIONNEMENT</span><h2>Piloter le réseau avant la rupture.</h2><p>StoreOps croise ventes, couverture, stock magasin et stock entrepôt pour prioriser les transferts et consolider les besoins fournisseurs.</p></div><button class="btn soft" id="whRefresh">Actualiser</button></div><div class="wh-kpis"><div class="wh-kpi"><span>Ruptures</span><strong>${n(m.ruptures)}</strong></div><div class="wh-kpi"><span>Proches ruptures</span><strong>${n(m.nearStockouts)}</strong></div><div class="wh-kpi"><span>Transferts à préparer</span><strong>${n(m.transferLines)}</strong></div><div class="wh-kpi"><span>Achats DC</span><strong>${n(m.dcPurchaseLines)}</strong></div><div class="wh-kpi"><span>Direct fournisseur</span><strong>${n(m.directPurchaseLines)}</strong></div><div class="wh-kpi"><span>PO DC</span><strong>${n(m.supplierOrders)}</strong></div><div class="wh-kpi"><span>Commandes directes</span><strong>${n(m.directSupplierOrders)}</strong></div><div class="wh-kpi"><span>Stock source inconnu</span><strong>${n(m.unknownSupply)}</strong></div></div><section class="wh-section"><div class="wh-section-head"><div><h3>Besoins DC transmis par les magasins</h3><p>Quand LVE est à 0, le magasin transmet son besoin ici au lieu de créer un PO fournisseur.</p></div></div>${dcRequestList(dcRequests)}</section><section class="wh-section"><div class="wh-section-head"><div><h3>Achats pour le DC · LVE Lakhyayta</h3><p>Uniquement les articles marqués DC dans ReleasedProductsV2. Le fournisseur alimente l’entrepôt.</p></div></div>${supplierGroups(snapshot.supplierGroups)}</section><section class="wh-section"><div class="wh-section-head"><div><h3>Commandes directes fournisseurs → magasins</h3><p>Articles marqués Direct : aucun passage par LVE.</p></div></div>${supplierGroups(snapshot.directSupplierGroups)}</section><section class="wh-section"><div class="wh-section-head"><div><h3>Transferts LVE → magasins</h3><p>Priorité aux produits que l’entrepôt peut couvrir immédiatement.</p></div></div>${transferGroups(snapshot.transferGroups)}</section><section class="wh-section"><div class="wh-section-head"><div><h3>Tension par article</h3><p>Vision réseau des besoins, du disponible entrepôt et du reliquat à acheter.</p></div></div>${productsTable(snapshot.products)}</section><section class="wh-section"><div class="wh-section-head"><div><h3>Couverture magasins</h3><p>Les sources indisponibles sont signalées, jamais remplacées par un faux zéro.</p></div></div>${storesTable(snapshot.stores||[])}</section></div>`;document.getElementById('whRefresh')?.addEventListener('click',()=>load(true))}
async function load(force=false){if(loading)return;loading=true;try{const [snap,requests]=await Promise.all([api('/api/warehouse-control'+(force?'?force=1':'')),api('/api/network/replenishment-requests?limit=500').catch(()=>({items:[]}))]);snapshot=snap;dcRequests=requests.items||[];render();if(force)toast('Cockpit approvisionnement actualisé.')}catch(e){const root=document.getElementById('warehouseControlContent');if(root)root.innerHTML=`<div class="wh-shell"><div class="banner ban-danger"><strong>Cockpit Entrepôt indisponible</strong><span>${esc(e.message||'Impossible de charger les données.')}</span></div></div>`}finally{loading=false}}
function activate(){if(!hasAccess())return;ensureShell();document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById('warehouseControlPage')?.classList.add('active');document.querySelectorAll('#nav button').forEach(x=>x.classList.remove('active'));document.getElementById('warehouseControlNav')?.classList.add('active');window.scrollTo({top:0,behavior:'smooth'});snapshot=null;render();load()}
function bind(){if(!hasAccess())return;ensureShell();if(isSupplyChain()){document.body.classList.add('supply-chain-only');setTimeout(activate,80)}document.addEventListener('click',e=>{const request=e.target.closest('[data-wh-request-action]');if(request){e.preventDefault();e.stopImmediatePropagation();return actOnDcRequest(request)}const b=e.target.closest('#warehouseControlNav');if(!b)return;e.preventDefault();e.stopImmediatePropagation();activate()},true)}
bind();
